.circleci/config.yml, .githooks/pre-commit, src/main/java/com/google/api/generator/engine/ast/AstNode.java, src/main/java/com/google/api/generator/engine/basics/Identifier.java, src/main/java/com/google/api/generator/engine/basics/Reference.java, src/main/java/com/google/api/generator/engine/basics/Type.java, src/main/java/com/google/api/generator/engine/lexicon/InvalidSymbol.java, src/main/java/com/google/api/generator/engine/lexicon/Keyword.java, src/main/java/com/google/api/generator/engine/lexicon/Literal.java, src/main/java/com/google/api/generator/engine/lexicon/Operator.java, src/main/java/com/google/api/generator/engine/lexicon/Separator.java, src/test/java/com/google/api/generator/engine/basics/IdentifierTest.java, src/test/java/com/google/api/generator/engine/basics/TypeTest.java, src/test/java/com/google/api/generator/engine/lexicon/InvalidSymbolTest.java, src/test/java/com/google/api/generator/engine/lexicon/KeywordTest.java, src/test/java/com/google/api/generator/engine/lexicon/LiteralTest.java, src/test/java/com/google/api/generator/engine/lexicon/OperatorTest.java, src/test/java/com/google/api/generator/engine/lexicon/SeparatorTest.java
1. add license headers to all source files
2. add header check to precommit hook
3. add header check to circleCI workflow
=> [ggj][build] add header check to precommit hook

src/main/java/com/google/api/generator/engine/ast/ObjectValue.java
Concrete object value types will inherit from this interface.
=> [ggj] feat: add ObjectValue

src/main/java/com/google/api/generator/engine/ast/TypeNode.java
This will be needed for expressions.
=> [ggj] feat: add void type

src/main/java/com/google/api/generator/engine/ast/AssignmentExpr.java, src/main/java/com/google/api/generator/engine/ast/Expr.java, src/main/java/com/google/api/generator/engine/ast/PrimitiveValue.java, src/main/java/com/google/api/generator/engine/ast/TypeMismatchException.java, src/main/java/com/google/api/generator/engine/ast/ValueExpr.java, src/main/java/com/google/api/generator/engine/ast/VariableExpr.java, src/main/java/com/google/api/generator/engine/writer/JavaWriterVisitor.java, src/test/java/com/google/api/generator/engine/ast/AssignmentExprTest.java, src/test/java/com/google/api/generator/engine/ast/BUILD.bazel, src/test/java/com/google/api/generator/engine/ast/PrimitiveValueTest.java, src/test/java/com/google/api/generator/engine/writer/JavaWriterVisitorTest.java
This will help with polymorphic "redirection" in the visitor.
=> [ggj] fix!: make Expr extend AstNode

src/main/java/com/google/api/generator/engine/ast/ObjectValue.java
Makes the API surface more clear.
=> [ggj] fix: add type() override to ObjectValue

src/main/java/com/google/api/generator/engine/ast/MethodDefinition.java, src/main/java/com/google/api/generator/engine/ast/MethodInvocationExpr.java, src/test/java/com/google/api/generator/engine/ast/BUILD.bazel, src/test/java/com/google/api/generator/engine/ast/MethodDefinitionTest.java, src/test/java/com/google/api/generator/engine/ast/MethodInvocationExprTest.java
Add check null test in MethodDefinition
Add unit test in MethodInvocationExpr
=> build: integrate null value in method

src/main/java/com/google/api/generator/engine/ast/AssignmentExpr.java, src/main/java/com/google/api/generator/engine/ast/StringObjectValue.java, src/main/java/com/google/api/generator/engine/ast/TernaryExpr.java, src/main/java/com/google/api/generator/engine/ast/ValueExpr.java, src/main/java/com/google/api/generator/engine/ast/VariableExpr.java, src/main/java/com/google/api/generator/engine/ast/WhileStatement.java
Group the contents of class following go/java-style#s3.4.2-ordering-class-contents
=> [ggj]fix: order class contents by java style

src/main/java/com/google/api/generator/engine/ast/IdentifierNode.java, src/main/java/com/google/api/generator/engine/ast/MethodDefinition.java, src/main/java/com/google/api/generator/engine/ast/MethodInvocationExpr.java, src/main/java/com/google/api/generator/engine/ast/VariableExpr.java, src/main/java/com/google/api/generator/engine/writer/ImportWriterVisitor.java, src/main/java/com/google/api/generator/engine/writer/JavaWriterVisitor.java, src/main/java/com/google/api/generator/gapic/composer/ServiceClientClassComposer.java, src/test/java/com/google/api/generator/engine/ast/ExprStatementTest.java, src/test/java/com/google/api/generator/engine/ast/MethodDefinitionTest.java, src/test/java/com/google/api/generator/engine/ast/MethodInvocationExprTest.java, src/test/java/com/google/api/generator/engine/ast/VariableExprTest.java, src/test/java/com/google/api/generator/engine/writer/ImportWriterVisitorTest.java, src/test/java/com/google/api/generator/engine/writer/JavaWriterVisitorTest.java
=> [ggj] fix!: MethodInvocationExpr: use TypeNode instead of names for static refs

src/main/java/com/google/api/generator/engine/ast/ArithmeticOperationExpr.java, src/main/java/com/google/api/generator/engine/ast/AstNodeVisitor.java, src/main/java/com/google/api/generator/engine/writer/ImportWriterVisitor.java, src/main/java/com/google/api/generator/engine/writer/JavaWriterVisitor.java, src/test/java/com/google/api/generator/engine/ast/ArithmeticOperationExprTest.java, src/test/java/com/google/api/generator/engine/ast/BUILD.bazel, src/test/java/com/google/api/generator/engine/writer/ImportWriterVisitorTest.java, src/test/java/com/google/api/generator/engine/writer/JavaWriterVisitorTest.java
Add arithmetic expr and its unit test:
- importvisitor test
- javawritevisitor test
=> [javanaut] feat: Add arithmetic operation expr with unit test

src/main/java/com/google/api/generator/gapic/utils/JavaStyle.java, src/test/java/com/google/api/generator/gapic/BUILD.bazel, src/test/java/com/google/api/generator/gapic/utils/BUILD.bazel, src/test/java/com/google/api/generator/gapic/utils/JavaStyleTest.java
Analogous to the [monolith's change](https://github.com/googleapis/gapic-generator/pull/3265).
=> [ggj][engx] fix: handle post-digit caps, add test, and robustify JavaStyle

test/integration/BUILD.bazel, test/integration/goldens/logging/LoggingServiceV2StubSettings.java
This will go away soon, so this golden update is meant to provide a historical checkpoint and baseline for future readers.
=> [ggj][engx] test: update logging integration goldens with gapic.yaml

src/main/java/com/google/api/generator/gapic/composer/ServiceClientClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/ServiceClientCommentComposer.java, src/main/java/com/google/api/generator/gapic/composer/ServiceClientSampleCodeComposer.java, src/test/java/com/google/api/generator/gapic/composer/ServiceClientSampleCodeComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/goldens/EchoClient.golden, src/test/java/com/google/api/generator/gapic/composer/goldens/IdentityClient.golden, test/integration/goldens/asset/AssetServiceClient.java, test/integration/goldens/library/LibraryServiceClient.java, test/integration/goldens/logging/ConfigClient.java, test/integration/goldens/logging/LoggingClient.java, test/integration/goldens/logging/MetricsClient.java, test/integration/goldens/redis/CloudRedisClient.java
java-logging client paged callable method [sample code](https://github.com/googleapis/java-logging/blob/release-v1.101.3/google-cloud-logging/src/main/java/com/google/cloud/logging/v2/ConfigClient.java#L258-L270)
```
* try (ConfigClient configClient = ConfigClient.create()) {
*   ParentName parent = ProjectName.of("[PROJECT]");
*   ListSinksRequest request = ListSinksRequest.newBuilder()
*     .setParent(parent.toString())
*     .build();
*   ApiFuture<ListSinksPagedResponse> future = configClient.listSinksPagedCallable().futureCall(request);
*   // Do something
*   for (LogSink element : future.get().iterateAll()) {
*     // doThingsWith(element);
*   }
* }
```
=> [2/3]Implement Paged Callable Method

src/test/java/com/google/api/generator/gapic/composer/BUILD.bazel, src/test/java/com/google/api/generator/gapic/composer/samplecode/BUILD.bazel, src/test/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientSampleCodeComposerTest.java, test/integration/goldens/logging/MetricsClient.java
`samplecode-master` rebased on `dev_composer` branch.
This PR is move `ServiceClientSampleCodeComposerTest` from `src/test/.../composer` to `src/test/.../composer/samplecode`.
=> [rebase][samplecode] rebase dev_composer and correct samplecode test position

src/main/java/com/google/api/generator/gapic/composer/ServiceClientClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/samplecode/BUILD.bazel, src/main/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientSampleCodeComposer.java, src/test/java/com/google/api/generator/gapic/composer/goldens/EchoClient.golden, src/test/java/com/google/api/generator/gapic/composer/goldens/IdentityClient.golden, src/test/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientSampleCodeComposerTest.java, test/integration/goldens/asset/AssetServiceClient.java, test/integration/goldens/credentials/IamCredentialsClient.java, test/integration/goldens/library/LibraryServiceClient.java, test/integration/goldens/logging/ConfigClient.java, test/integration/goldens/logging/LoggingClient.java, test/integration/goldens/logging/MetricsClient.java, test/integration/goldens/redis/CloudRedisClient.java
Unary rpc callable method sample code:
```
* try (EchoClient echoClient = EchoClient.create()) {
*   EchoRequest request = EchoRequest.newBuilder().build();
*   ApiFuture&lt;EchoResponse&gt; future = echoClient.echoCallable().futureCall(request);
*   // Do something
*   EchoResponse response = future.get();
* }
* 
```
=> [samplecode][1/3]Implement unary callable sample code

src/test/java/com/google/api/generator/gapic/composer/goldens/GrpcTestingStub.golden, src/test/java/com/google/api/generator/gapic/composer/goldens/TestingClientTest.golden, src/test/java/com/google/api/generator/gapic/protoparser/HttpRuleParserTest.java, src/test/java/com/google/api/generator/gapic/testdata/testing.proto
=> chore: add test for enums in HTTP annotations [ggj]

src/main/java/com/google/api/generator/engine/ast/ThrowExpr.java, src/main/java/com/google/api/generator/engine/writer/ImportWriterVisitor.java, src/main/java/com/google/api/generator/engine/writer/JavaWriterVisitor.java, src/test/java/com/google/api/generator/engine/ast/ThrowExprTest.java, src/test/java/com/google/api/generator/engine/writer/ImportWriterVisitorTest.java, src/test/java/com/google/api/generator/engine/writer/JavaWriterVisitorTest.java
Closes #808. This is needed for #804, so we can rethrow exceptions.
=> feat(ast): support throwing all kinds of expressions [ggj]

src/main/java/com/google/api/generator/gapic/composer/grpc/ServiceClientTestClassComposer.java
=> Remove extraneous call

src/main/java/com/google/api/generator/gapic/composer/common/AbstractTransportServiceStubClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/grpcrest/GrpcRestContext.java, src/main/java/com/google/api/generator/gapic/composer/rest/HttpJsonServiceCallableFactoryClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/rest/HttpJsonServiceStubClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/rest/RestContext.java, src/test/java/com/google/api/generator/gapic/composer/rest/goldens/HttpJsonComplianceCallableFactory.golden, src/test/java/com/google/api/generator/gapic/composer/rest/goldens/HttpJsonComplianceStub.golden, test/integration/goldens/compute/com/google/cloud/compute/v1/stub/HttpJsonAddressesStub.java, test/integration/goldens/compute/com/google/cloud/compute/v1/stub/HttpJsonRegionOperationsCallableFactory.java, test/integration/goldens/compute/com/google/cloud/compute/v1/stub/HttpJsonRegionOperationsStub.java
Depends on https://github.com/googleapis/gax-java/pull/1484
=> feat: Add REST AIP-151 LRO suport

rules_java_gapic/resources/gradle/client_grpc.gradle.tmpl, rules_java_gapic/resources/gradle/client_grpcrest.gradle.tmpl, rules_java_gapic/resources/gradle/client_rest.gradle.tmpl, rules_java_gapic/resources/gradle/grpc.gradle.tmpl, rules_java_gapic/resources/gradle/proto.gradle.tmpl
=> fix: fix Gradle build error for sourcesJar task on generated libs

.github/workflows/sonar.yaml
SonarCloud provides code coverage and static code quality analysis.
https://sonarcloud.io/project/overview?id=googleapis_gapic-generator-java
=> chore: Add SonarCloud support

src/main/java/com/google/api/generator/spring/composer/SpringAutoConfigClassComposer.java, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationFull.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpc.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpcRest.golden
This change intend to set the auto-configuration to be enabled by default.
ref: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1364#discussion_r1036162159
=> fix(spring): set autoconfig to be enabled by default.

.github/.OwlBot.lock.yaml, .github/.OwlBot.yaml, java-common-protos/.OwlBot.yaml, java-iam/.OwlBot.yaml
Preparing OwlBot configuration files for this gapic-generator-java monorepo.
=> build: OwlBot configuration fix for monorepo

.kokoro/release/publish_javadoc11.cfg, .kokoro/release/publish_javadoc11.sh
This PR introduces `publish_javadoc.sh` job and its config for the monorepo.
=> chore: Cloud RAD setup

.kokoro/presubmit/downstream-build.sh, .kokoro/settings.xml
`settings.xml` copied from https://github.com/googleapis/google-cloud-java/blob/main/settings.xml
=> ci: Add .kokoro/settings.xml to use maven mirror

.github/workflows/ci-maven.yaml, pom.xml
=> fix: support mvn fmt:check and fmt:format

.github/workflows/ci-maven.yaml, .github/workflows/downstream-native-image.yaml, .github/workflows/nightly.yaml, .github/workflows/sonar.yaml, gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpJsonDirectServerStreamingCallableTest.java
=> ci: add nightly build workflow

.github/workflows/ci-maven.yaml, .github/workflows/downstream-native-image.yaml, showcase/gapic-showcase/pom.xml, showcase/grpc-gapic-showcase-v1beta1/pom.xml, showcase/proto-gapic-showcase-v1beta1/pom.xml
> @suztomo : The failure is unclear. In another pull request, would you separate golden test and integration tests?
CC: @mpeddada1
=> ci: split showcase golden and integration test phases

gax-java/CONTRIBUTING.md
=> chore: update CONTRIBUTING.md

.github/workflows/ci-maven.yaml
=> feat: install compatibility check

gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpRequestRunnableTest.java
=> chore: Fix unicode flaky test with utf-8 as default charset

.kokoro/presubmit/downstream-build.sh
Follow up to https://github.com/googleapis/gapic-generator-java/pull/1518
Instead of replacing the GAPIC BOM version in `google-cloud-java/shared-dependencies/first-party-dependencies/pom.xml`, we will now replace the shared-dependencies version in google-cloud-java with the SNAPSHOT.
=> chore: update graalvm downstream presubmit after java-core and share-dependencies migration

java-core/.repo-metadata.json
Fixes https://github.com/googleapis/gapic-generator-java/issues/1542
=> chore: fix java-core/.repo-metadata.json

.github/workflows/ci.yaml, .github/workflows/downstream-native-image.yaml, .github/workflows/sonar.yaml, renovate.json, showcase/README.md, showcase/gapic-showcase/pom.xml
Update the latest version to include this fix: https://github.com/googleapis/gapic-showcase/pull/1282
=> chore: Update showcase to latest version

scripts/create_native_image_test_env.sh
=> chore: fix syntax in native image submodule script

README.md, gapic-generator-java-pom-parent/pom.xml, gapic-generator-java/DEVELOPMENT.md, gapic-generator-java/pom.xml, gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/grpc/ServiceClientTestClassComposer.java, gapic-generator-java/src/test/java/com/google/api/generator/gapic/protoparser/HttpRuleParserTest.java, gapic-generator-java/src/test/proto/http_rule_parser_testing.proto, java-common-protos/proto-google-common-protos/src/main/java/com/google/api/MethodSettings.java, java-common-protos/proto-google-common-protos/src/main/proto/google/api/client.proto, java-core/.repo-metadata.json
Rename repo name to `skd-platform-java`.
=> chore: rename repo to `sdk-platform-java`

gapic-generator-java-pom-parent/pom.xml, gax-java/dependencies.properties
=> build(deps): Bump grpc-java version to 1.55.3

java-shared-dependencies/third-party-dependencies/pom.xml
=> chore: Add j2obc-annotations to shared-dependencies

renovate.json
The dependency soft freeze period ended.
=> chore: enable renovate bot

gapic-generator-java/DEVELOPMENT.md
Minor adjustment to DEVELOPMENT.md to reflect the repo name change to sdk-platform-java
=> chore: update DEVELOPMENT.md for sdk-platform-java rename

gapic-generator-java-pom-parent/pom.xml, gax-java/dependencies.properties
=> build(deps): Bump grpc version to 1.56.1

gapic-generator-java-pom-parent/pom.xml, gax-java/gax-bom/pom.xml, java-shared-dependencies/first-party-dependencies/pom.xml, java-shared-dependencies/third-party-dependencies/pom.xml, java-shared-dependencies/upper-bound-check/pom.xml
=> build(deps): Bump java-shared-configs version to 1.5.7

.github/workflows/ci.yaml, .github/workflows/shared_dependencies.yaml, .github/workflows/sonar.yaml
Configures CI for 2.22.x branch
=> ci: configure the 2.22.x protected branch

gax-java/pom.xml
=> chore: gax-java now uses third-party-dependencies' management

gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpJsonDirectServerStreamingCallableTest.java
=> chore: Resolve flaky HttpJsonDirectServerStreamingCallableTest test

.github/workflows/verify_library_generation.yaml, library_generation/test/generate_library_unit_tests.sh
=> chore: add a lint for shell script

.github/workflows/verify_library_generation.yaml, library_generation/test/generate_library_integration_test.sh, library_generation/test/resources/proto_path_list.txt, library_generation/utilities.sh
In this PR:
- Change `generate_library_integration_test.sh` to test on multiple libraries in `googleapis-gen`. The libraries are chosen from [here](https://github.com/googleapis/sdk-platform-java/tree/main/test/integration/goldens).
=> chore: Change `generate_library_integration_test.sh `to test on multiple libraries in `googleapis-gen`

library_generation/test/resources/gapic_options/example_gapic.legacy.yaml, library_generation/test/resources/gapic_options/example_gapic_legacy.yaml, library_generation/utilities.sh
=> feat: filter out `*gapic.legacy.yaml` when parsing `java_gapic_opts`

.github/workflows/ci.yaml, .github/workflows/downstream.yaml
Fixes https://github.com/googleapis/sdk-platform-java/issues/1942
=> ci: move downstream check to independent yaml file

library_generation/utilities.sh
In this PR:
- download the parent pom to output folder
=> chore: download the parent pom to output folder

showcase/README.md, test/integration/goldens/README.md
In this PR:
- Modify instructions on how to update goldens in showcase and integration tests.
=> chore: modify instructions on how to update goldens

.github/release-please.yml
=> chore: update release-please configs to include cloudbuild yaml files

.github/workflows/create_additional_release_tag.yaml
=> ci: fix typo in additional tag job

java-shared-dependencies/unmanaged-dependency-check/src/test/resources/local-install.sh
=> ci: suppress download progress in unmanaged dependency check

java-shared-dependencies/third-party-dependencies/pom.xml
Apache Arrow dependencies for java-bigquery
Flogger dependencies for java-pubsublite
=> deps: adding the dependencies for java-pubsublite and java-bigquery

.cloudbuild/graalvm/cloudbuild-test-a.yaml, .cloudbuild/graalvm/cloudbuild-test-b.yaml, .cloudbuild/graalvm/cloudbuild.yaml, gapic-generator-java-pom-parent/pom.xml, gax-java/gax-bom/pom.xml, java-shared-dependencies/first-party-dependencies/pom.xml, java-shared-dependencies/third-party-dependencies/pom.xml, java-shared-dependencies/upper-bound-check/pom.xml, sdk-platform-java-config/pom.xml, showcase/pom.xml
=> build(deps): update dependency com.google.cloud:google-cloud-shared-config to v1.7.4

rules_java_gapic/resources/gradle/client_grpc.gradle.tmpl, rules_java_gapic/resources/gradle/client_grpcrest.gradle.tmpl, rules_java_gapic/resources/gradle/client_rest.gradle.tmpl
Fixes https://github.com/googleapis/sdk-platform-java/issues/1367
=> feat: Add JavadocJar Task to build.gradle for self service libraries

library_generation/owlbot/templates/java_library/renovate.json
In this PR:
- Sync https://github.com/googleapis/synthtool/pull/1921
- Sync https://github.com/googleapis/synthtool/pull/1922
- Sync https://github.com/googleapis/synthtool/pull/1941
=> chore: sync renovate template from synthtool

library_generation/owlbot/templates/java_library/renovate.json
Port template change in https://github.com/googleapis/synthtool/pull/1945
=> chore: update renovate to explicitly ignore workflow files

library_generation/README.md, library_generation/cli/entry_point.py, library_generation/test/cli/entry_point_unit_tests.py, library_generation/test/integration_tests.py, library_generation/test/utils/generation_config_comparator_unit_tests.py
In this PR:
- Change input parameter's name in `entry_point.py`.
=> chore: change variable name

.github/workflows/ci.yaml, java-shared-dependencies/dependency-analyzer/pom.xml, java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/DependencyAnalyzer.java, java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/external/DepsDevClient.java, java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/Advisory.java, java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/AdvisoryKey.java, java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/AnalysisResult.java, java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/DependencyResponse.java, java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/Node.java, java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/PackageInfo.java, java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/QueryResult.java, java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/Result.java, java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/Version.java, java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/VersionKey.java, java-shared-dependencies/dependency-analyzer/src/test/java/com/google/cloud/external/DepsDevClientTest.java, java-shared-dependencies/dependency-analyzer/src/test/java/com/google/cloud/model/AnalysisResultTest.java, java-shared-dependencies/dependency-analyzer/src/test/java/com/google/cloud/model/VersionKeyTest.java
In this PR:
- Convert POJO to record.
=> chore: use record in dependency analyzer

java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/DependencyAnalyzer.java, java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/Advisory.java, java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/AnalysisResult.java, java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/License.java, java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/PackageInfo.java, java-shared-dependencies/dependency-analyzer/src/test/java/com/google/cloud/model/AnalysisResultTest.java, java-shared-dependencies/dependency-analyzer/src/test/java/com/google/cloud/model/LicenseTest.java
In this PR:
- Show the package information report regardless of the analysis result.
- Change report format (verified in unit tests).
=> chore: change report logic

library_generation/test/integration_tests.py
In this PR:
- Remove test output directory.
=> chore: remove test output

library_generation/templates/root-pom.xml.j2, library_generation/test/resources/test_monorepo_postprocessing/pom-golden.xml
The updated version has passed CI in https://github.com/googleapis/google-cloud-java/pull/10931
=> chore: update plugin version in template

gax-java/gax/pom.xml
Fixes https://github.com/googleapis/sdk-platform-java/issues/2966
=> chore: Use argLine maven property

showcase/gapic-showcase/pom.xml
Fixes: https://github.com/googleapis/sdk-platform-java/issues/2695
=> deps: Use Gapic-Showcase v0.35.1

.github/ISSUE_TEMPLATE/config.yml
config.yml mirrors https://github.com/googleapis/google-cloud-java/blob/main/.github/ISSUE_TEMPLATE/config.yml
=> docs: add support option to 'new issue' choices

DEVELOPMENT.md
Clarify testing guide in DEVELOPMENT.md for code changes in `parser` module.
=> chore: Clarify testing guide in DEVELOPMENT.md

library_generation/owlbot/templates/java_library/renovate.json
Result of `npx --yes --package renovate -- renovate-config-validator` from https://docs.renovatebot.com/troubleshooting/#validating-configuration-changes
=> chore: Re-run renovate-config-validator

gapic-generator-java/DEVELOPMENT.md
due to changes in googleapis/WORKSPACE [here](https://github.com/googleapis/googleapis/commit/cf16946acfefb6f5a33122802ebbaebf5bb45645), adjust to dev guide.
=> docs: Update DEVELOPMENT.md

.github/workflows/verify_library_generation.yaml, library_generation/README.md
Fix: #2733 
The checks change to
=> chore: remove mac unit tests in library generation ci

.cloudbuild/library_generation/library_generation.Dockerfile, library_generation/DEVELOPMENT.md, library_generation/README.md, library_generation/owlbot/bin/entrypoint.sh, library_generation/owlbot/bin/format_source.sh, library_generation/test/generate_library_unit_tests.sh, library_generation/test/utilities_unit_tests.py, library_generation/utils/utilities.sh, showcase/scripts/generate_showcase.sh
In this PR:
- Bake Java formatter into image.
---------
Thank you for opening a Pull Request! Before submitting your PR, please read our [contributing guidelines](https://github.com/googleapis/gapic-generator-java/blob/main/CONTRIBUTING.md). 
There are a few things you can do to make sure it goes smoothly:
=> chore: bake Java formatter into image (#3271)

.github/scripts/hermetic_library_generation.sh, library_generation/test/integration_tests.py
In this PR:
- Add `--quiet` option to `docker run` to suppress pulling progress, according to [docker run doc](https://docs.docker.com/reference/cli/docker/container/run/)
=> chore: suppress pull progress

.cloudbuild/library_generation/cloudbuild-library-generation-push-prod.yaml, release-please-config.json
In this PR:
- Setup release please to update version in `.cloudbuild/library_generation/cloudbuild-library-generation-push-prod.yaml`
=> chore: update current version in trigger

.github/workflows/nightly.yaml
Fix https://github.com/actions/runner-images/issues/10721
Example run: https://github.com/googleapis/sdk-platform-java/actions/runs/12240872490/job/34144705458
=> chore: update nightly runner

gapic-generator-java/DEVELOPMENT.md
removed line from [WORKSPACE](https://github.com/googleapis/googleapis/blob/d383e2fe6661b29ea0def03c3900080ba953dd26/WORKSPACE#L292-L304) a while ago.
=> chore: Update DEVELOPMENT.md according to WORKSPACE

showcase/README.md
In this PR:
- Update link in showcase readme.
=> docs: update showcase readme

hermetic_build/library_generation/owlbot/templates/java_library/.github/scripts/update_generation_config.sh
In this PR:
- Sync workflow template from https://github.com/googleapis/java-bigquerystorage/pull/2913
=> chore: update workflow template

hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-native-a.cfg, hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-native-b.cfg, hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-native-c.cfg, release-please-config.json
Confirmed it works in https://github.com/diegomarquezp/sdk-platform-java/pull/1/files#diff-6ddf80c6d7503f011989a3f1751695ca008a916e8ffd32a33b36f3419e78f153
=> fix: inline version update in kokoro templates

java-iam/grpc-google-iam-v3/pom.xml, java-iam/pom.xml, java-iam/proto-google-iam-v3/pom.xml
GroupId value should be: `com.google.api.grpc`
=> fix: Update IAM v3 groupId to the correct value

java-showcase/owlbot.py
=> chore: remove print from java-showcase owlbot.py

.github/release-please.yml, .github/sync-repo-settings.yaml
=> chore: create LTS branch 2.59.x

.github/workflows/gemini-issue-automated-triage.yml, .github/workflows/gemini-issue-scheduled-triage.yml
Error:
```
Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/sdk-platform-java/sdk-platform-java'. Did you forget to run actions/checkout before running your local action?
```
From https://github.com/googleapis/sdk-platform-java/actions/runs/16917097354/job/47933669808
=> ci: Fix gemini cli issues triage 

dependencies.txt
Update the upper bound dependencies file to have the latest versions per release notes instruction. It is a combination of checking the [Dependency Dashboard](https://github.com/googleapis/sdk-platform-java/issues/831) and manually checking the github repo(e.g. grpc, protobuf, ) if they don't show up in the dashboard.
=> chore: Update the upper bound dependencies file

hermetic_build/library_generation/owlbot/templates/java_library/.github/workflows/ci.yaml
Thank you for opening a Pull Request! Before submitting your PR, please read our [contributing guidelines](https://github.com/googleapis/gapic-generator-java/blob/main/CONTRIBUTING.md). 
There are a few things you can do to make sure it goes smoothly:
=> ci: update ci template to JDK 25
