googleapis/sdk-platform-java

DEVELOPMENT.md
Putting development workflow and notes in a separate doc so it doesn't show up in the default README view.
=> [ggj][docs] Add development workflow docs

src/main/java/com/google/api/generator/engine/ast/AstNodeVisitor.java, src/main/java/com/google/api/generator/engine/ast/IdentifierNode.java, src/main/java/com/google/api/generator/engine/ast/ReferenceTypeNode.java, src/main/java/com/google/api/generator/engine/ast/TypeNode.java, src/main/java/com/google/api/generator/engine/ast/Variable.java, src/main/java/com/google/api/generator/engine/writer/JavaWriterVisitor.java, src/test/java/com/google/api/generator/engine/ast/BUILD.bazel, src/test/java/com/google/api/generator/engine/ast/IdentifierNodeTest.java, src/test/java/com/google/api/generator/engine/writer/JavaWriterVisitorTest.java
Java classes should typically adhere to the <Type><SuperType> naming convention. For example, devs will be able to quickly tell that TypeNode inherits from AstNode and Variable does not. The monolith generator seemed to use this naming convention as well.
=> [ggj] fix!: rename classes to make inheritance more obvious

src/main/java/com/google/api/generator/engine/ast/AssignmentExpr.java, src/test/java/com/google/api/generator/engine/ast/AssignmentExprTest.java
This will allow us to have assignment statements such as:
```java
Map<String, Integer> aMap = methodThatReturnsAHashMap();
```
=> [ggj] fix: enable super/sub type assignments

src/main/java/com/google/api/generator/engine/ast/ConcreteReference.java, src/main/java/com/google/api/generator/engine/ast/Reference.java, src/main/java/com/google/api/generator/engine/ast/VaporReference.java, src/test/java/com/google/api/generator/engine/ast/BUILD.bazel, src/test/java/com/google/api/generator/engine/ast/ReferenceTest.java, src/test/java/com/google/api/generator/engine/ast/VaporReferenceTest.java, src/test/java/com/google/api/generator/engine/writer/ImportWriterVisitorTest.java
Provides a way to use `Reference` for types that don't exist at runtime.
=> [ggj] feat: add VaporReference

src/main/java/com/google/api/generator/engine/ast/ConcreteReference.java, src/main/java/com/google/api/generator/engine/ast/Reference.java, src/main/java/com/google/api/generator/engine/ast/VaporReference.java, src/main/java/com/google/api/generator/engine/writer/ImportWriterVisitor.java, src/main/java/com/google/api/generator/engine/writer/JavaWriterVisitor.java, src/test/java/com/google/api/generator/engine/ast/ConcreteReferenceTest.java, src/test/java/com/google/api/generator/engine/ast/VaporReferenceTest.java, src/test/java/com/google/api/generator/engine/writer/ImportWriterVisitorTest.java, src/test/java/com/google/api/generator/engine/writer/JavaWriterVisitorTest.java
This will allow us to distinguish between static imports or nested references. 
- Static import case: `import java.util.Map.Entry` and references will use only `Entry`.
- Non-static: `import java.util.Map` and references will use `Map.Entry`.
=> feat: add static import toggling

src/main/java/com/google/api/generator/engine/ast/ClassDefinition.java, src/test/java/com/google/api/generator/engine/ast/ClassDefinitionTest.java
A class cannot extends NullType because it is an interface.
But a class can implements an NullType, so I put two cases in `classdefinitiontest`
Here is an example to implement NullType, where it is imported from `javax.lang.model.type.NullType`
```
class Summer implements NullType {
@Override
public TypeKind getKind() {
return null;
}
@Override
public <R, P> R accept(TypeVisitor<R, P> v, P p) {
return null;
}
@Override
public List<? extends AnnotationMirror> getAnnotationMirrors() {
return null;
}
@Override
public <A extends Annotation> A getAnnotation(Class<A> annotationType) {
return null;
}
@Override
public <A extends Annotation> A[] getAnnotationsByType(Class<A> annotationType) {
return null;
}
}
```
=> build: integrate null type in Class Definition

src/main/java/com/google/api/generator/engine/ast/ThisObjectValue.java, src/main/java/com/google/api/generator/engine/ast/TypeNode.java, src/test/java/com/google/api/generator/engine/ast/BUILD.bazel, src/test/java/com/google/api/generator/engine/ast/ThisObjectValueTest.java, src/test/java/com/google/api/generator/engine/writer/JavaWriterVisitorTest.java
fullfill `ThisObjectValue`
- Refer instance variable
- Invoke class’s method with or without arguments
- Return the referenced class
=> feat: add ThisObjectValue

repositories.bzl
The original one (copied from `gapic-generator`) is from 2019 and does not have modern annotations.
=> [ggj[ Update googleapis commit hash to latest

.githooks/pre-commit
The build may fail due to bad formatting but shows up as a "failed build" message. Moving the formatting check makes the resulting error more clear.
=> [ggj] fix: check Java format first in pre-commit hook

src/main/java/com/google/api/generator/gapic/BUILD.bazel, src/test/java/com/google/api/generator/gapic/BUILD.bazel, src/test/java/com/google/api/generator/gapic/composer/BUILD.bazel
1. include composer files in bazel format rules.
2. add `ServiceSettingsClassComposerTest` to bazel rules.
=> [ggj]fix: include composer files in bazel format rules

src/main/java/com/google/api/generator/engine/ast/OperationExpr.java, src/main/java/com/google/api/generator/engine/ast/OperatorKind.java, src/main/java/com/google/api/generator/engine/writer/JavaWriterVisitor.java
Prepare common interface operation expr for
- Arithmetic Operation Expr
- Unary Operation Expr
- Relational Operation Expr
- Logical Operation Expr
=> [javanaut]feat: Add operation expr interface and operator kind enum

src/main/java/com/google/api/generator/engine/ast/AstNodeVisitor.java, src/main/java/com/google/api/generator/engine/ast/LogicalOperationExpr.java, src/main/java/com/google/api/generator/engine/ast/OperatorKind.java, src/main/java/com/google/api/generator/engine/writer/ImportWriterVisitor.java, src/main/java/com/google/api/generator/engine/writer/JavaWriterVisitor.java, src/test/java/com/google/api/generator/engine/ast/BUILD.bazel, src/test/java/com/google/api/generator/engine/ast/LogicalOperationExprTest.java, src/test/java/com/google/api/generator/engine/writer/ImportWriterVisitorTest.java, src/test/java/com/google/api/generator/engine/writer/JavaWriterVisitorTest.java
enables logical operators (&&) and (||)
=> [javanaut]feat: Add Logical operation expr and unit test

WORKSPACE, repositories.bzl, repository_rules.bzl, rules_java_gapic/java_gapic.bzl
Enables integration with the googleapis repo [here](https://github.com/googleapis/googleapis/pull/620).
=> [ggj][bazel] fix: new repo bazel name

.github/sync-repo-settings.yaml
Otherwise, anyone with write access can update these settings.
=> fix: restrict repo settings changes to admins

BUILD.bazel, rules_bazel/java/java_diff_test.bzl, src/test/java/com/google/api/generator/engine/BUILD.bazel, src/test/java/com/google/api/generator/gapic/composer/BUILD.bazel, src/test/java/com/google/api/generator/gapic/dummy/BUILD.bazel, src/test/java/com/google/api/generator/test/framework/BUILD.bazel
Fixes the following issues:
- `bazel run testTarget_update` did not work when starting from a clean cache. This refactoring ensures that all the dependent targets are built when the former is run.
- Removes all the Bazel direct-import warnings.
- Separates per-test targets from the test runner binary, so that we don't need to glob all sources and all goldens into a single `java_binary` target.
- Fixes file-update errors for tests that use multiple goldens.
=> [ggj][bazel][goldens] fix: refactor and fix bazel golden_update rules

src/main/java/com/google/api/generator/engine/ast/AssignmentExpr.java, src/test/java/com/google/api/generator/engine/ast/AssignmentExprTest.java
Cannot assign a value to final variable.
=> feat: add final keyword check on assignment expr

src/main/java/com/google/api/generator/engine/ast/UnaryOperationExpr.java, src/test/java/com/google/api/generator/engine/ast/UnaryOperationExprTest.java
1. Add precondition check; Should not increment on a final variable.
2. Fix unit test naming.
Next TODO: variable should not be declare here.
=> feat: add final keyword checking in post increment operation expr

src/main/java/com/google/api/generator/gapic/composer/ServiceClientClassComposer.java, src/test/java/com/google/api/generator/gapic/composer/BUILD.bazel, src/test/java/com/google/api/generator/gapic/composer/ServiceClientClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/goldens/IdentityClient.golden, src/test/java/com/google/api/generator/gapic/testdata/BUILD.bazel, src/test/java/com/google/api/generator/gapic/testdata/identity.proto
This will help with the upcoming support for nested fields in `method_signature`.
=> [ggj][codegen] fix: refactor requestBuilder into separate method in ServiceClient

src/main/java/com/google/api/generator/gapic/protoparser/Parser.java
Supports RPCs that use packages like `google.cloud.apiname.v999.TypeName` in LRO `response_type` and `metadata_type` annotations.
=> [ggj][codegen] fix: support LRO package.name annotations

.circleci/config.yml
Testing test targets should be sufficient, and will avoid building the golden update targets. This will hopefully speed up the build.
=> [ggj][engx] build: speed up CircleCI by removing build-everything job

test/integration/goldens/asset/AssetServiceClientTest.java, test/integration/goldens/asset/AssetServiceStubSettings.java, test/integration/goldens/asset/GrpcAssetServiceStub.java
Running bazel test against Asset API shows the code generation has some updates since last goldens addition. Update the goldens files for upcoming bazel rules for Asset API integration test.
=> [ggj]fix: update asset goldens for integration test

DEVELOPMENT.md
Find more details in design doc: go/java-micro-integration-test-infra
=> [ggj][infra][5/5]doc: update development.md for running integration test

src/main/java/com/google/api/generator/engine/ast/AstNodeVisitor.java, src/main/java/com/google/api/generator/engine/ast/BreakStatement.java, src/main/java/com/google/api/generator/engine/writer/ImportWriterVisitor.java, src/main/java/com/google/api/generator/engine/writer/JavaWriterVisitor.java, src/test/java/com/google/api/generator/engine/writer/JavaWriterVisitorTest.java
To support write break statement:
Use case in composing sample code like:
```
* try (EchoClient echoClient = EchoClient.create()) {
*   PagedExpandRequest request = PagedExpandRequest.newBuilder().build();
*   while (true) {
*     PagedExpandResponse response = EchoClient.pagedExpandCallable().call(request);
*     for (PagedExpandResponse element : response.getResponsesList()) {
*       // doThingsWith(element);
*     }
*     String nextPageToken = response.getNextPageToken();
*     if (!String.isNullOrEmpty(nextPageToken)) {
*       request = PagedExpandRequest.toBuilder().setPageToken(nextPageToken).build();
*     } else {
*       break;
*     }
*   }
* }
```
=> [engine][ast]Implement Break Statement

src/main/java/com/google/api/generator/gapic/composer/samplecode/BUILD.bazel, src/main/java/com/google/api/generator/gapic/composer/samplecode/SampleCodeWriter.java, src/test/java/com/google/api/generator/gapic/composer/samplecode/BUILD.bazel, src/test/java/com/google/api/generator/gapic/composer/samplecode/SampleCodeWriterTest.java
Add a helper function to writeSampleCode where it has been frequently used in #487 #493 #498 and future changes.
=> [composer][samplecode]Add writeSampleCode method

src/main/java/com/google/api/generator/gapic/composer/ServiceClientSampleCodeComposer.java, src/test/java/com/google/api/generator/gapic/composer/goldens/EchoClient.golden, src/test/java/com/google/api/generator/gapic/composer/goldens/IdentityClient.golden, test/integration/goldens/asset/AssetServiceClient.java, test/integration/goldens/logging/ConfigServiceV2Client.java, test/integration/goldens/logging/LoggingServiceV2Client.java, test/integration/goldens/logging/MetricsServiceV2Client.java, test/integration/goldens/redis/CloudRedisClient.java
Use Variable Expr instead of String value for myCredentials and myEndpoint.
=> [samplecode][bug]fix credentials and endpoint sample code variable

rules_java_gapic/java_gapic.bzl
This is needed for APIs that use commonly-used proto rules, which we also use as default dependencies. Since skylark does not have Python `set`s and dependency detection is quite involved, we use this workaround instead.
=> [ggj][bazel] fix: append Bazel input deps without dupes

src/main/java/com/google/api/generator/gapic/composer/ServiceClientSampleCodeComposer.java
As we discuss in #573, no need wrapper `createVariableExpr`. Flatten the existing `createVariableExpr` and prepare for merge `MethodSampleCodeHelperComposer` merge into `ServiceClientSampleCodeComposer`.
=> [samplecode][Prepare][2/2]Flattern the createVariableExpr wrapper 

rules_java_gapic/java_gapic.bzl, src/main/java/com/google/api/generator/gapic/composer/ServiceClientCommentComposer.java, src/main/java/com/google/api/generator/gapic/protoparser/HttpRuleParser.java, src/test/java/com/google/api/generator/gapic/composer/goldens/EchoClient.golden, src/test/java/com/google/api/generator/gapic/composer/goldens/GrpcTestingStub.golden, src/test/java/com/google/api/generator/gapic/composer/goldens/IdentityClient.golden, src/test/java/com/google/api/generator/gapic/composer/goldens/TestingClientTest.golden, src/test/java/com/google/api/generator/gapic/protoparser/HttpRuleParserTest.java, src/test/java/com/google/api/generator/gapic/testdata/testing.proto, test/integration/goldens/asset/AssetServiceClient.java, test/integration/goldens/library/LibraryServiceClient.java, test/integration/goldens/logging/ConfigClient.java, test/integration/goldens/logging/LoggingClient.java, test/integration/goldens/logging/MetricsClient.java, test/integration/goldens/redis/CloudRedisClient.java
Handles the case where different bindings may be used in the `additional_bindings` field of the HTTP proto annotation.
=> [ggj][codgen] fix: add HTTP's additional_bindings to GrpcServiceStub call settings

rules_java_gapic/java_gapic.bzl, src/main/java/com/google/api/generator/gapic/protoparser/MethodSignatureParser.java, src/main/java/com/google/api/generator/gapic/protoparser/Parser.java, src/main/java/com/google/api/generator/gapic/protoparser/ResourceParserHelpers.java, test/integration/goldens/logging/ConfigClientTest.java
Required for backwards-compatibility with the monolith. Affects a few selected repos like java-bigquerystorage and java-cloudbuild.
=> feat: generate resname classes for all refs, message res defs

src/main/java/com/google/api/generator/gapic/composer/ServiceClientClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/ServiceClientCommentComposer.java, src/main/java/com/google/api/generator/gapic/composer/ServiceClientSampleCodeComposer.java, src/test/java/com/google/api/generator/gapic/composer/ServiceClientSampleCodeComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/goldens/EchoClient.golden, src/test/java/com/google/api/generator/gapic/composer/goldens/IdentityClient.golden, test/integration/goldens/asset/AssetServiceClient.java, test/integration/goldens/library/LibraryServiceClient.java, test/integration/goldens/logging/ConfigClient.java, test/integration/goldens/logging/LoggingClient.java, test/integration/goldens/logging/MetricsClient.java, test/integration/goldens/redis/CloudRedisClient.java
RPC default method has 3 types sample code for:
1. paged (gapic-generator [sample code](https://github.com/googleapis/java-redis/blob/master/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/CloudRedisClient.java#L1202-L1212))
```
* try (LibraryServiceClient libraryServiceClient = LibraryServiceClient.create()) {
*   ListShelvesRequest request =
*       ListShelvesRequest.newBuilder()
*           .setPageSize(883849137)
*           .setPageToken("pageToken873572522")
*           .build();
*   for (Shelf element : libraryServiceClient.listShelves(request).iterateAll()) {
*     // doThingsWith(element);
*   }
* }
```
2. lro (gapic-generator [sample code](https://github.com/googleapis/java-redis/blob/master/google-cloud-redis/src/main/java/com/google/cloud/redis/v1/CloudRedisClient.j …
=> [samplecode] Implement rpc default method sample code

rules_java_gapic/java_gapic.bzl
We've migrated Ads off this file, so we no longer need to support it.
=> [ggj][engx] fix: remove service_yaml parsing from Bazel rules

src/main/java/com/google/api/generator/gapic/composer/ServiceClientClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/ServiceClientCommentComposer.java, src/main/java/com/google/api/generator/gapic/composer/ServiceClientSampleCodeComposer.java, src/test/java/com/google/api/generator/gapic/composer/ServiceClientSampleCodeComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/goldens/EchoClient.golden, test/integration/goldens/asset/AssetServiceClient.java, test/integration/goldens/redis/CloudRedisClient.java
Inside of try body, 
1. construct request with default values.
2. Assign future variable with invoking LRO callable method.
3. Assign response variable with invoking `future.get` method.
```
* try (CloudRedisClient cloudRedisClient = CloudRedisClient.create()) {
*   LocationName parent = LocationName.of("[PROJECT]", "[LOCATION]");
*   String instanceId = "test_instance";
*   Instance.Tier tier = Instance.Tier.BASIC;
*   int memorySizeGb = 1;
*   Instance instance = Instance.newBuilder()
*     .setTier(tier)
*     .setMemorySizeGb(memorySizeGb)
*     .build();
*   CreateInstanceRequest request = CreateInstanceRequest.newBuilder()
*     .setParent(parent.toString())
*     .setInstanceId(instanceId)
*     .setInstance(instance)
*     .build();
*   OperationFuture&lt;Instance, …
```
=> [1/3]Implemente LRO Operation Callable Method sample code

src/main/java/com/google/api/generator/gapic/composer/BUILD.bazel, src/main/java/com/google/api/generator/gapic/composer/Composer.java, src/main/java/com/google/api/generator/gapic/composer/ServiceClientTestClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/defaultvalue/BUILD.bazel, src/main/java/com/google/api/generator/gapic/composer/defaultvalue/DefaultValueComposer.java, src/main/java/com/google/api/generator/gapic/composer/resourcename/BUILD.bazel, src/main/java/com/google/api/generator/gapic/composer/resourcename/ResourceNameHelperClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/resourcename/ResourceNameTokenizer.java, src/test/java/com/google/api/generator/engine/writer/BUILD.bazel, src/test/java/com/google/api/generator/gapic/composer/BUILD.bazel, src/test/java/com/google/api/generator/gapic/composer/BatchingDescriptorComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/ComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/GrpcServiceCallableFactoryClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/GrpcServiceStubClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/MockServiceClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/MockServiceImplClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/RetrySettingsComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/ServiceClientClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/ServiceClientTestClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/ServiceSettingsClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/ServiceStubClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/ServiceStubSettingsClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/constants/BUILD.bazel, src/test/java/com/google/api/generator/gapic/composer/constants/ComposerConstants.java, src/test/java/com/google/api/generator/gapic/composer/defaultvalue/BUILD.bazel, src/test/java/com/google/api/generator/gapic/composer/defaultvalue/DefaultValueComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/resourcename/BUILD.bazel, src/test/java/com/google/api/generator/gapic/composer/resourcename/ResourceNameHelperClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/resourcename/ResourceNameTokenizerTest.java
After change on #616, sample code generate depend on default value composer, it causes bazel error of a cycle in bazel dependency graph.
In this PR,  I create `defaultvalue` bazel package, `resourcename` bazel package and `constants` bazel package. Also do the same for their matched tests.
dependency graph:
defaultvalue -> resourcename -> constants
=> [composer][engx] seperate default value related files and same to resource name

src/main/java/com/google/api/generator/gapic/composer/ServiceClientClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientSampleCodeComposer.java, src/test/java/com/google/api/generator/gapic/composer/goldens/EchoClient.golden, src/test/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientSampleCodeComposerTest.java, test/integration/goldens/asset/AssetServiceClient.java, test/integration/goldens/redis/CloudRedisClient.java
```
* Sample code:
*
* <pre>
* <code>
* try (EchoClient echoClient = EchoClient.create()) {
*   WaitRequest request = WaitRequest.newBuilder().build();
*   ApiFuture&lt;Operation&gt; future = echoClient.waitCallable().futureCall(request);
*   // Do something
*   Operation response = future.get();
* }
* </code>
* </pre>
*/
public final UnaryCallable<WaitRequest, Operation> waitCallable() {
return stub.waitCallable();
}
```
=> [samplecode][2/3]Implement regular lro callable sample code

src/main/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientSampleCodeComposer.java, src/test/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientSampleCodeComposerTest.java
TODO: rebase #641 to get rid of `CloudRedisClient.java` change.
=> [samplecode]Add unit test for class header sample code

src/main/java/com/google/api/generator/gapic/composer/ServiceClientClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/comment/ServiceClientCommentComposer.java, src/main/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientSampleCodeComposer.java, src/test/java/com/google/api/generator/gapic/composer/goldens/EchoClient.golden, src/test/java/com/google/api/generator/gapic/composer/goldens/IdentityClient.golden, src/test/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientSampleCodeComposerTest.java, test/integration/goldens/asset/AssetServiceClient.java, test/integration/goldens/credentials/IamCredentialsClient.java, test/integration/goldens/library/LibraryServiceClient.java, test/integration/goldens/logging/ConfigClient.java, test/integration/goldens/logging/LoggingClient.java, test/integration/goldens/logging/MetricsClient.java, test/integration/goldens/redis/CloudRedisClient.java
Use the first pure unary RPC method's sample code as showcase, if no such method exists, use the first method in the service's methods list. And if the method has no method signature, we use `DefaultMethodHeaderSampleCode`
=> [samplecode]Implement class header method sample code

src/main/java/com/google/api/generator/gapic/model/Message.java, src/main/java/com/google/api/generator/gapic/protoparser/Parser.java, src/main/java/com/google/api/generator/gapic/protoparser/TypeParser.java, src/test/java/com/google/api/generator/gapic/composer/defaultvalue/DefaultValueComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/goldens/EchoClient.golden, src/test/java/com/google/api/generator/gapic/composer/goldens/EchoClientTest.golden, src/test/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientSampleCodeComposerTest.java, test/integration/goldens/asset/AssetServiceClient.java, test/integration/goldens/asset/AssetServiceClientTest.java, test/integration/goldens/asset/package-info.java, test/integration/goldens/logging/ConfigClientTest.java
This is currently exercised when an RPC uses an enum type in `method_signature`.
=> fix: add support for top-level protobuf enums

.github/workflows/ci.yaml, README.md, codecov.yml
- Add codecov config file
- Add codecov github action
- Add codecov badge showing on readMe
=> [ggj] Add overall test coverage

.github/workflows/ci.yaml, src/test/java/com/google/api/generator/gapic/composer/BUILD.bazel
This ensures it runs once, since the tests run twice (once for Java 8, another for 11).
=> chore(ci): Separate codecov to optimize presubmit check speed [ggj][engx][build]

src/main/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientSampleCodeComposer.java, src/test/java/com/google/api/generator/gapic/composer/goldens/EchoClient.golden, src/test/java/com/google/api/generator/gapic/composer/goldens/IdentityClient.golden, src/test/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientSampleCodeComposerTest.java, test/integration/goldens/asset/AssetServiceClient.java, test/integration/goldens/kms/KeyManagementServiceClient.java, test/integration/goldens/library/LibraryServiceClient.java, test/integration/goldens/logging/ConfigClient.java, test/integration/goldens/logging/LoggingClient.java, test/integration/goldens/logging/MetricsClient.java, test/integration/goldens/redis/CloudRedisClient.java
=> [samplecode]fix: add request with default value in regular paged callable method

src/main/java/com/google/api/generator/gapic/composer/BatchingDescriptorComposer.java, src/main/java/com/google/api/generator/gapic/composer/ServiceClientClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/ServiceClientTestClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/ServiceStubClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/ServiceStubSettingsClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/defaultvalue/DefaultValueComposer.java, src/main/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientSampleCodeComposer.java, src/main/java/com/google/api/generator/gapic/model/Message.java, src/main/java/com/google/api/generator/gapic/protoparser/HttpRuleParser.java, src/main/java/com/google/api/generator/gapic/protoparser/MethodSignatureParser.java, src/main/java/com/google/api/generator/gapic/protoparser/Parser.java, src/main/java/com/google/api/generator/gapic/protoparser/ResourceNameParser.java, src/test/java/com/google/api/generator/gapic/composer/defaultvalue/DefaultValueComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientSampleCodeComposerTest.java, src/test/java/com/google/api/generator/gapic/protoparser/HttpRuleParserTest.java, src/test/java/com/google/api/generator/gapic/protoparser/ParserTest.java, src/test/java/com/google/api/generator/gapic/protoparser/ResourceNameParserTest.java
Addresses the use case where a proto message `foo.bar.Car` has an internal field with the same short name, such as `bar.foo.Car`.
=> fix(types): Use fully-qualified message type names [ggj]

rules_bazel/java/integration_test.bzl, src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceClientTestClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/grpc/ServiceClientTestClassComposer.java, src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/DeprecatedServiceClientTest.golden, src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/EchoClientTest.golden, src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/LoggingClientTest.golden, src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/SubscriberClientTest.golden, src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/TestingClientTest.golden, test/integration/goldens/asset/BUILD.bazel, test/integration/goldens/asset/com/google/cloud/asset/v1/AssetServiceClientTest.java, test/integration/goldens/credentials/BUILD.bazel, test/integration/goldens/credentials/com/google/cloud/iam/credentials/v1/IAMCredentialsClientTest.java, test/integration/goldens/iam/BUILD.bazel, test/integration/goldens/iam/com/google/iam/v1/IAMPolicyClientTest.java, test/integration/goldens/kms/BUILD.bazel, test/integration/goldens/kms/com/google/cloud/kms/v1/KeyManagementServiceClientTest.java, test/integration/goldens/library/BUILD.bazel, test/integration/goldens/library/com/google/cloud/example/library/v1/LibraryServiceClientTest.java, test/integration/goldens/logging/BUILD.bazel, test/integration/goldens/logging/com/google/cloud/logging/v2/ConfigClientTest.java, test/integration/goldens/logging/com/google/cloud/logging/v2/LoggingClientTest.java, test/integration/goldens/logging/com/google/cloud/logging/v2/MetricsClientTest.java, test/integration/goldens/pubsub/BUILD.bazel, test/integration/goldens/pubsub/com/google/cloud/pubsub/v1/SchemaServiceClientTest.java, test/integration/goldens/pubsub/com/google/cloud/pubsub/v1/SubscriptionAdminClientTest.java, test/integration/goldens/pubsub/com/google/cloud/pubsub/v1/TopicAdminClientTest.java, test/integration/goldens/redis/BUILD.bazel, test/integration/goldens/redis/com/google/cloud/redis/v1beta1/CloudRedisClientTest.java
This is needed for the Bazel integration test fix in #744.
=> fix(tests): Ensure deterministic field ordering in test classes [ggj]

WORKSPACE, src/main/java/com/google/api/generator/gapic/composer/comment/SettingsCommentComposer.java, src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceStubSettingsClassComposer.java, src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/DeprecatedServiceStubSettings.golden, src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/EchoStubSettings.golden, src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/LoggingServiceV2StubSettings.golden, src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/PublisherStubSettings.golden, src/test/java/com/google/api/generator/gapic/composer/rest/goldens/ComplianceStubSettings.golden, test/integration/goldens/asset/com/google/cloud/asset/v1/stub/AssetServiceStubSettings.java, test/integration/goldens/credentials/com/google/cloud/iam/credentials/v1/stub/IamCredentialsStubSettings.java, test/integration/goldens/iam/com/google/iam/v1/stub/IAMPolicyStubSettings.java, test/integration/goldens/kms/com/google/cloud/kms/v1/stub/KeyManagementServiceStubSettings.java, test/integration/goldens/library/com/google/cloud/example/library/v1/stub/LibraryServiceStubSettings.java, test/integration/goldens/logging/com/google/cloud/logging/v2/stub/ConfigServiceV2StubSettings.java, test/integration/goldens/logging/com/google/cloud/logging/v2/stub/LoggingServiceV2StubSettings.java, test/integration/goldens/logging/com/google/cloud/logging/v2/stub/MetricsServiceV2StubSettings.java, test/integration/goldens/pubsub/com/google/cloud/pubsub/v1/stub/PublisherStubSettings.java, test/integration/goldens/pubsub/com/google/cloud/pubsub/v1/stub/SchemaServiceStubSettings.java, test/integration/goldens/pubsub/com/google/cloud/pubsub/v1/stub/SubscriberStubSettings.java, test/integration/goldens/redis/com/google/cloud/redis/v1beta1/stub/CloudRedisStubSettings.java
Googlers see go/java-gapic-client-mtls for the detailed design doc.
This PR adds mtls logic to gapic generator. It relies on the gax-java [mtls change](https://github.com/googleapis/gax-java/pull/1249). This PR requires gax-java version >= 1.65.0.
The following new code is added to StubSetting:
```
/** Returns the default mTLS service endpoint. */
public static String getDefaultMtlsEndpoint() {    return <mtls endpoint>;  }  <=== new code
private static Builder createDefault() {
Builder builder = new Builder(((ClientContext) null));
builder.setTransportChannelProvider(defaultTransportChannelProvider());
builder.setCredentialsProvider(defaultCredentialsProviderBuilder().build()); 
builder.setInternalHeaderProvider(defaultApiClientHeaderProviderBuilder().build()); …
```
=> feat: add mtls feature

src/main/java/com/google/api/generator/engine/ast/AssignmentExpr.java, src/main/java/com/google/api/generator/gapic/composer/defaultvalue/BUILD.bazel, src/main/java/com/google/api/generator/gapic/composer/defaultvalue/DefaultValueComposer.java, src/test/java/com/google/api/generator/gapic/composer/defaultvalue/DefaultValueComposerTest.java
Use an anonymous ResourceName class as a default value when only wildcard resource name types are present. This primarily affects GCS and IAM. These anonymous classes will be used only for explicit field assignments, and not when the value is being set on a message. Specifically, note that the IAM integration goldens are unchanged.
The GCS use case is covered by the default value unit test. Integration tests may be added once the GCS protos are published.
=> fix(resnames): Use anon resname classes when only wildcards are present

repositories.bzl
Otherwise, running `bazel test test/integration/compute` results in the following error:
```
ERROR: Traceback (most recent call last):
File "/usr/local/google/home/miraleung/.cache/bazel/_bazel_miraleung/81d8a0d4367fd2fc950131569ad58216/external/com_google_googleapis_discovery/google/cloud/compute/v1/BUILD.bazel", line 102, column 6, in <toplevel>
"java_gapic_assembly_gradle_pkg_legacy",
Error: file '@com_google_googleapis_imports//:imports.bzl' does not contain symbol 'java_gapic_assembly_gradle_pkg_legacy'
ERROR: /usr/local/google/home/miraleung/dev/ggj2/test/integration/BUILD.bazel:135:19: no such target '@com_google_googleapis_discovery//google/cloud/compute/v1:compute_small_java_proto': target 'compute_small_java_proto' not declared in package 'google/cloud/compute/v1' defined by …
```
=> fix(build): Update googleapis-discovery hash to fix compute integration test [ggj]

src/main/java/com/google/api/generator/engine/ast/AnnotationNode.java, src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceCallableFactoryClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/grpc/GrpcServiceCallableFactoryClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/rest/HttpJsonServiceCallableFactoryClassComposer.java, src/test/java/com/google/api/generator/gapic/composer/rest/goldens/HttpJsonComplianceCallableFactory.golden, test/integration/goldens/compute/com/google/cloud/compute/v1/stub/HttpJsonAddressesCallableFactory.java, test/integration/goldens/compute/com/google/cloud/compute/v1/stub/HttpJsonRegionOperationsCallableFactory.java
This is to make implementing LRO post-GA safer. Note, `TransportServiceFactory` class is public for technical reasons, and is not supposed to be used by users directly.
=> fix: (rest transport) Add `@BetaApi` to the generated `TransportServiceFactory` class and lro-specific method

repositories.bzl, src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/SubscriberClientTest.golden, test/integration/goldens/asset/com/google/cloud/asset/v1/AssetServiceClient.java, test/integration/goldens/asset/com/google/cloud/asset/v1/stub/AssetServiceStubSettings.java, test/integration/goldens/pubsub/com/google/cloud/pubsub/v1/SubscriptionAdminClient.java, test/integration/goldens/pubsub/com/google/cloud/pubsub/v1/SubscriptionAdminClientTest.java, test/integration/goldens/pubsub/com/google/cloud/pubsub/v1/gapic_metadata.json
Golden file updates are due to the proto updates in googleapis.
=> chore: Update googleapis hash (incl. mono removal) [ggj]

test/integration/BUILD.bazel, test/integration/goldens/storage/BUILD.bazel, test/integration/goldens/storage/com/google/storage/v2/BucketName.java, test/integration/goldens/storage/com/google/storage/v2/CryptoKeyName.java, test/integration/goldens/storage/com/google/storage/v2/MockStorage.java, test/integration/goldens/storage/com/google/storage/v2/MockStorageImpl.java, test/integration/goldens/storage/com/google/storage/v2/ProjectName.java, test/integration/goldens/storage/com/google/storage/v2/StorageClient.java, test/integration/goldens/storage/com/google/storage/v2/StorageClientTest.java, test/integration/goldens/storage/com/google/storage/v2/StorageSettings.java, test/integration/goldens/storage/com/google/storage/v2/gapic_metadata.json, test/integration/goldens/storage/com/google/storage/v2/package-info.java, test/integration/goldens/storage/com/google/storage/v2/stub/GrpcStorageCallableFactory.java, test/integration/goldens/storage/com/google/storage/v2/stub/GrpcStorageStub.java, test/integration/goldens/storage/com/google/storage/v2/stub/StorageStub.java, test/integration/goldens/storage/com/google/storage/v2/stub/StorageStubSettings.java
Storage has several generation-time edge cases (e.g. messages named `Object`, which cause a naming collision in Java). This will also be used as a baseline diff for #803.
=> chore: add baseline storage golden files [ggj]

src/main/java/com/google/api/generator/gapic/protoparser/Parser.java
Closes #819. Undoes #785 for Ads under an allowlist. With this change, the following extra unused resource names are generated for Ads' v8 on comparing the one generated with release 2.0.0 (of the microgenerator) and one generated with this fix:
```sh
$ cd /path/to/output/orig
$ diff <(find googleads-java/ -name "*Name.java" | cut -d  '/' -f2-) <(find ../fixed/googleads-java/ -name "*Name.java" | cut -d  '/' -f4-)
> proto-googleads-java/src/main/java/com/google/ads/googleads/v8/resources/InvoiceName.java
43a45
> proto-googleads-java/src/main/java/com/google/ads/googleads/v8/resources/CallViewName.java
52a55
> proto-googleads-java/src/main/java/com/google/ads/googleads/v8/resources/PaymentsAccountName.java
87a91
> proto-googleads-java/src/main/java/com/google/ads/googleads/v8/resources/Chan …
```
=> fix: bring back unused resnames for Ads [ggj]

WORKSPACE, src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceStubSettingsClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/grpc/ServiceStubSettingsClassComposer.java, src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/DeprecatedServiceStubSettings.golden, src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/EchoStubSettings.golden, src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/LoggingServiceV2StubSettings.golden, src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/PublisherStubSettings.golden, test/integration/goldens/asset/com/google/cloud/asset/v1/stub/AssetServiceStubSettings.java, test/integration/goldens/credentials/com/google/cloud/iam/credentials/v1/stub/IamCredentialsStubSettings.java, test/integration/goldens/iam/com/google/iam/v1/stub/IAMPolicyStubSettings.java, test/integration/goldens/kms/com/google/cloud/kms/v1/stub/KeyManagementServiceStubSettings.java, test/integration/goldens/library/com/google/cloud/example/library/v1/stub/LibraryServiceStubSettings.java, test/integration/goldens/logging/com/google/cloud/logging/v2/stub/ConfigServiceV2StubSettings.java, test/integration/goldens/logging/com/google/cloud/logging/v2/stub/LoggingServiceV2StubSettings.java, test/integration/goldens/logging/com/google/cloud/logging/v2/stub/MetricsServiceV2StubSettings.java, test/integration/goldens/pubsub/com/google/cloud/pubsub/v1/stub/PublisherStubSettings.java, test/integration/goldens/pubsub/com/google/cloud/pubsub/v1/stub/SchemaServiceStubSettings.java, test/integration/goldens/pubsub/com/google/cloud/pubsub/v1/stub/SubscriberStubSettings.java, test/integration/goldens/redis/com/google/cloud/redis/v1beta1/stub/CloudRedisStubSettings.java, test/integration/goldens/storage/com/google/storage/v2/stub/StorageStubSettings.java
For GAPIC clients, this PR enables self signed jwt feature by changing the implementation of `defaultCredentialsProviderBuilder`  from 
```
public static GoogleCredentialsProvider.Builder defaultCredentialsProviderBuilder() {
return GoogleCredentialsProvider.newBuilder().setScopesToApply(DEFAULT_SERVICE_SCOPES);
}
```
to
```
return GoogleCredentialsProvider.newBuilder().setScopesToApply(DEFAULT_SERVICE_SCOPES)
.setUseJwtAccessWithScope(true);
```
There is no changes for DIREGAPIC clients.
This PR relies on https://github.com/googleapis/gax-java/pull/1420.
=> feat: enable self signed jwt for gapic clients

WORKSPACE, src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceStubClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/grpc/GrpcServiceStubClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/rest/HttpJsonServiceCallableFactoryClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/rest/HttpJsonServiceStubClassComposer.java, src/test/java/com/google/api/generator/gapic/composer/rest/goldens/HttpJsonComplianceCallableFactory.golden, src/test/java/com/google/api/generator/gapic/composer/rest/goldens/HttpJsonComplianceStub.golden, test/integration/goldens/compute/com/google/cloud/compute/v1/stub/HttpJsonAddressesCallableFactory.java, test/integration/goldens/compute/com/google/cloud/compute/v1/stub/HttpJsonAddressesStub.java, test/integration/goldens/compute/com/google/cloud/compute/v1/stub/HttpJsonRegionOperationsCallableFactory.java, test/integration/goldens/compute/com/google/cloud/compute/v1/stub/HttpJsonRegionOperationsStub.java
Added methods to HttpJsonServiceCallableFactoryClassComposer and HttpJsonServiceStubClassComposer to generate LRO machinery without annotations. Used the established AST format.
Methods generated:
- getOperationSnapshotFactory
- setPollingRequestFactory
- createOperationCallable
TODO:
Add annotations
Find alternative way of representing generic types. Currently using a vapor reference with the same package as the class being generated.
=> DIREGAPIC LRO implementation without annotations

src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceCallableFactoryClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceStubClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/common/ServiceClientClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/common/ServiceStubClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/grpc/GrpcServiceCallableFactoryClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/rest/HttpJsonServiceCallableFactoryClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/rest/HttpJsonServiceStubClassComposer.java, src/main/java/com/google/api/generator/gapic/model/LongrunningOperation.java, src/main/java/com/google/api/generator/gapic/model/Method.java, src/main/java/com/google/api/generator/gapic/model/OperationResponse.java, src/main/java/com/google/api/generator/gapic/model/Service.java, src/main/java/com/google/api/generator/gapic/protoparser/Parser.java, src/test/java/com/google/api/generator/gapic/composer/rest/goldens/HttpJsonComplianceCallableFactory.golden, src/test/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientSampleCodeComposerTest.java, src/test/java/com/google/api/generator/gapic/protoparser/ParserTest.java, test/integration/goldens/compute/com/google/cloud/compute/v1/AddressesClient.java, test/integration/goldens/compute/com/google/cloud/compute/v1/AddressesClientTest.java, test/integration/goldens/compute/com/google/cloud/compute/v1/AddressesSettings.java, test/integration/goldens/compute/com/google/cloud/compute/v1/gapic_metadata.json, test/integration/goldens/compute/com/google/cloud/compute/v1/package-info.java, test/integration/goldens/compute/com/google/cloud/compute/v1/stub/AddressesStub.java, test/integration/goldens/compute/com/google/cloud/compute/v1/stub/AddressesStubSettings.java, test/integration/goldens/compute/com/google/cloud/compute/v1/stub/HttpJsonAddressesCallableFactory.java, test/integration/goldens/compute/com/google/cloud/compute/v1/stub/HttpJsonAddressesStub.java
There are 2 more things left:
1) longRunnignOperation() getter method on the transport-agnostic (parent) class
2) proper (transport-specific) Response and Metadata transformers for OperationSettings initialization
=> fix: fix diregapic-lro logic

rules_java_gapic/java_gapic.bzl, rules_java_gapic/java_gapic_pkg.bzl, rules_java_gapic/resources/gradle/client_grpcrest.gradle.tmpl, src/main/java/com/google/api/generator/gapic/BUILD.bazel, src/main/java/com/google/api/generator/gapic/composer/Composer.java, src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceCallableFactoryClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceClientClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceClientTestClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceSettingsClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceStubClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceStubSettingsClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/common/AbstractTransportServiceStubClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/common/TransportContext.java, src/main/java/com/google/api/generator/gapic/composer/grpc/GrpcContext.java, src/main/java/com/google/api/generator/gapic/composer/grpc/ServiceClientTestClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/grpcrest/BUILD.bazel, src/main/java/com/google/api/generator/gapic/composer/grpcrest/GrpcRestContext.java, src/main/java/com/google/api/generator/gapic/composer/grpcrest/HttpJsonServiceClientTestClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/grpcrest/HttpJsonServiceStubClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/grpcrest/ServiceClientClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/grpcrest/ServiceSettingsClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/grpcrest/ServiceStubClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/grpcrest/ServiceStubSettingsClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/rest/HttpJsonServiceCallableFactoryClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/rest/RestContext.java, src/main/java/com/google/api/generator/gapic/composer/rest/ServiceClientTestClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/rest/ServiceStubSettingsClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/utils/ClassNames.java, src/test/java/com/google/api/generator/gapic/BUILD.bazel
1) Fully backward compatible with grpc-only GAPIC
2) Strictly speaking not fully backward compatible with rest-only REGAPIC (but is compatible for practical cases). See below for details.
3) Introduces the concept of default transport (is necessary to preserve backward-compabitility). The default behavior assumes `grpc` transport.
4) Strictly speaking `rest` client is not backward compatible with `grpc+rest` (but is compatible for practical cases).
=> feat: REGAPIC Multitransport implementation (grpc+rest)

src/main/java/com/google/api/generator/gapic/protoparser/BatchingSettingsConfigParser.java, src/main/java/com/google/api/generator/gapic/protoparser/GapicLanguageSettingsParser.java, src/main/java/com/google/api/generator/gapic/protoparser/GapicLroRetrySettingsParser.java, src/main/java/com/google/api/generator/gapic/protoparser/ServiceYamlParser.java, src/main/java/com/google/api/generator/gapic/protowriter/Writer.java
Currently the conversion result is platform-dependent.
=> Portable String <--> bytes conversion

DEVELOPMENT.md
=> Fix development doc

src/main/java/com/google/api/generator/gapic/protoparser/Parser.java
`toSet()` makes `sorted()` irrelevant. Looking at other code locations, `toList()` is really intended.
Other changes are only minor simplifications.
=> Fix preserving sorted order of a collection

rules_java_gapic/resources/gradle/gradle/wrapper/gradle-wrapper.properties
The new 7.x verison of gradle is incompatible with the used gradle build scripts format.
=> fix: revert gradle version used for the bazel-generated assembly packages

WORKSPACE
We should be fine without upgrading this, but it's always good to keep this up-to-date.
=> Update gax-java to latest 2.7.0

rules_java_gapic/resources/gradle/client_grpc.gradle.tmpl, rules_java_gapic/resources/gradle/client_grpcrest.gradle.tmpl, rules_java_gapic/resources/gradle/proto.gradle.tmpl
After #876, turns out these dependencies are required to compile generated libraries.
The reason that these were not required previously is probably the same as https://github.com/googleapis/gax-java/issues/1534. That is, something people realize after they drop the obsolete `compile` or `runtime` "scopes."
This will resolve b/211697397, but there might be more dependencies to add (hopefully not).
=> fix: add missing dependencies in Gradle for "self-service" library generation

rules_java_gapic/resources/gradle/client_grpc.gradle.tmpl, rules_java_gapic/resources/gradle/client_grpcrest.gradle.tmpl, rules_java_gapic/resources/gradle/client_rest.gradle.tmpl, rules_java_gapic/resources/gradle/grpc.gradle.tmpl, rules_java_gapic/resources/gradle/proto.gradle.tmpl
Stopgap support for generated libraries. See #888.
Tested this with java-compute and java-retail using Java 11.
=> feat: support Java 9+ compilation of generated libraries

rules_java_gapic/resources/gradle/assembly.gradle.tmpl
=> feat: add Gradle `install` "alias" for local publication for generated libraries

rules_java_gapic/java_gapic_pkg.bzl
This is about "self-service" generated libraries.
We [changed the dependency "scope"](https://github.com/googleapis/gapic-generator-java/pull/876/files#diff-66f068746d573fb515dcebc976e0d2eabf10a609e61ff20fa07d888d88702c23R169) from the obsolete `compile` to `implementation` when we upgraded Gradle, which prevents affecting dependencies from transitively exposed to library users. We did the same to gax a while ago and a report like [this](https://github.com/googleapis/gax-java/issues/1534#issuecomment-944785857) ensued. Likewise, today I got a report where a library user cannot access auto-generated proto stub classes in their Java code.
This PR changes the scope back to what `compile` meant in old Gradle versions. The behavior after the change should be that of the old versions.
I've …
=> fix: expose extra dependencies transitively to library users

.github/workflows/ci.yaml, rules_java_gapic/resources/gradle/client_grpc.gradle.tmpl, rules_java_gapic/resources/gradle/client_grpcrest.gradle.tmpl, rules_java_gapic/resources/gradle/client_rest.gradle.tmpl
b/214271851
```
> Resolving dependency configuration 'runtimeOnly' is not allowed as it is defined as 'canBeResolved=false'.
Instead, a resolvable ('canBeResolved=true') dependency configuration that extends 'runtimeOnly' should be resolved.
```
`runtimeOnly` is not resolvable. The point of `allJars` is to get all the runtime dependencies + library itself, so `runtimeClasspath` should do it.
=> fix: fix broken Gradle allJars task on generated libs and add tests for it

PROPERTIES.bzl, repositories.bzl, src/main/java/com/google/api/generator/engine/ast/BUILD.bazel, test/integration/BUILD.bazel, test/integration/goldens/compute/com/google/cloud/compute/v1small/AddressesClient.java, test/integration/goldens/compute/com/google/cloud/compute/v1small/AddressesClientTest.java, test/integration/goldens/compute/com/google/cloud/compute/v1small/AddressesSettings.java, test/integration/goldens/compute/com/google/cloud/compute/v1small/RegionOperationsClient.java, test/integration/goldens/compute/com/google/cloud/compute/v1small/RegionOperationsClientTest.java, test/integration/goldens/compute/com/google/cloud/compute/v1small/RegionOperationsSettings.java, test/integration/goldens/compute/com/google/cloud/compute/v1small/gapic_metadata.json, test/integration/goldens/compute/com/google/cloud/compute/v1small/package-info.java, test/integration/goldens/compute/com/google/cloud/compute/v1small/stub/AddressesStub.java, test/integration/goldens/compute/com/google/cloud/compute/v1small/stub/AddressesStubSettings.java, test/integration/goldens/compute/com/google/cloud/compute/v1small/stub/HttpJsonAddressesCallableFactory.java, test/integration/goldens/compute/com/google/cloud/compute/v1small/stub/HttpJsonAddressesStub.java, test/integration/goldens/compute/com/google/cloud/compute/v1small/stub/HttpJsonRegionOperationsCallableFactory.java, test/integration/goldens/compute/com/google/cloud/compute/v1small/stub/HttpJsonRegionOperationsStub.java, test/integration/goldens/compute/com/google/cloud/compute/v1small/stub/RegionOperationsStub.java, test/integration/goldens/compute/com/google/cloud/compute/v1small/stub/RegionOperationsStubSettings.java
googleapis now has compute v1small, so no need to pull in googleapis_discovery.
error_prone is simply unused.
javax.validation is not used anywhere either. `git grep javax.validation` shows nothing.
=> chore: clean up build

.githooks/pre-commit, .github/workflows/ci.yaml, BUILD.bazel, DEVELOPMENT.md
Adds `test_suite(name = "units", ...)`, so now we can just do `bazel test units` to run all tests.
Also, in #919, I missed the project itself from the debug generator runtime classpath. This is fixed.
=> chore: add test_suite for unit tests and fix minor build issues

DEVELOPMENT.md
=> chore: update DEVELOPEMENT.md

repositories.bzl, src/main/java/com/google/api/generator/ProtoRegistry.java, src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/SubscriberClientTest.golden, test/integration/BUILD.bazel, test/integration/goldens/bigtable/com/google/bigtable/v2/TableName.java, test/integration/goldens/bigtable/com/google/cloud/bigtable/data/v2/BaseBigtableDataClient.java, test/integration/goldens/bigtable/com/google/cloud/bigtable/data/v2/BaseBigtableDataClientTest.java, test/integration/goldens/bigtable/com/google/cloud/bigtable/data/v2/BaseBigtableDataSettings.java, test/integration/goldens/bigtable/com/google/cloud/bigtable/data/v2/MockBigtable.java, test/integration/goldens/bigtable/com/google/cloud/bigtable/data/v2/MockBigtableImpl.java, test/integration/goldens/bigtable/com/google/cloud/bigtable/data/v2/gapic_metadata.json, test/integration/goldens/bigtable/com/google/cloud/bigtable/data/v2/package-info.java, test/integration/goldens/bigtable/com/google/cloud/bigtable/data/v2/stub/BigtableStub.java, test/integration/goldens/bigtable/com/google/cloud/bigtable/data/v2/stub/BigtableStubSettings.java, test/integration/goldens/bigtable/com/google/cloud/bigtable/data/v2/stub/GrpcBigtableCallableFactory.java, test/integration/goldens/bigtable/com/google/cloud/bigtable/data/v2/stub/GrpcBigtableStub.java, test/integration/goldens/pubsub/com/google/cloud/pubsub/v1/SubscriptionAdminClient.java, test/integration/goldens/pubsub/com/google/cloud/pubsub/v1/SubscriptionAdminClientTest.java, test/integration/goldens/redis/com/google/cloud/redis/v1beta1/CloudRedisClient.java, test/integration/goldens/redis/com/google/cloud/redis/v1beta1/CloudRedisClientTest.java, test/integration/goldens/redis/com/google/cloud/redis/v1beta1/CloudRedisSettings.java, test/integration/goldens/redis/com/google/cloud/redis/v1beta1/MockCloudRedisImpl.java, test/integration/goldens/redis/com/google/cloud/redis/v1beta1/gapic_metadata.json, test/integration/goldens/redis/com/google/cloud/redis/v1beta1/stub/CloudRedisStub.java, test/integration/goldens/redis/com/google/cloud/redis/v1beta1/stub/CloudRedisStubSettings.java, test/integration/goldens/redis/com/google/cloud/redis/v1beta1/stub/GrpcCloudRedisStub.java, test/integration/goldens/storage/com/google/storage/v2/StorageClient.java, test/integration/goldens/storage/com/google/storage/v2/StorageClientTest.java
Routing annotation was not recognized on parsing protos, this is due to RoutingProto's extensions are not registered. This also indicate that we are missing integration tests for the new routing annotation, hence added bigtable to integration tests as well.
=> fix: Routing annotation was not recognized on parsing protos

BUILD.bazel
Bazel debugger rule is not working because it's missing some runtime dependencies. Added the MAIN_DEPS to the deps of debugger rule.
=> fix: Add dependencies to debugger rule.

PROPERTIES.bzl, WORKSPACE, repositories.bzl
Bump gax-version to 2.12.2. Remove unnecessary api-common dependency since it's a transitive dependency of gax.
=> chore: Bump gax-version to 2.12.2. 

BUILD.bazel
This seems to be added setup in #936, but later accidentally deleted?
Verified test runs with command `bazel run //:update_com_google_api_generator_engine_JavaCodeGeneratorTest`
=> fix: setups for manually runs single JUnit test

.github/snippet-bot.yml
Check failing on unit test made up product prefix in generated sample region tags.
[example](https://github.com/googleapis/gapic-generator-java/pull/933/checks?check_run_id=5559995994)
=> chore: update snippet bot to ignore unit tests

.githooks/pre-commit
- `go get -u` command used to install `addlicense` tool in L51 is [deprecated](https://go.dev/doc/go-get-install-deprecation#overview) since Go 1.17. Replace it with `go install`.
- Add similar function to install `buildifier` if not already installed. This is used to fix Bazel format.
These are for development onboard only, tested changes locally:
```
INFO: Running command line: bazel-bin/google_java_format_verification.sh
INFO: Build completed successfully, 3 total actions
Precommit:    Setting up tool to fix Bazel format 
Precommit:    buildifier tool is not yet installed, downloading it now. 
Precommit:    Checking Apache License Header ... 
Precommit:    Setting up license check environment 
Precommit:    addlicense tool is not yet installed, downloading it now. 
Precommit: …
```
=> fix: pre-commit script addlicense tool installation command and add same for buildifier

src/main/java/com/google/api/generator/gapic/composer/comment/ServiceClientCommentComposer.java, src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceClientClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/grpcrest/ServiceClientClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientHeaderSampleComposer.java, src/test/java/com/google/api/generator/gapic/composer/grpcrest/GrpcRestTestProtoLoader.java, src/test/java/com/google/api/generator/gapic/composer/grpcrest/GrpcServiceCallableFactoryClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/grpcrest/GrpcServiceStubClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/grpcrest/HttpJsonServiceCallableFactoryClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/grpcrest/HttpJsonServiceClientTestClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/grpcrest/HttpJsonServiceStubClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/grpcrest/ServiceClientClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/grpcrest/ServiceClientTestClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/grpcrest/ServiceSettingsClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoClient.golden, src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoClientHttpJsonTest.golden, src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoClientTest.golden, src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoSettings.golden, src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/GrpcEchoCallableFactory.golden, src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/GrpcEchoStub.golden, src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/HttpJsonEchoCallableFactory.golden, src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/HttpJsonEchoStub.golden, src/test/java/com/google/api/generator/gapic/composer/rest/HttpJsonServiceStubClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/rest/ServiceClientTestClassComposerTest.java, src/test/proto/echo_grpcrest.proto
This is for `grpc+rest` clients.
Also add proper `grpc+rest` unit tests which were missing.
=> feat: Add add autogenerated javadoc sample for selecting REST transport over gRPC

.github/workflows/ci.yaml
Fixes #984
https://go.dev/doc/go-get-install-deprecation
=> chore: fix license header check

src/main/java/com/google/api/generator/gapic/composer/rest/HttpJsonServiceStubClassComposer.java, src/main/java/com/google/api/generator/gapic/model/HttpBindings.java, src/main/java/com/google/api/generator/gapic/protoparser/HttpRuleParser.java, src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoClient.golden, src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoClientTest.golden, src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/HttpJsonEchoStub.golden, src/test/java/com/google/api/generator/gapic/model/MethodTest.java, src/test/proto/echo_grpcrest.proto
if a field is declared as repeated in proto then its getter's name is `get<FieldName>List` not `get<FieldName>` instead.
=> fix: [REGAPIC] Fix repeated fields handling for query parameters

rules_java_gapic/java_gapic_pkg.bzl
Now to include samples in the package we have to pass `include_samples = True` in the build file such as:
```
java_gapic_assembly_gradle_pkg(
name = "google-cloud-accessapproval-v1-java",
deps = [
":accessapproval_java_gapic",
":accessapproval_java_grpc",
":accessapproval_java_proto",
":accessapproval_proto",
],
include_samples = True,
)
```
Not including (as currently is) will result in no samples being included allowing us to roll out slower. This isn't whether samples will be generated but whether they would be included in the assembly package, that would require a more complicated change.
Follow up to: cl/446288272
=> chore: avoid using implicitly declared samples target in BUILD.bazel

DEVELOPMENT.md, WORKSPACE, repositories.bzl, test/integration/goldens/README.md
- Moves the `com_google_googleapis` dependency into `WORKSPACE`
- Updates a couple docs for readability and fixing some small typos
=> chore: move googleapis dependency to WORKSPACE and update docs

BUILD.bazel, src/main/java/com/google/api/generator/engine/ast/TypeNode.java, src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceClientTestClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/defaultvalue/DefaultValueComposer.java, src/test/java/com/google/api/generator/gapic/composer/defaultvalue/DefaultValueComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/grpcrest/GrpcRestTestProtoLoader.java, src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoClientHttpJsonTest.golden, src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoClientTest.golden, src/test/proto/echo_grpcrest.proto
1) Generate an empty unit test  method even if the method is not supported in a particular transport. Bazel fails test execution, if the test class has no `@Test` methods. In case if there is a service with only unsupported methods, and we do not generate unit tests for those, we would get an empty unit test, which will fail execution in our automatic bazel build pipeline.
2) For fields of `google.protobuf.Value` type set an actual value for it (to avoid non-set vs null value differences after json serialization/deserializaiton roudtrip). This looks like an issue in protobuf support of `google.protobuf.Value` type in JSON and not specific to GAPIC.
=> fix: More REST transport fixes

src/main/java/com/google/api/generator/engine/ast/LambdaExpr.java, src/test/java/com/google/api/generator/engine/ast/LambdaExprTest.java, src/test/java/com/google/api/generator/engine/writer/JavaWriterVisitorTest.java
This will enable it to be assigned to an appropriate variable
**Before this change:**  cannot assign a lambda expression to a variable because its type is always `VOID`. 
**After this change:** lambda expression builder will infer type from `returnExpr`’s expression type. Allowing it to be assigned to an appropriate variable. Because `returnExpr` is a required field, its type should always be accessible.
**Example:** a naive sample usage is provided in [JavaWriterVisitorTest.java](https://github.com/googleapis/gapic-generator-java/pull/1011/files#diff-60163f71e845b4cc97f9ccd7101646aa243fa5317a77cd326a7f61143618f62f) as test. Another example is what I am trying to generate for spring autoconfig code: `this.projectIdProvider = () -> clientProperties.getProjectId();`. Ideally through method …
=> feat(ast): add support for LambdaExpr to infer type from return expr type

src/main/java/com/google/api/generator/engine/ast/LambdaExpr.java, src/test/java/com/google/api/generator/engine/ast/LambdaExprTest.java
Fix for Issue #843. This pull request modifies allows the creation of lambda expressions that have _void_ as return type. The main change was made in `ast/LambdaExpr.java`
=> fix(ast): removed lambda void return type check

rules_java_gapic/java_gapic_pkg.bzl
The googleapis Bazel build logs have a lot of
```
INFO: From Action google/cloud/aiplatform/v1beta1/proto-google-cloud-aiplatform-v1beta1-java-srcs_pkg.tar.gz:
rm: missing operand
Try 'rm --help' for more information.
rm: missing operand
Try 'rm --help' for more information.
rm: missing operand
Try 'rm --help' for more information.
rm: missing operand
Try 'rm --help' for more information.
rm: missing operand
Try 'rm --help' for more information.
rm: missing operand
Try 'rm --help' for more information.
```
I'm assuming it can only come from the line I'm changing here, in case if there are no files with zero size. I'm changing it so that it will only called `rm` if needed.
=> fix(bazel): do not emit empty rm commands

rules_java_gapic/java_gapic_pkg.bzl
Each use of `cd -` prints the directory it's returning to. Let's not print it to save some log lines.
```
INFO: From Action google/cloud/commerce/consumer/procurement/v1alpha1/google-cloud-consumer-procurement-v1alpha1-java.tar.gz:
/bazel_root/1d081bf08a15278ca34ce779797e8450/sandbox/processwrapper-sandbox/15758/execroot/com_google_googleapis
INFO: From Action google/cloud/videointelligence/v1/gapi-cloud-videointelligence-v1-go.tar.gz:
/bazel_root/1d081bf08a15278ca34ce779797e8450/sandbox/processwrapper-sandbox/25287/execroot/com_google_googleapis
```
=> fix(bazel): do not print current working directory

WORKSPACE, rules_java_gapic/java_gapic.bzl, src/main/java/com/google/api/generator/gapic/composer/common/AbstractTransportServiceStubClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/grpc/GrpcServiceStubClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/rest/HttpJsonServiceStubClassComposer.java, src/main/java/com/google/api/generator/gapic/model/GapicContext.java, src/main/java/com/google/api/generator/gapic/protoparser/Parser.java, src/main/java/com/google/api/generator/gapic/protoparser/PluginArgumentParser.java, src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/HttpJsonEchoStub.golden, src/test/java/com/google/api/generator/gapic/composer/rest/RestTestProtoLoader.java, src/test/java/com/google/api/generator/gapic/composer/rest/goldens/HttpJsonComplianceStub.golden, src/test/java/com/google/api/generator/gapic/protoparser/PluginArgumentParserTest.java, test/integration/goldens/compute/src/com/google/cloud/compute/v1small/stub/HttpJsonAddressesStub.java
See b/232457244 for exact requirements. In short, this PR added four things:
1. Add a flag to the Java microgenerator Bazel plugin to determine whether we need to generate a client library that supports rest numeric enums. This flag is to make sure we only generate client libraries with numeric enums for the services that have already upgraded to the latest ESF. See go/gapic-numericenum-release for details.
2. Serialize enum object to int if the above flag is set to true
3. Add a query parameter `$alt=json;enum-encoding=int` to every request if the above flag is set to true so that the backend will return response with numeric enums.
4. Upgrade gax-java to the latest since it's dependent on https://github.com/googleapis/gax-java/pull/1743.
=> feat: Add support for rest numeric enums.

src/main/java/com/google/api/generator/gapic/composer/Composer.java, src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceClientClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceSettingsClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceStubSettingsClassComposer.java, src/main/java/com/google/api/generator/gapic/model/GapicClass.java, src/main/java/com/google/api/generator/gapic/model/Service.java, src/test/java/com/google/api/generator/gapic/composer/ComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/grpc/ServiceClientClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/grpc/ServiceSettingsClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/grpc/ServiceStubClassComposerTest.java, src/test/java/com/google/api/generator/gapic/composer/grpc/ServiceStubSettingsClassComposerTest.java, src/test/java/com/google/api/generator/gapic/model/ServiceTest.java
Follow-up to #1066.
This PR exposes parsed `apiShortName` and `apiVersion` as fields in `Service.java`, since the source fields (defaultHost and protoPakkage) are both defined per-service. It also:
- Adds these two fields correspondingly to GapicClass so that it can be composed from Service given these two upstream fields, then replaces `withDefaultHost` (for building GapicClass) added in #1040 with `withApiShortName` and `withApiVersion`. (Composers and tests where this is currently used for sample generation are updated) 
This change will enable Spring Codegen (when eventually split out from this repo) to reuse this parsing logic in descriptive comments and metadata. It also moves the parsing logic to earlier in the parse-compose process.
=> refactor: expose parsed api short name and version as fields in Service

src/main/java/com/google/api/generator/gapic/composer/grpcrest/ServiceClientClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientHeaderSampleComposer.java, src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoClient.golden, src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoEmpty.golden
The old version also worked for the most part, but it is longer and also does not configure proper headers for statistics gathering.
=> fix: fix REST transport client creation generated javadoc sample

src/main/java/com/google/api/generator/spring/SpringWriter.java, src/test/java/com/google/api/generator/spring/SpringWriterTest.java, src/test/java/com/google/api/generator/spring/goldens/SpringAdditionalMetadataJson.golden, src/test/java/com/google/api/generator/spring/goldens/SpringPackagePom.golden
**In this PR:**
- Extract content-building logic in `SpringWriter` not covered by composers into own methods with visibility for testing
- Adds unit testing for:
- Contents of `org.springframework.boot.autoconfigure.AutoConfiguration.imports` (string comparison)
- Contents of `additional-spring-configuration-metadata.json` ~(json comparison)~ (generates and updates golden file)
- Contents of `pom.xml` (generates and updates golden file)
=> test(spring): add tests for content-building methods in SpringWriter

src/main/java/com/google/api/generator/engine/writer/ImportWriterVisitor.java, src/test/java/com/google/api/generator/engine/writer/ImportWriterVisitorTest.java
This PR is a follow-up patch to #1012 which added support for annotations on `VariableExpr`. It updates `ImportWriterVisitor `so that import generation also covers these annotations. 
Note: the Spring CodeGen branch ([autoconfig-gen-draft2](https://github.com/googleapis/gapic-generator-java/tree/autoconfig-gen-draft2)) will need a rebase after this is merged, and have its golden test files updated to reflect this change.
=> fix(ast): add import generation for annotations on VariableExpr

src/main/java/com/google/api/generator/spring/utils/Utils.java, src/test/java/com/google/api/generator/spring/composer/goldens/SpringPackageInfo.golden, src/test/java/com/google/api/generator/spring/composer/goldens/SpringPackageInfoFull.golden, src/test/java/com/google/api/generator/spring/goldens/SpringAdditionalMetadataJson.golden, src/test/java/com/google/api/generator/spring/goldens/SpringPackagePom.golden
Follow-up PR to switch `getLibName()` to use apiShortName parsed from default host.
- ~Added an extra conversion for showcase (which we unit test with), which uses `localhost:7469` and does not parse to a pretty libname. (This means the current spring golden tests don't really cover other cases of `getLibName()`, but the logic itself also lives upstream)~
=> fix(spring): use parsed api shortname as libname

src/main/java/com/google/api/generator/spring/SpringWriter.java, src/test/java/com/google/api/generator/spring/goldens/SpringPackagePom.golden
Instead of package name, use corresponding client library's artifact-id as artifact id prefix for spring modules.
Reasoning of this change: 
- Generated module artifact name aligned better with corresponding client library's, less confusing for users.
- "client-library-artifact-id" is already needed to substitute in generation script, so no added item there.
- Charging from [monorepo](https://github.com/googleapis/google-cloud-java/blob/main/versions.txt), only one version of client library is published per module. So consider the generation process starts from a client library coordinates, then the risk of not including `-v1beta1`/`-v1` from package name is mininum. 
- It's more direct this way to generate README item in spring-cloud-gcp side. …
=> fix(spring codegen): use client-library-artifact-id as pom artifactId prefix

src/main/java/com/google/api/generator/spring/composer/SpringPropertiesClassComposer.java, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringPropertiesFull.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringPropertiesGrpc.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringPropertiesGrpcRest.golden
**This PR:** updates setters for Spring properties of type `org.threeten.bp.Duration` to accept argument of type `java.time.Duration` instead, and parse to `org.threeten.bp.Duration` in the setter body. 
- Converting between the two types: `parse()` and `toString()` methods for both will accept or return ISO-8601 seconds based representation, such as `PT8H6M12.345S`.
This addresses the issue that properties of type `org.threeten.bp.Duration` cannot be set from strings (e.g. specified in Spring property files) because the implicit conversion is unsupported. Spring boot has [dedicated support](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.typesafe-configuration-properties.conversion.durations) for properties of type …
=> fix(spring): update setters for properties of type Duration

src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceClientTestClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/grpc/ServiceClientTestClassComposer.java, src/main/java/com/google/api/generator/gapic/composer/rest/ServiceClientTestClassComposer.java
* **Handle [method signatures with nested arguments](https://github.com/googleapis/gapic-showcase/blob/main/schema/google/showcase/v1beta1/identity.proto#L44-L46)**.
Before:
```java
Assert.assertEquals(displayName, actualRequest.getDisplayName());
```
After:
```java
Assert.assertEquals(displayName, actualRequest.getUser().getDisplayName());
```
* **Provide a consistent tolerance value of `0.0001` for `assertEquals` on `double` and `float` values.**
Before:
```java
Assert.assertEquals(expected, actual);
```
> bazel error: [DoNotCall] This method always throws java.lang.AssertionError. Use assertEquals(expected, actual, delta) to compare floating-point numbers
After:
```java
Assert.assertEquals(expected, actual, 0.0001);
```
=> fix: Support testing nested argument method signatures and 'double' field assertions

src/main/java/com/google/api/generator/spring/SpringWriter.java, src/test/java/com/google/api/generator/spring/goldens/SpringPackagePom.golden
- `{{starter-version}}` are not needed anymore as we inherit version from parent pom.
- add parent version placeholder. Changes on spring-cloud-gcp side needed.
- remove redundant groupid.
- remove versions for `spring-cloud-gcp-core` and `spring-boot-starter`, specified in `genereated-parent` pom
=> fix(spring): fix write pom placeholders.

src/main/java/com/google/api/generator/spring/composer/SpringAutoConfigClassComposer.java, src/main/java/com/google/api/generator/spring/utils/LoggerUtils.java, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationFull.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpc.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpcRest.golden
As suggested after discussing https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1364
=> feat: set logging level to trace

.github/snippet-bot.yml
This [snippet-bot issue and conversation](https://github.com/googleapis/repo-automation-bots/issues/4697) states that snippet-bot pulls its configuration from the base branch rather than the PR head. This PR sets the base branch configuration to ignore files that will be introduced in https://github.com/googleapis/gapic-generator-java/pull/1100
=> ci(showcase): disable snippet-bot for showcase

DEVELOPMENT.md
Adding a step to use gapic-generator-java in local computer.
Credit: @chanseokoh 's "How does gapic-generator-java (“Java Microgenerator”) fit into the Cloud library generation workflow?" documentation.
=> docs: development with local gapic-generator-java

src/main/java/com/google/api/generator/spring/composer/SpringAutoConfigClassComposer.java, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationFull.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpc.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpcRest.golden
Enables usage of `[Service]Settings` as a separate bean, as suggested in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1364#discussion_r1036178245
Changes were based on [POC](https://github.com/zhumin8/language_poc1/pull/4) by @zhumin8 and [POC fixes](https://github.com/zhumin8/language_poc1/pull/5) by @emmileaf
=> feat: service settings as a bean

src/main/java/com/google/api/generator/spring/SpringWriter.java, src/main/java/com/google/api/generator/spring/composer/SpringAutoConfigClassComposer.java, src/main/java/com/google/api/generator/spring/composer/SpringPropertiesClassComposer.java, src/main/java/com/google/api/generator/spring/utils/ComposerUtils.java, src/main/java/com/google/api/generator/spring/utils/GlobalPropertiesUtils.java, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationFull.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpc.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpcRest.golden, src/test/java/com/google/api/generator/spring/goldens/SpringPackagePom.golden
As discussed off-line, instead of depending on a new `global-properties` module, use `CredentialsProvider` bean from `spring-cloud-gcp-autoconfigure` instead.
- Replace dependency from `core` to `autoconfigure` module.
- Revert #1071 and implement changes shown in [poc](https://github.com/zhumin8/language_poc1/pull/7)
- Minor code cleanups and util method extracted from `SpringPropertiesClassComposer.java`. 
Note: #1071 and https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1308 will be obsolete after this change.
Also, conflicts needs to be resolved between this pr and #1110 depending on merging order.
=> fix(spring): Replace global properties with CredentialsProvider bean

.bazeliskrc, .github/workflows/ci.yaml
" ci / build (8) " has been failing in https://github.com/googleapis/gapic-generator-java/pull/1156. Creating an empty pull request to see the build failures.
This PR changes:
- The unit tests in Bazel and "coverage" on it have been removed. @blakeli0 intends to remove it in another PR anyway.
- GitHub Actions to use bazelisk command that keeps the Bazel version stable.
- The client library generation job is separated from the build job.
As per https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md, ubuntu-latest has bazelisk installed.
=> build: use bazelisk avoid unexpected Bazel version upgrades

.bazeliskrc, .github/workflows/ci.yaml
- Brings in #1163 to spring codegen branch to fix Bazel 6.0.0 breaking changes in CI
- Cherry-picked commit instead of updating against main given repo restructure changes
=> build(spring): update spring branch with Bazel CI fix from main

src/main/java/com/google/api/generator/spring/SpringWriter.java, src/test/java/com/google/api/generator/spring/goldens/SpringPackagePom.golden
This is part 2 of implementation for repo structural changes in [PoC](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1383).
Changes in Pom string:
- changed parent to `spring-cloud-gcp-starters` and version with "-preview" suffix
- removed client library version (should inherit from Libraries BOM).
Corresponding changes in spring-cloud-gcp: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1394
=> fix(spring): pom writer changes to adapt to repo structure changes in hosting repo

.github/workflows/ci-maven.yaml, .github/workflows/ci.yaml
When a cache hit occurs, we don't update the cache.
Existing bazel cache is outdated (requiring refetching most dependencies) but is used often enough to prevent the cache from being replaced with an update. The existing implementation uses the static cache key `Linux-` due to the `secret` no longer existing.
The new implementation uses the dynamic cache key `Linux-${hashFile(WORKSPACE)}` with a fallback to `Linux-` if there's no hit. This will allow the current, outdated `Linux-` cache to eventually be garbage collected and updated.
https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#cache-hits-and-misses
From the Showcase 11 CI build of this PR: The `restore-key` is working to provide the existing cache as a backup.
```
Cache restored …
```
=> ci: fix bazel cache

src/main/java/com/google/api/generator/spring/composer/SpringAutoConfigClassComposer.java, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationFull.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpc.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpcRest.golden
Add name to `@ConditionalOnMissingBean` annotation when creating `TransportChannelProvider` bean so that it can be picked up with Qualifier in serviceSettings bean creation that follows.
This was missed in original [commit](https://github.com/googleapis/gapic-generator-java/commit/0643085e8e837f23d11b3bc18bded7e1551233ba) adding this bean and should fix error seen in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1407#issuecomment-1370058527
=> fix: add name to ConditionalOnMissingBean when creating bean

src/main/java/com/google/api/generator/spring/composer/SpringAutoConfigClassComposer.java, src/main/java/com/google/api/generator/spring/composer/comment/SpringAutoconfigCommentComposer.java, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationFull.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpc.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpcRest.golden
Addressing: https://github.com/googleapis/gapic-generator-java/pull/1110#issuecomment-1355712280
This was leftover from changes made in #1110
=> fix(spring): Separate out client settings bean and client bean comment

src/main/java/com/google/api/generator/spring/composer/SpringAutoConfigClassComposer.java, src/main/java/com/google/api/generator/spring/composer/SpringPropertiesClassComposer.java, src/main/java/com/google/api/generator/spring/utils/Utils.java, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationFull.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpc.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpcRest.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringPropertiesFull.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringPropertiesGrpc.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringPropertiesGrpcRest.golden
This PR is a patch for the `RetrySettings` configuration issue discovered in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1407#issuecomment-1363280649. It excludes streaming and LRO methods from retry configuration through spring properties for now. 
- Ref: [UnaryCallSettings](https://github.com/googleapis/gax-java/blob/main/gax/src/main/java/com/google/api/gax/rpc/UnaryCallSettings.java) vs. [StreamingCallSettings](https://github.com/googleapis/gax-java/blob/main/gax/src/main/java/com/google/api/gax/rpc/StreamingCallSettings.java); how gapic-generator [configures default retry settings per-method](https://github.com/googleapis/gapic-generator-java/blob/0fb58e0b459a5dea109afd8b41da57e48728deb3/gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common …
=> fix(spring): limit retry settings configuration by method type

src/main/java/com/google/api/generator/engine/ast/JavaDocComment.java, src/main/java/com/google/api/generator/spring/composer/comment/SpringAutoconfigCommentComposer.java, src/test/java/com/google/api/generator/engine/ast/JavaDocCommentTest.java, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationFull.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpc.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpcRest.golden
Adds `@param` and `@return` to method javadoc comments in generated autoconfiguration classes. 
Also adding a change to `JavaDocComment` to enable `@return` in comment. (this change in 537e33c2cdaf5e79d29f12fe12d372e1f75a525d can be copied to main branch of `gapic-generator-java` if useful.)
=> fix(spring): fix method javadoc missing @param and @return

gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractTransportServiceStubClassComposer.java, gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/grpc/GrpcServiceStubClassComposer.java, gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/rest/HttpJsonServiceStubClassComposer.java, gapic-generator-java/src/main/java/com/google/api/generator/gapic/model/Method.java, gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/HttpJsonEchoStub.golden, gapic-generator-java/src/test/java/com/google/api/generator/gapic/model/MethodTest.java, showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/HttpJsonEchoStub.java, showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/HttpJsonMessagingStub.java
This is a PR for Part 1 of #1117 (Override method with clearer exception messages for non-eligible and non-enabled Service RPCs). Opening this while I look at other possible approaches: 
Other approaches looked at/ to revisit:
- Override createCallableClassMembers to return Map<String, Expr> (Return either VariableExpr or ThrowExpr)
- Create a duplicate createCallableClassMembers (i.e. createInvalidCallableClassMembers) that copies functionality of createCallableClassMembers but returns Map<String, ThrowExpr>
Both approaches above had an issue when setting the return type for the callableGetter. ThrowExpr's type is always set as `UnsupportedOperationException` but the MethodDefinition's return type is not (i.e. for Streams it would be ServerStreamCallable or ClientStreamCallable/ Unary is …
=> feat: Add callable getters for non-eligible or non-enabled REST methods

src/main/java/com/google/api/generator/spring/composer/SpringAutoConfigClassComposer.java, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationFull.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpc.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpcRest.golden
This PR is a follow-up to https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1364#discussion_r1062017855. 
Updated behaviour (see #1078) for when `Transport.REST_GRPC` and `useRest = true` (through properties):
- The `ServiceSettings` bean uses `newHttpJsonBuilder`
- The `TransportChannelProvider` bean definition returns `defaultHttpJsonTransportProviderBuilder`
=> fix(spring): use newHttpJsonBuilder in settings bean for REST transport option

gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/ChannelPool.java, gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcDirectStreamController.java, gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/ChannelPoolTest.java
We got a customer issue and the stacktrace didn't show us where the call was cancelled (b/263968439)
When trying to reproduce this error, we noticed some inconsistent behaviors when we cancel the stream in onStart()
```
client.readRowsCallable().call(Query.create("t"), new ResponseObserver<Row>() {
@Override
public void onStart(StreamController streamController) {
streamController.cancel();
}
@Override
public void onResponse(Row row) {
}
@Override
public void onError(Throwable throwable) {
}
@Override
public void onComplete() {
}
});
```
When the above code is called, we got exception:
```
Caused by: java.util.concurrent.CancellationException: User cancelled stream
at com.google.api.gax.rpc.ServerStreamingAttemptCallable.onCancel(ServerStreamingAttemptCallable.java:309)
```
However, if we …
=> fix: Handle cancel in ReleasingClientCall and rethrow the exception in start

api-common-java/pom.xml, gapic-generator-java-bom/pom.xml, gapic-generator-java-pom-parent/pom.xml, gapic-generator-java/pom.xml, gax-java/pom.xml, java-common-protos/pom.xml, java-iam/pom.xml
The gapic-generator powers non-Cloud code generation. It may make sense for the groupId to be under `com.google.api` instead of `com.google.cloud` and for the gapic monorepo related modules to have a consistent groupId.
=> fix: Rename gapic-parent-pom to groupId to google.cloud.api

src/main/java/com/google/api/generator/spring/composer/SpringAutoConfigClassComposer.java, src/main/java/com/google/api/generator/spring/composer/SpringPropertiesClassComposer.java, src/main/java/com/google/api/generator/spring/utils/Utils.java
This PR switches camelcase handling to use align with logic used in generating client libraries, e.g. [here](https://github.com/googleapis/gapic-generator-java/blob/8c1facf7a2ad2e42d6de490aebbb671439d4f1f2/gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceSettingsClassComposer.java#L254). However, it introduces no updates to golden tests for the spring composers, and my local test to regenerate https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1449 using this branch also showed no diff.
I think `spring-cloud-gcp` enforces stricter checkstyle rules ([fail on warning](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/a5a346600e4b123643d9a507144d9167280c8870/pom.xml#L273-L274)) than what is used for the client libraries, so …
=> fix(spring): switch camelcase conversion logic to use JavaStyle

src/main/java/com/google/api/generator/spring/SpringWriter.java, src/test/java/com/google/api/generator/spring/goldens/SpringPackagePom.golden
This enables release-please setup in `spring-cloud-gcp` to update version as needed. (Ref: [parent pom](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/0caa9b6245cb4281b8d8da7ccb9f8fa993b0b9c4/spring-cloud-gcp-starters/pom.xml#L9))
=> chore(spring): add release-please annotations to pom template

src/main/java/com/google/api/generator/spring/composer/SpringAutoConfigClassComposer.java, src/main/java/com/google/api/generator/spring/composer/comment/SpringAutoconfigCommentComposer.java, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationFull.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpc.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpcRest.golden
This PR addresses the [javadoc error](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/actions/runs/4009223364/jobs/6884435843) observed in our attempt to set up `spring-cloud-previews` for release.
Cause of javadoc error: few exceptions of incorrect client library `<service>Client` and `<service>Settings` class names
- Misalignment: [`service.name()`](https://github.com/googleapis/gapic-generator-java/blob/c96a2e7cf647cf245199c33ad989c8050208646e/gapic-generator-java/src/main/java/com/google/api/generator/gapic/model/Service.java#L28) vs. [`service.overridenName()`](https://github.com/googleapis/gapic-generator-java/blob/c96a2e7cf647cf245199c33ad989c8050208646e/gapic-generator-java/src/main/java/com/google/api/generator/gapic/model/Service.java#L42) can be different
- This did not …
=> fix(spring): fix client and settings class names in comments

.kokoro/presubmit/downstream-build.sh
To reflect recent migration of java-shared-dependencies repository to google-cloud-java.
To fix the problem found in https://github.com/googleapis/gapic-generator-java/pull/1290#issuecomment-1412695859
Kokoro downstream tests to use java-shared-dependencies in google-cloud-java repository.
=> ci: use java-shared-dependencies in google-cloud-java repository for downstream test

gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/nativeimage/GrpcNettyFeature.java, gax-java/gax-grpc/src/main/resources/META-INF/native-image/com.google.api/gax-grpc/native-image.properties, gax-java/gax-grpc/src/main/resources/META-INF/native-image/com.google.api/gax-grpc/reflect-config.json
Build initialization of netty causes inconsistent behavior when an application is run locally versus on Cloud Run. One such case as discovered in https://github.com/mutianf/graalvm-test is when a bigtable application works fine with native image compilation locally but times out on Cloud Run. 
More details:
Netty `System.nanoTime()` [as a memoized static start_time variable](https://github.com/netty/netty/pull/12459) when the native image is being build. `System.nanoTime()` is an arbitrary value and platform specific so when the start_time compared against another `System.nanoTime()` at run time on the container, the comparison may not always be consistent. Netty is initialized at native image build time by default for netty 4.x but we can adjust this by setting …
=> fix(java): initialize netty-shaded at run-time and add reflection configurations for netty classes

showcase/BUILD.bazel, showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/HttpJsonComplianceStub.java, showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/HttpJsonEchoStub.java, showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/HttpJsonIdentityStub.java, showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/HttpJsonMessagingStub.java, showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/HttpJsonSequenceServiceStub.java, showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/HttpJsonTestingStub.java, showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITFirstHttp.java, showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITNumericEnums.java
Disabling this feature until https://github.com/googleapis/gapic-showcase/issues/1255 is addressed to unblock showcase testing development. 
Created a follow up issue to track enabling of numeric enum feature for showcase.
=> ci(showcase): disable rest_numeric_enum for showcase testing

.bazeliskrc
Pin Bazel version to 5.2.0 as googleapis already [updated](https://github.com/googleapis/googleapis/blob/ebf47e25ff363de57a6036562504db6caf3d8b89/.bazeliskrc#L2) to 5.2.0
=> chore: Pin Bazel version to 5.2.0

src/main/java/com/google/api/generator/spring/composer/SpringAutoConfigClassComposer.java
This PR aligns the spring generator with main branch changes from https://github.com/googleapis/gapic-generator-java/issues/1117. I copied the relevant `isSupportedByTransport(Transport.REST)` logic as a quick fix instead of cherry-picking the commits, since the branches have diverged a bit since the monorepo migration. 
Future note: as part of migrating this spring generator code away from its separate branch and depending on the gapic generator jar, I'd like to revisit this logic to call the corresponding helpers in gapic-generator-java main.
=> fix(spring): update hasRestOption to exclude services with no rest-supported methods

renovate.json
Following up on https://github.com/googleapis/gapic-generator-java/pull/1338, suppressing renovate PRs for the `rules_pkg` dependency since it will need to align with version used in googleapis.
=> chore: add rules_pkg to renovate bot ignoreDeps

renovate.json
Fixes #1352, from missed separator in #1349's changes.
=> chore: fix renovate bot ignoreDeps

renovate.json
Copying packageGroup configuration from https://github.com/googleapis/synthtool/blob/master/synthtool/gcp/templates/java_library/renovate.json
This should avoid separate pull requests for Protobuf: https://github.com/googleapis/gapic-generator-java/pull/1155 and https://github.com/googleapis/gapic-generator-java/pull/1154
=> chore: renovate to group Protobuf artifacts

src/main/java/com/google/api/generator/spring/composer/SpringPropertiesClassComposer.java, src/main/java/com/google/api/generator/spring/composer/comment/SpringAutoconfigCommentComposer.java, src/test/java/com/google/api/generator/gapic/composer/grpcrest/GrpcRestTestProtoLoader.java, src/test/java/com/google/api/generator/spring/composer/SpringAutoConfigClassComposerTest.java, src/test/java/com/google/api/generator/spring/composer/SpringPropertiesClassComposerTest.java, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationFull.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpc.golden, src/test/java/com/google/api/generator/spring/composer/goldens/EchoSpringAutoConfigurationGrpcRest.golden, src/test/java/com/google/api/generator/spring/composer/goldens/WickedSpringAutoConfigurationNoRestRpcs.golden, src/test/java/com/google/api/generator/spring/composer/goldens/WickedSpringPropertiesNoRestRpcs.golden, src/test/proto/wicked.proto
This PR is a follow-up on #1343:
- Extends fix to `SpringPropertiesClassComposer`, so that for services without REST-enabled rpcs, the unused `useRest` property is also not generated 
- Adds golden tests for the updated `hasRestOption` scenario using the wicked proto
- Updates `SpringAutoconfigCommentComposer` for javadoc comments alluding to the `useRest` option
=> fix(spring): extend hasRestOption fix to properties composer and add golden tests

gapic-generator-java/README.md
Talked with Blake. Because the file is seldom updated, it's better to add a section in README.md rather than setting up automation. I closed https://github.com/googleapis/gapic-generator-java/pull/1359 for that reason (this pull request 1359 relied on master branch, not a released version, which may contain temporary changes there.)
=> chore: README.md to explain service_config.proto

gax-java/README.md
Adding description of gax, gax-grpc, and gax-httpjson. Credit: Vadym's "Java GAPIC Toolchain Transition" document.
I happened to find the document today and it's worth adding the note.
=> chore: adding description of gax, gax-grpc, gax-httpjson

renovate.json
Importing gax-java repository's renovate.json rule to this repository https://github.com/googleapis/gax-java/blob/main/renovate.json#L7.
As per the documentation (https://docs.renovatebot.com/modules/manager/regex/#regular-expression-capture-groups) I confirmed the regex `"=(?<depName>.+\\:.+?):(?<currentValue>.+?)\\n"` works in https://regex101.com/r/01eHFC/1
=> chore: importing gax-java's Renovate configuration with regex

.github/workflows/ci.yaml
As follow-up to monitoring dashboard still pointing to [ci.yaml](https://github.com/googleapis/gapic-generator-java/actions/workflows/ci.yaml):
- Renames `ci-maven.yaml` workflow to the former name of `ci.yaml` (previous bazel-based workflow, now removed), also to reflect that bazel is still used for running the integration tests.
=> chore: rename ci-maven workflow to ci

.github/workflows/ci.yaml, .github/workflows/downstream-native-image.yaml, WORKSPACE, showcase/README.md
Updating gapic-showcase to v0.26.0. 
For the REGAPIC testing efforts, it fixes an issue regarding PATCH requests: https://github.com/googleapis/gapic-showcase/pull/1262
=> chore: Update gapic-showcase to v0.26.0

api-common-java/LICENSE, api-common-java/pom.xml, gax-java/LICENSE, gax-java/gax-bom/pom.xml, gax-java/pom.xml
Fixes #1335 
Now uses the compliant [SPDX License Identifier](https://spdx.org/licenses/) as recommended by [Maven](https://maven.apache.org/pom.html#Licenses).
Both `LICENSE` files now also follow "Google LLC" guidance.
=> chore: api-common-java and gax-java use SPDX identifier for BSD-3-Clause license

.github/workflows/shared_dependencies.yaml, gapic-generator-java-pom-parent/pom.xml
Moving the removed job from https://github.com/googleapis/google-cloud-java/pull/9266/files#r1145267872 to gapic-generator-java.
=> ci: installing shared dependencies BOM upper-bound check

gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/GrpcDirectStreamController.java, gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcDirectStreamControllerTest.java
Fix the race condition in `GrpcDirectStreamController` when controller.request() is called when there's a retry attempt. This could cause `IllegalStateException`:
```
java.lang.IllegalStateException: Not started
at com.google.common.base.Preconditions.checkState(Preconditions.java:502)
at io.grpc.internal.ClientCallImpl.request(ClientCallImpl.java:451)
at com.google.api.gax.grpc.GrpcDirectStreamController.request(GrpcDirectStreamController.java:95)
at com.google.api.gax.grpc.ExceptionResponseObserver$1.request(ExceptionResponseObserver.java:67)
at com.google.api.gax.rpc.ServerStreamingAttemptCallable.onRequest(ServerStreamingAttemptCallable.java:345)
at com.google.api.gax.rpc.ServerStreamingAttemptCallable.access$200(ServerStreamingAttemptCallable.java:97)
at …
```
=> fix: Fix race condition in GrpcDirectStreamController

gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/ProtoMessageRequestFormatter.java, gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/ProtoMessageRequestFormatterTest.java
Part of #1440
---
We validate that the default path or any additional path matches. Otherwise, it is possible to have an invalid path returned and will result in a 404 when making the call.
=> fix: Validate paths and check additionalPathTemplates

gapic-generator-java/DEVELOPMENT.md
Fixes #1499 ☕️
Ran into this issue when doing some testing for the release manager. This is what I did to resolve it locally.
=> chore: Update steps to generate a library locally

coverage-report/pom.xml
This will fix https://github.com/googleapis/gapic-generator-java/pull/1511#issuecomment-1483254025
=> chore: coverage-report/pom.xml to have api-common annotation

java-iam/pom.xml
Removing google-iam-policy from java-iam/pom.xml dependency management section.
Reference [comment](https://github.com/googleapis/gapic-generator-java/pull/1429#discussion_r1137564797).
=> chore: Renovate bot should not update this dependency.

showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITClientSideStreaming.java, showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITServerSideStreaming.java, showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITUnaryCallable.java
Verifies:
- OK Server response when client sends streaming requests to server.
- Handling of Server Error response.
=> chore: add client-side streaming showcase integration tests for gRPC support

showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITServerSideStreaming.java
=> chore: Add httpjson server-side streaming showcase tests

.github/workflows/sonar.yaml, coverage-report/README.md, gapic-generator-java-pom-parent/pom.xml, gapic-generator-java/pom.xml, java-common-protos/pom.xml, java-iam/pom.xml, pom.xml
This PR adds showcase coverage to the gapic-generator-java-root sonarcloud project.
Verified with 
```
mvn clean verify -Penable-integration-tests -Dcheckstyle.skip -DenableTestCoverage -Denforcer.skip org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=mpeddada1_gapic-generator-java -Dsonar.organization=mpeddada1 -Dsonar.projectName=gapic-generaator-java-root
```
=> chore: add showcase coverage to full project coverage report

showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITBidiStreaming.java, showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITClientSideStreaming.java, showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITServerSideStreaming.java, showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITUnaryCallable.java, showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/util/TestClientInitializer.java
This PR does the following two things:
1. Add a basic BIDI streaming showcase test. 
2. Introduce a util class `TestClientInitializer` to centralize the initialization of test clients. 
This PR does not intend to test all scenarios of BIDI streaming, we may need more test cases for BIDI steaming.
=> test: Add BIDI streaming showcase test.

api-common-java/src/main/java/com/google/api/core/ApiFutures.java
=> fix: add javadoc for `ApiFutures`

.bazeliskrc
googleapis is using [6.0.0](https://github.com/googleapis/googleapis/blob/master/.bazeliskrc#L2) to build client libraries now, we should keep it in sync
=> build: Update Bazel version to 6.0.0 in .bazeliskrc

api-common-java/pom.xml
Fixes https://github.com/googleapis/gapic-generator-java/issues/1618
https://github.com/google/auto/blob/main/value/userguide/index.md#with-maven says
> You will need auto-value-annotations-${auto-value.version}.jar in your compile-time classpath, and you will need auto-value-${auto-value.version}.jar in your annotation-processor classpath.
- auto-value-annotations is declared as compile-time class path in 3 lines above this change.
- The annotation-processor class path is set in https://github.com/googleapis/gapic-generator-java/blob/main/api-common-java/pom.xml#L97, which this PR does not touch.
=> fix(deps): remove unnecessary auto-value in api-common-java

showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITCrud.java
Seeing this error in the CIs:
```
Apr 14, 2023 4:21:13 PM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Previous channel ManagedChannelImpl{logId=23, target=localhost:7469} was not shutdown properly!!! ~*~*~*
Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
```
Forgot to close the gRPC client.
=> chore: Close gRPC Identity client

gax-java/gax/src/test/java/com/google/api/gax/batching/AssertByPolling.java, gax-java/gax/src/test/java/com/google/api/gax/batching/AssertByPollingTest.java, gax-java/gax/src/test/java/com/google/api/gax/batching/FlowControllerTest.java
Fixes #1286 
Issue: "Expected thread to be WAITING (blocked) but instead was RUNNABLE (had not been started yet, or had not yet reached the blocking logic.)"
This PR increases the amount of time spent waiting for the thread to be blocked, while also implementing a polling assertion mechanism to prevent waiting the maximum amount of time.
Also: Raw types fixed in this file.
=> chore: handle FlowControllerTest thread start variation by polling

gapic-generator-java-bom/pom.xml
This PR adds `gapic-generator-java` to the BOM For downstream use in the `spring-cloud-gcp` generator, per discussion in https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/1686#discussion_r1168802844.
(Side note: I'm not sure if this is the right conventional commit prefix to use, vs. `chore:`?)
=> feat(deps): add gapic-generator-java to bom

gapic-generator-java/src/main/java/com/google/api/generator/engine/lexicon/Keyword.java, gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/defaultvalue/DefaultValueComposer.java, gapic-generator-java/src/main/java/com/google/api/generator/gapic/utils/JavaStyle.java, gapic-generator-java/src/test/java/com/google/api/generator/engine/lexicon/KeywordTest.java, gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoClient.golden, gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoClientHttpJsonTest.golden, gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoClientTest.golden, gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoSettings.golden, gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoStubSettings.golden, gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/GrpcEchoStub.golden, gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/HttpJsonEchoStub.golden, gapic-generator-java/src/test/proto/echo_grpcrest.proto
Unescape Java keyword field names when generating HttpJson unit tests, if the field is also a resource and used for http annotations. Otherwise we would not be able to populate default values for the field when generating HttpJson unit tests.
fixes: #1652
=> fix: Unescape Java keyword field names when generating HttpJson unit tests.

.github/workflows/ci.yaml
The java-cloud-bom was released today. The tag is "v26.13.0". This includes the recent change in validate-bom action that checks the dependency tree. https://github.com/googleapis/java-cloud-bom/blob/v26.13.0/tests/validate-bom/action.yml
=> test: use a tag in validating gapic-generator-java-bom

gax-java/gax/src/test/java/com/google/api/gax/batching/AssertByPollingTest.java
In response to flake: https://github.com/googleapis/gapic-generator-java/actions/runs/4781551520/jobs/8500121748
This test previous had its duration increased from 100ms to 300ms. To reduce flakiness without increasing max test time, this PR reduces the number of sleeps that occur from 2 to 1, thus reducing the chance of flakiness to allow the timeout to occur.
=> chore: reduce sleep count in AssertByPollingTest

gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
Remove DirectPath env GOOGLE_CLOUD_ENABLE_DIRECT_PATH. This env is not used by anyone. People who want to use DirectPath should use the `setAttemptDirectPath` option instead.
=> feat: remove directpath enable env

gax-java/dependencies.properties
Updating dependencies.properties protobuf version to match workspace version. Looks like renovate-bot doesn't update these automatically.
parent-pom is updated to match workspace: https://github.com/googleapis/gapic-generator-java/blob/main/gapic-generator-java-pom-parent/pom.xml#LL33C24-L33C24
=> chore: update protobuf dependency to match workspace

showcase/scripts/verify.sh
This prevents failure on `mvn verify` when there are (gitignored) `.iml` files in `showcase/gapic-showcase/**/*`
=> chore: exclude .iml files in showcase's `verify.sh` diff check

gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/GrpcDirectStreamControllerTest.java
Recent builds was hanging for 6 hours on this test.
https://github.com/googleapis/sdk-platform-java/actions/runs/5017051494/jobs/8994676841?pr=1622
https://github.com/googleapis/sdk-platform-java/actions/runs/5017051494/jobs/8994676448?pr=1622
=> chore: add 2 minute timeout to GrpcDirectStreamControllerTest

.github/workflows/create_additional_release_tag.yaml
Replacement for https://github.com/googleapis/sdk-platform-java/pull/1695
This fixes a couple issues with the original workflow:
1) Skips tags that are already created instead of failing
2) Uses exact matches for artifact IDs (multiple artifacts that begin with `gax` were causing issues)
3) Removes manual input for manual trigger; will automatically take the latest release which is what we want.
=> fix: update tag workflow

.github/workflows/create_additional_release_tag.yaml
Hopefully final follow-up to: https://github.com/googleapis/sdk-platform-java/pull/1699 
Workflow currently fails if tag is already created. This is because the actions/checkout checks out the code in a fresh workspace that does not contain tags by default. This adds in the step of fetching tags.
=> fix: fix release tag workflow to fetch all tags first

.kokoro/release/stage.sh
The release in https://github.com/googleapis/sdk-platform-java/pull/1674 failed with the following error:
```
[ERROR] Failed to execute goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:release (default-cli) on project gapic-generator-java-root: Execution default-cli of goal org.sonatype.plugins:nexus-staging-maven-plugin:1.6.13:release failed: No converter available
[ERROR] ---- Debugging information ----
[ERROR] message             : No converter available
[ERROR] type                : java.util.Arrays$ArrayList
[ERROR] converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
[ERROR] message[1]          : Unable to make field protected transient int java.util.AbstractList.modCount accessible: module java.base does not "opens java.util" to …
```
=> chore: add workaround for sonatype issue with Java 17

gax-java/gax/src/main/java/com/google/api/gax/rpc/ClientContext.java, gax-java/gax/src/test/java/com/google/api/gax/rpc/ClientContextTest.java
Credentials may be null, e.g. when connecting to an emulator. This fix makes it possible to use null credentials in combination with setting quota project id, something that may be useful in testing.
Fixes #1687 ☕️
=> fix: Allow quota project to be used in combination with null credentials

renovate.json
Temporarily turning off RenovateBot https://docs.renovatebot.com/configuration-options/#enabled.
We examine dependency upgrades manually until August to avoid unexpected dependency upgrades sneaking into the shared dependencies.
=> chore: temporarily turning off Renovate Bot until August

rules_java_gapic/java_gapic_pkg.bzl
The `dict | dict` syntax is only supported in Python 3.9+ which is not available in all test environments.
This PR uses a syntax that is supported more widely.
=> chore: copy and update PROPERTIES using widely supported syntax

gax-java/gax/clirr-ignored-differences.xml, gax-java/gax/pom.xml, gax-java/gax/src/main/java/com/google/api/gax/batching/BatchResource.java, gax-java/gax/src/main/java/com/google/api/gax/batching/BatcherImpl.java, gax-java/gax/src/main/java/com/google/api/gax/batching/BatchingDescriptor.java, gax-java/gax/src/main/java/com/google/api/gax/batching/DefaultBatchResource.java, gax-java/gax/src/test/java/com/google/api/gax/batching/BatcherImplTest.java
Abstract the element and byte counting to a `BatchResource` object so client libraries can add other dimensions to it. Also moved `shouldBeFull` logic to `BatchResource` so libraries can override it and use the other dimensions to determine if the batch should be flushed.
=> fix: abstract batch resource and add method to determine if batch should be flushed

.github/workflows/ci.yaml
This check compares the Showcase client against the **target branch** for binary incompatible changes.
Previous binary incompatibilities have been caught with the java-iam client, but:
* Showcase covers proto, grpc, and gapic artifacts. The java-iam client covers only proto and grpc.
* Showcase is intended to provide broad feature coverage, thus it will be a more robust binary compatibility check.
* Since this check compares against the target branch, it works with LTS branches.
See https://github.com/googleapis/sdk-platform-java/pull/1804 for an example of this check catching a binary incompatible change.
=> ci: add showcase-clirr check

gax-java/README.md
=> chore: Update gax-httpjson version in README

.github/workflows/ci.yaml, .github/workflows/sonar.yaml, .kokoro/presubmit/downstream-build.sh, WORKSPACE, showcase/README.md, showcase/gapic-showcase/pom.xml
Includes this fix for HttpJson IAM: https://github.com/googleapis/gapic-showcase/pull/1340
=> chore: Bump gapic-showcase version to 0.28.2

.github/workflows/ci.yaml
Install sdk-platform-java before performing final clirr check, so version changes are available in the local repository
Failure seen in release PR: https://github.com/googleapis/sdk-platform-java/pull/1806
=> ci: fix showcase-clirr check on release PRs

java-shared-dependencies/first-party-dependencies/pom.xml
Dependency management for gson is already provided via the [gapic-generator-java-bom import](https://github.com/googleapis/sdk-platform-java/blob/main/java-shared-dependencies/first-party-dependencies/pom.xml#L33-L40) which has a [gson entry](https://github.com/googleapis/sdk-platform-java/blob/main/gapic-generator-java-bom/pom.xml#L39-L43) with the [version defined in the gapic-generator-pom-parent](https://github.com/googleapis/sdk-platform-java/blob/main/gapic-generator-java-pom-parent/pom.xml#L33).
=> chore: remove gson version duplication

gax-java/pom.xml
Reverts googleapis/sdk-platform-java#1866
=> Revert "chore: gax-java now uses third-party-dependencies' management"

.github/workflows/sonar.yaml
From recent PRs' sonar scan results:
Read more [here](https://docs.sonarcloud.io/appendices/scanner-environment/)
=> ci: use java 17 with sonar

gapic-generator-java-bom/pom.xml, showcase/gapic-showcase/pom.xml, showcase/pom.xml
Primary change:
Showcase now uses shared-config as its parent, and imports shared-deps in its dependency management. This makes showcase more consistent with production client libraries which is useful for testing.
Secondary change:
Shared dependencies (via gapic-generator-java-bom) now includes a declaration for the google-auth-library-oauth2-http testlib.
=> ci: showcase now uses shared-dependencies

.github/workflows/ci.yaml, .kokoro/presubmit/common.sh, .kokoro/presubmit/common_test.sh, .kokoro/presubmit/downstream-build.sh, .kokoro/presubmit/downstream-compatibility.sh
Adds a new GitHub workflow to perform downstream testing on client libraries.
1. Installs sdk-platform-java to local maven.
2. Checks out the downstream repository at the latest release associated with the main branch, not HEAD.
3. Updates all dependencies on java-shared-dependency to the local version.
4. Compiles and invokes unit tests for the given client libraries. 
Does not invoke integration tests. Downstream integration testing is limited to google-cloud-java via the existing GraalVM Kokoro presubmits.
=> ci: add downstream compatibility checks

gax-java/gax/src/main/java/com/google/api/gax/core/GaxProperties.java, gax-java/gax/src/test/java/com/google/api/gax/core/GaxPropertiesTest.java
This PR adds java vendor information to the "gl-java" header value. Only when the information is present, add it to `javaRuntimeInformation`.
Local testing results for various combinations- 
(1)
the vendor is -> Eclipse Adoptium
the vendor version is -> Temurin-11.0.19+7
**the javaRuntimeInformation is -> 11.0.19__Eclipse-Adoptium__Temurin-11.0.19-7**
(2)
the vendor is ->Amazon.com Inc.
the vendor version is ->Corretto-11.0.19.7.1
**the javaRuntimeInformation is ->11.0.19__Amazon.com-Inc.__Corretto-11.0.19.7.1**
(3)
the vendor is ->Eclipse Adoptium
the vendor version is ->Temurin-11.0.20.1+1
**the javaRuntimeInformation is ->11.0.20.1__Eclipse-Adoptium__Temurin-11.0.20.1-1**
(4) [Case when vendor version is not available]
the vendor is ->Oracle Corporation
the vendor version is ->null …
=> feat: Adding vendor and vendor information in header

.github/workflows/verify_library_generation.yaml, library_generation/generate_library.sh, library_generation/test/generate_library_integration_test.sh, library_generation/utilities.sh
Adds OS detection to `generate_library.sh`
Manual input from workflow matrix is removed in favor of automatic detection
=> feat: hermetic build OS detection

gax-java/gax/src/test/java/com/google/api/gax/batching/BatcherImplTest.java
At the end of the test, it verifies that the batcher waited more than throttled time by capturing the argument of `callContext.withOption()`. There were two problems:
```
Error:  Failures: 
Error:    BatcherImplTest.testThrottlingBlocking:899 
apiCallContext.withOption(
<Capturing argument>,
<Capturing argument>
);
Wanted 1 time:
-> at com.google.api.gax.batching.BatcherImplTest.testThrottlingBlocking(BatcherImplTest.java:899)
But was 0 times.
```
The callContext.withOption method is called by `BatcherImpl.sendOutstanding()` method via
`BatcherImpl$PushCurrentBatchRunnable` in **another thread**. https://github.com/googleapis/sdk-platform-java/blob/4c741077d614093d08665e9ddd83fb0e332b7881/gax-java/gax/src/main/java/com/google/api/gax/batching/BatcherImpl.java#L206
Technically, there's no …
=> test: fix concurrency issue in testThrottlingBlocking

showcase/scripts/generate_components.sh
Fixes issues when running `mvn compile -Pupdate` in showcase
=> fix: showcase update goal fix

.kokoro/presubmit/downstream-compatibility.sh
Follow-up to https://github.com/googleapis/sdk-platform-java/pull/1989
The check will temporarily fail until we make a new release of google-cloud-java with https://github.com/googleapis/google-cloud-java/pull/9854 is made.
=> chore: restore monorepo check to be pinned at latest version

gax-java/.repo-metadata.json
Fixes: https://github.com/googleapis/sdk-platform-java/issues/2021
=> docs: add release level to gax metadata

library_generation/README.md, library_generation/test/generate_library_unit_tests.sh, library_generation/utilities.sh
This prevents the [failures](https://github.com/googleapis/sdk-platform-java/actions/runs/6263228150/job/17007141447?pr=1978) from showcase tests on the release-please branch since it tries to fetch a non-published version (`2.26.0`). The fix is to check whether we are on a release please branch as an additional condition to fetch the generator jar and pom locally.
=> fix(hermetic-build): obtain gapic-generator-java locally on release branch

gapic-generator-java/pom.xml, gax-java/dependencies.properties, gax-java/gax-httpjson/pom.xml, java-core/google-cloud-core/pom.xml
Reverts a temporary solution from https://github.com/googleapis/sdk-platform-java/pull/1791#issuecomment-1601587713 that excludes `j2objc-annotations` brought by `protobuf-java-util` which has a differing version. 
With protobuf `24.3`, this should not be necessary anymore
=> chore: revert exclusion for `j2objc-annotations`

rules_java_gapic/java_gapic.bzl
The generated unit tests for google/maps/places is not compilable, this is due to a Geo common proto is not added to Bazel test dependencies. See cl/567435528 and yaqs/8970072045605879808 for details.
In long term, the Bazel Java test should be replaced with Maven/Gradle tests, so all the dependencies are managed through the gapic-generator-java jar instead of Bazel. This should be done as part of the Hermetic build project, cc: @JoeWang1127
=> fix: Add Geo common protos to Bazel test dependencies.

library_generation/README.md, library_generation/generate_library.sh, library_generation/test/generate_library_integration_test.sh, library_generation/test/resources/proto_path_list.txt, library_generation/test/test_utilities.sh, library_generation/utilities.sh
=> feat: generate proto-only library

gax-java/gax-httpjson/BUILD.bazel, gax-java/gax-httpjson/src/main/java/com/google/api/gax/httpjson/HttpJsonClientCallImpl.java, gax-java/gax/BUILD.bazel, gax-java/gax/src/main/java/com/google/api/gax/rpc/ServerStreamingAttemptCallable.java, gax-java/gax/src/main/java/com/google/api/gax/rpc/Watchdog.java
Towards #1938 . This pull request replaces `javax.annotation.concurrent.GuardedBy` with errorprone's annotation. The official documentation https://github.com/google/error-prone/blob/master/docs/bugpattern/GuardedBy.md uses `com.google.errorprone.annotations.concurrent.GuardedBy`.
To reviewers, if you wonder whether the GuardedBy annotation has any effect, see the Bazel build caught a bug I intentionally introduced in https://github.com/googleapis/sdk-platform-java/pull/2060.
=> build: use errorprone's GuardedBy rather than javax's

gapic-generator-java-pom-parent/pom.xml, gax-java/gax-bom/pom.xml, java-shared-dependencies/first-party-dependencies/pom.xml, java-shared-dependencies/third-party-dependencies/pom.xml, java-shared-dependencies/upper-bound-check/pom.xml, showcase/pom.xml
This PR bumps java-shared-config to `1.5.8` and removes `<auto-value.version>` property declaration from the gapic-pom-parent. This version will be inherited from java-shared-config from now on. Current latest version for `<auto-value>` is `1.10.4`
=> deps: Bumping java-shared-config to 1.5.8

gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/ChannelPool.java
This should help developers and customer identify the cause of RPC failure due to shutdown channels
=> feat: more logging for ChannelPool shutdown

renovate.json
As described in https://docs.renovatebot.com/key-concepts/dashboard/, we can enable the dependency dashboard using this configuration.
=> chore: Enabling Dependency Dashboard for renovate-bot

library_generation/generate_library.sh
In this PR: add exceptions to include/exclude certain protos from `proto_path`.
- google/cloud/filestore: include `google/cloud/common/operation_metadata.proto`
- google/cloud/oslogin: include `google/cloud/oslogin/common/common.proto`
- google/devtools/containeranalysis/v1beta1: exclude `google/devtools/containeranalysis/v1beta1/cvss/cvss.proto` in java compiler
- google/cloud/aiplatform/v1beta1: 
- exclude `google/cloud/aiplatform/v1beta1/schema/io_format.proto`
- exclude `google/cloud/aiplatform/v1beta1/schema/*.proto` in java compiler
Follow up PR will add exceptions to exclude subdirectories within `proto_path`.
=> chore: include/exclude certain protos when generating libraries

renovate.json
All configuration as per https://docs.renovatebot.com/configuration-options/.
Might fix https://github.com/googleapis/sdk-platform-java/issues/2067
(Will re-open the issue if it gets closed and this fix doesn't work).
=> chore: Fixing renovate config

library_generation/README.md, library_generation/generate_library.sh, library_generation/test/generate_library_integration_test.sh, library_generation/test/generate_library_unit_tests.sh, library_generation/test/resources/proto_path_list.txt, library_generation/test/test_utilities.sh, library_generation/utilities.sh, showcase/scripts/generate_showcase.sh
In this PR:
- add three optional inputs to `generate_library.sh`:
- gapic_yaml
- grpc_service_config
- service_yaml
- add parsing methods to parse three inputs from BUILD
- add docs
=> feat: add gapic options as inputs to `generate_library.sh`

gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/ChannelPool.java, gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/ChannelPoolTest.java
fixes: #2081 
Add two flags `wasClosed` and `wasReleased` to `ReleasingClientCall` to check various scenarios. The combination of these two flags can make sure the count of outstanding RPCs can never go negative, and help us identify what exactly goes wrong next time it happens. 
The primary purpose of keeping a count for outstanding RPCs is to track when a channel is
safe to close. In grpc, initialization & starting of rpcs is split between 2 methods:
Channel#newCall() and ClientCall#start. gRPC already has a mechanism to safely close channels
that have rpcs that have been started. However, it does not protect calls that have been
created but not started. In the sequence: Channel#newCall() Channel#shutdown()
ClientCall#Start(), gRpc will error out the call telling the caller that the …
=> fix: Make sure outstanding RPCs count in ChannelPool can not go negative

gax-java/dependencies.properties
Currently we need to make an additional update to the dependencies.properties file for bazel.  Created an issue to investigate this further: https://github.com/googleapis/sdk-platform-java/issues/2210
=> deps: update graal-sdk to 22.3.3 in bazel dependencies file

.kokoro/presubmit/graalvm-native-17-downstream.cfg, .kokoro/presubmit/graalvm-native-downstream.cfg, renovate.json
=> chore: update graalvm container images to 22.3.3

library_generation/test/generate_library_integration_test.sh, library_generation/test/resources/proto_path_list.txt
Follow up of https://github.com/googleapis/google-cloud-java/pull/10050
* Confirms java files have been transferred by owl-bot-copy
* Adds `google/iam/v2` in the integration test list. 
* `google/iam/v1` is blacklisted from postprocessing list because it is not listed in its [owlbot yaml ](https://github.com/googleapis/google-cloud-java/blob/18020600f38e9cf966d3b4c12035954a7124344a/java-iam/.OwlBot.yaml#L25-L28)
=> fix: confirm owlbot-copy succeeeded to transfer java files

java-common-protos/pom.xml, java-iam/pom.xml
The maven-javadoc-plugin version is defined in the shared config pom.xml.
https://github.com/googleapis/java-shared-config/blob/778a547a09de71dbf9e5a42b155f12d15c319864/pom.xml#L472
=> build: do not declare javadoc plugin version

java-core/google-cloud-core/src/main/java/com/google/cloud/Structs.java, java-core/google-cloud-core/src/test/java/com/google/cloud/StructsTest.java
Originally implemented in https://github.com/googleapis/java-logging/blob/d3f897c26b5b55436d2212a0d7452940f15c413f/google-cloud-logging/src/main/java/com/google/cloud/logging/Structs.java, this is a common utility that other projects can benefit from.
Test is from: https://github.com/googleapis/java-logging/blob/d3f897c26b5b55436d2212a0d7452940f15c413f/google-cloud-logging/src/test/java/com/google/cloud/logging/StructsTest.java
The only difference between the java-logging implementation and this is that builder and class methods in Structs.java have been made public.
=> feat: Structs mapper utility

gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpJsonDirectServerStreamingCallableTest.java
Fixes #1975 
(This test is multithread because RetryingServerStreamingCallable uses an executor.)
This change increases the timeout in HttpJsonDirectServerStreamingCallableTest.testOnResponseError to avoid flakiness. There's no guarantee that this multithread test executes the CountDownLatch.countDown() within 2 seconds.
Will this 60-second timeout make the test execution slower? => No, it won't. `CountDownLatch.await(timeout)` returns immediately when the count becomes zero, without waiting for timeout.
In b/281936326, Lawrence tried to reproduce the issue in Windows, but it didn't. I think the best way is to increase timeout and observe any recurrence.
=> test: increasing timeout in testOnResponseError

.cloudbuild/cloudbuild-test-a.yaml, .cloudbuild/cloudbuild-test-b.yaml, .cloudbuild/cloudbuild.yaml, .cloudbuild/google-cloud-sdk.repo, .cloudbuild/graalvm_a.Dockerfile, .cloudbuild/graalvm_b.Dockerfile, .kokoro/presubmit/downstream-build.sh, renovate.json
Cloud Build Trigger for the docker image push is set to:
=> chore: add cloudbuild setup to publish docker images

gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpJsonDirectServerStreamingCallableTest.java
Fixes https://github.com/googleapis/sdk-platform-java/issues/1678
The assertion error tells `latch.await(2, TimeUnit.SECONDS)` did not return true.
https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CountDownLatch.html#await-long-java.util.concurrent.TimeUnit-
> Returns:
> true if the count reached zero and false if the waiting time elapsed before the count reached zero
Under a multithreading test, there's no guarantee that `latch.await(2, TimeUnit.SECONDS)` finishes within 2 second.
Increasing the value to 60 second to (drastically) reduce the flakiness. (This is the same tactics as https://github.com/googleapis/sdk-platform-java/pull/2291)
Will this 60-second timeout make the test execution slower? => No, it won't. `CountDownLatch.await(timeout)` returns immediately when the …
=> test: increasing timeout in testServerStreamingStart

gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java, gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java, gax-java/gax/clirr-ignored-differences.xml, gax-java/gax/src/main/java/com/google/api/gax/rpc/ClientContext.java, gax-java/gax/src/main/java/com/google/api/gax/rpc/EndpointContext.java, gax-java/gax/src/main/java/com/google/api/gax/rpc/StubSettings.java, gax-java/gax/src/test/java/com/google/api/gax/rpc/ClientContextTest.java, gax-java/gax/src/test/java/com/google/api/gax/rpc/EndpointContextTest.java, gax-java/gax/src/test/java/com/google/api/gax/rpc/testing/FakeStubSettings.java
Features:
- Introduces the concept of Universe Domain
- Endpoint + Universe Domain resolution is determined solely by the EndpointContext
- Support and compatibility for GDC-H, DirectPath, and mTLS
=> feat: Full Endpoint Resolution from EndpointContext

pom.xml, sdk-platform-java-config/pom.xml
This artifact is meant to mirror java-shared-config with the java-shared-dependencies version to then be consumed by downstream libraries (including the monorepo and handwritten libraries). The purpose of this artifact is to have a single update PR in the downstream libs to update shared-config and shared-dependencies instead of two. 
Name of the artifact: `sdk-platform-java-config`
=> feat: new artifact for sdk-platform-java configs. 

.cloudbuild/cloudbuild-test-a.yaml, .cloudbuild/cloudbuild-test-b.yaml, .cloudbuild/cloudbuild.yaml
Preparing docker images for #2290. Similar to the observations in https://github.com/googleapis/java-shared-config/issues/730, release-please doesn't update these files despite the following configs being applied:
-  Inline annotation with `x-version-update:<artifact-name>:released` 
- Addition of `.cloudbuild/` yamls files to `extraFiles` parameter in `release-please.yaml` ([line](https://github.com/googleapis/sdk-platform-java/blob/99e51953f319c97b225a0209b093367fa440f9d3/.github/release-please.yml#L6))
These files were updated after the the release PR was opened. In the case of java-shared-config, the update to these extra files didn't happen until a new release PR was opened. Created a follow-up task to verify the automation in the next release #2327.
=> chore: one time manual docker images update for shared-deps 3.21.0 release

sdk-platform-java-config/java.header, sdk-platform-java-config/license-checks.xml, sdk-platform-java-config/pom.xml
The checkstyle was initially disabled to address the following error when executing `mvn clean install`:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.3.1:check (checkstyle) on project sdk-platform-java-config: Failed during checkstyle execution: Unable to find configuration file at location: license-checks.xml: Could not find resource 'license-checks.xml'. -> [Help 1]
```
However, since this artifact is meant to be used as a parent for downstream libraries, there is a risk that the `checkstyle.skip` property will be inherited by child poms in the future. This may cause checkstyle to be unintentionally disabled.
=> fix: re-enable checkstyle in sdk-platform-java-config

.github/workflows/nightly.yaml
There was an issue where the nightly jobs were failing due to the Windows/MacOS tests using an outdated cache (https://github.com/googleapis/sdk-platform-java/actions/runs/7381299031).
Removing the caching on the Java8 setup should ensure that the jobs will use the artifacts from the previous step: `run: mvn install --errors --batch-mode --no-transfer-progress -Dcheckstyle.skip -DskipTests -T 1C`. This should ensure this issue does not happen again.
The Java11 setup cache should be okay to leave as-is, as it should get updated whenever it finds the `mvn install` creates different files. The issue was that the Java8 setup was pulling it's own cache instead of using the latest artifacts from `mvn install`.
=> build: remove caching in java 8 setup

release-please-config.json
For https://github.com/googleapis/sdk-platform-java/issues/2338 and https://github.com/googleapis/sdk-platform-java/pull/2339
Adjusting parameter format to follow https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-files 
Example of `extra-files` usage: https://github.com/googleapis/java-cloud-bom/blob/17c18f1ec0c92ba51a77ab8e9f3c6189412ecea2/release-please-config.json#L8
=> chore: fix release-please-config json extra files parameter

release-please-config.json
Following the `Update arbitrary yaml file` strategy is resulting in release-please making unexpected changes to the cloudbuild yaml files. See #2350.  
Modifying release-please configs to follow `Update arbitrary file` strategy combined with inline annotations as described in https://github.com/googleapis/release-please/blob/main/docs/customizing.md#updating-arbitrary-files:
=> fix: adjust release-please configs for cloudbuild yaml updates

java-shared-dependencies/unmanaged-dependency-check/src/main/java/com/google/cloud/UnmanagedDependencyCheck.java
In this PR:
- change regex in unmanaged dependency check. The check failed in google-cloud-java so we need to change the regex to allow dependencies like `com.google.cloud:google-xxx` and `com.google.api.grpc:(grpc|proto)-google-xxx`
```
This pull request seems to add new third-party dependency, [com.google.cloud:google-identity-accesscontextmanager, com.google.api.grpc:proto-google-iam-admin-v1, com.google.analytics:google-analytics-data, com.google.api.grpc:proto-google-identity-accesscontextmanager-type, io.grafeas:grafeas, com.google.api.grpc:grpc-google-identity-accesscontextmanager-v1, com.google.api.grpc:grpc-google-analytics-data-v1alpha, com.google.api.grpc:grpc-google-analytics-admin-v1alpha, com.google.api.grpc:proto-google-apps-script-type-protos, …
```
=> chore: change regex in check

.github/workflows/create_additional_release_tag.yaml
In this PR:
- Try to delete the `unmanaged-dependencies-check-latest` tag in remote repository and push it again.
The workflow of creating additional tags failed after the release:
```
fatal: tag 'unmanaged-dependencies-check-latest' already exists
```
Full log: https://github.com/googleapis/sdk-platform-java/actions/runs/7579063722/job/20642665504
=> chore: fix workflow of create additional release tags

java-shared-dependencies/unmanaged-dependency-check/src/main/java/com/google/cloud/UnmanagedDependencyCheck.java, java-shared-dependencies/unmanaged-dependency-check/src/test/java/com/google/cloud/UnmanagedDependencyCheckTest.java, java-shared-dependencies/unmanaged-dependency-check/src/test/resources/google-internal-artifact-test-case-pom.xml
In this PR:
- Add artifacts in gapic-bom to the allow list of unmanaged dependency check
- com.google.api.grpc:gapic-google-*
- com.google.analytics:google-analytics-*
- com.google.area120:google-area120-*
- com.google.apis:google-api-*
- io.grafeas:grafeas
Related check log in google-cloud-java:
```
Running Unmanaged Dependency Check against /home/runner/work/google-cloud-java/google-cloud-java/gapic-libraries-bom/pom.xml
This pull request seems to add new third-party dependency, [com.google.analytics:google-analytics-data, io.grafeas:grafeas, com.google.apis:google-api-services-cloudresourcemanager, com.google.analytics:google-analytics-admin, com.google.area120:google-area120-tables, com.google.apis:google-api-services-translate, com.google.api.grpc:gapic-google-cloud-storage-v2, …
```
=> chore: add artifacts in gapic bom in allow list

java-shared-dependencies/unmanaged-dependency-check/action.yaml
Updating the go link with correct one.
=> chore: fix go link for unmanaged dependency check

gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java, gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
Fixes: https://github.com/googleapis/sdk-platform-java/issues/2411
=> fix: Verify Universe Domain's DirectPath Compatibility after Endpoint Resolution

gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java, gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
Fixes #2423 
The root cause of the issue is that `logDirectPathMisconfig()` is called in the builder of `InstantiatingGrpcChannelProvider`, which could be called multiple times before it is fully instantiated. We should only call `logDirectPathMisconfig()` right before `createChannel()` which creates the first channel. 
We can not move it to before `createSingleChannel()` because it is used for resizing channel regularly after a client is initialized, and we only want to log direct path misconfiguration once.
=> fix: Move direct path misconfiguration log to before creating the first channel

gax-java/gax/src/test/java/com/google/api/gax/retrying/ScheduledRetryingExecutorTest.java
Fixes https://github.com/googleapis/sdk-platform-java/issues/1962.
The test was written under a bad assumption that the main thread
(the thread running the test) calls `future.cancel` always before the
callable finishes in 2 second. In reality, there's no guarantee
that CPU executes the main thread in a timely manner.
(This possibility is actually already written in the source code
comment)
Increasing the timeout value from 2 seconds to 60 seconds will
drastically reduce the likelihood of the failure.
=> test: increase timeout testCancelOuterFutureAfterStart to 60s

gax-java/gax-httpjson/src/test/java/com/google/api/gax/httpjson/HttpJsonDirectServerStreamingCallableTest.java
* increase timeout from 2s to 30s to reduce the chance of DEADLINE_EXCEEDED before the NOT_FOUND message is received
* keep separate low timeout for the testDeadlineExceededServerStreaming test
* remove mockService reset to speedup tests, as it's no longer necessary
Fixes: #1842.
=> test: fix flaky HttpJsonDirectServerStreamingCallableTest.testOnResponseError

showcase/README.md
This addition removes the trailing ANSI escape sequence (`\x1b[0m`) on the returned version.
This regex `\x1b\[[0-9;]*m` matches ANSI escape sequences.
=> chore: update dev guide to get version of gapic-showcase to install.

.github/workflows/create_additional_release_tag.yaml
The workflow to create additional tags when releasing is failing: https://github.com/googleapis/sdk-platform-java/actions/runs/7893005878/job/21540707818.
Delete the local tag before creating one.
=> chore: fix workflow to create additional tags

library_generation/model/gapic_inputs.py, library_generation/test/resources/misc/BUILD_comment_common_resources.bazel, library_generation/test/resources/misc/BUILD_comment_iam_policy.bazel, library_generation/test/resources/misc/BUILD_comment_locations.bazel, library_generation/test/resources/misc/BUILD_common_resources.bazel, library_generation/test/resources/misc/BUILD_iam_locations.bazel, library_generation/test/resources/misc/BUILD_iam_policy.bazel, library_generation/test/resources/misc/BUILD_locations.bazel, library_generation/test/resources/misc/BUILD_no_additional_protos.bazel, library_generation/test/resources/search_additional_protos/BUILD_common_resources.bazel, library_generation/test/resources/search_additional_protos/BUILD_iam_policy.bazel, library_generation/test/resources/search_additional_protos/BUILD_locations.bazel, library_generation/test/unit_tests.py
In this PR:
- Ignore comment (leading with `#`) when parsing BUILD.bazel
- Add unit tests
Context: There's a [BUILD](https://github.com/googleapis/googleapis/blob/master/google/cloud/resourcemanager/v3/BUILD.bazel#L52C10-L52C50) in googleapis has common_resources.proto comment out. We need to adjust the regex pattern to adjust this case.
=> fix: ignore comment in BUILD

library_generation/owlbot/bin/entrypoint.sh
In this PR:
- Suppress logs of download progress when running `fmt` plugin.
=> chore: suppress download progress

gax-java/gax/src/test/java/com/google/api/gax/batching/BatcherImplTest.java
This is the follow-up of a pull request #2285, where we wanted to
catch any flaky test failure with logging, just in case the test
failed again.
https://github.com/googleapis/sdk-platform-java/pull/2285/files#r1416300479
It turned out that the fix worked well. We don't observe the test
failures any more. Therefore turning off the excessive logging.
=> test: do not show unnecessary BatcherImplTest logging

.cloudbuild/library_generation/library_generation.Dockerfile
From https://github.com/diegomarquezp/google-cloud-java/actions/runs/8178920720/job/22363860250
```
+ /usr/local/lib/python3.11/site-packages/library_generation/owlbot/bin/write_clirr_ignore.sh /usr/local/lib/python3.11/site-packages/library_generation
/workspace/google-cloud-java/java-datastore/proto-google-cloud-datastore-v1 /workspace/google-cloud-java/java-datastore
/workspace/google-cloud-java/java-datastore/proto-google-cloud-datastore-v1/src/main/java /workspace/google-cloud-java/java-datastore/proto-google-cloud-datastore-v1 /workspace/google-cloud-java/java-datastore
/usr/local/lib/python3.11/site-packages/library_generation/owlbot/bin/write_clirr_ignore.sh: line 29: jq: command not found
Library postprocessing failed
Error: Process completed with exit code 1.
```
This PR adds jq …
=> chore: add `jq` to hermetic build image definition

renovate.json
Fixes https://github.com/googleapis/sdk-platform-java/issues/2511. Verified with https://github.com/mpeddada1/forking-renovate-repro/pull/15
The Dependency Dashboard logs were shows the status of java-shared-config as being `skipReason:disabled`. Explicitly setting `enabled` to `true` resolves this issue. 
```
{
"datasource": "maven",
"depName": "com.google.cloud:google-cloud-shared-config",
"currentValue": "1.7.1",
"fileReplacePosition": 873,
"registryUrls": [
"https://repo.maven.apache.org/maven2",
"https://maven-central.storage-download.googleapis.com/maven2",
"https://repo1.maven.org/maven2",
"https://maven-central.storage-download.googleapis.com/maven2/"
],
"depType": "parent-root",
"updates": [],
"packageName": "com.google.cloud:google-cloud-shared-config",
"skipReason": "disabled" …
```
=> chore: fix renovate bot configs for java-shared-config updates

library_generation/generate_pr_description.py, library_generation/test/integration_tests.py
In this PR:
- Write PR description into a file which lives the same directory with the configuration.
Context:
After #2531, we can generate pull request description from generation config and a baseline commit.
However, the return value (string) can not be retrieved when running in docker environment. Therefore, write the description to a file. Put multi-line description to a file also helps editing the pr body ([link](https://github.com/cli/cli/issues/595#issuecomment-608372734)).
=> chore: write description to a file

java-common-protos/.OwlBot.yaml
This PR adds shopping and chat common protos. 
Once this is released and made it into google-cloud-java, we need to remove the corresponding modules in google-cloud-java, otherwise there would be compilation errors regarding duplicated classes. e.g. This [folder](https://github.com/googleapis/google-cloud-java/tree/main/java-shopping-merchant-reports/proto-google-shopping-merchant-reports-v1beta/src/main/java/com/google/shopping/type) need to be removed.
In addition, hardcoded proto references in https://github.com/googleapis/sdk-platform-java/pull/2414 in hermetic build scripts need to be removed as well.
Fixes #2018
=> feat: Add shopping and chat common protos.

library_generation/generate_pr_description.py, library_generation/test/resources/integration/google-cloud-java/generation_config.yaml, library_generation/test/resources/integration/google-cloud-java/pr-description-golden.txt
In this PR:
- When generate pull request description, do not include a commit that only changes `BUILD.bazel`.
=> feat: skip build only commit

library_generation/generate_library.sh
After #2553 is merged, we do not need to add `google/shopping/type/types.proto` in `generate_library.sh` as a special case.
=> chore: remove `google/shopping/type/types.proto` when generating shopping APIs

library_generation/generate_pr_description.py, library_generation/test/resources/integration/google-cloud-java/pr-description-golden.txt, library_generation/test/resources/integration/java-bigtable/pr-description-golden.txt
In this PR:
- Remove generator version in PR description
We plan to include generator update only when the version is updated, rather than including it in every PR.
=> chore: remove generator in PR description

library_generation/generate_pr_description.py, library_generation/test/resources/integration/google-cloud-java/pr-description-golden.txt, library_generation/test/resources/integration/java-bigtable/pr-description-golden.txt, library_generation/test/utils/commit_message_formatter_unit_tests.py, library_generation/utils/commit_message_formatter.py
In this PR:
- Wrap commit message with `BEGIN_COMMIT_OVERRIDE` and `BEGIN_COMMIT_OVERRIDE`.
Context: we found out that the commit messages in https://github.com/googleapis/google-cloud-java/pull/10529 didn't appear in the release notes. @chingor13 pointed out that we should wrap commit messages with `BEGIN_COMMIT_OVERRIDE` and `BEGIN_COMMIT_OVERRIDE` so that release-please can pick them up from a merged PR.
=> chore: modify pr description

library_generation/postprocess_library.sh
In this PR we fix the `deep-remove` and `deep-preserve` regexes in `.OwlBot.yaml` files in the monorepo by creating a temporary `.OwlBot.hermetic.yaml` with the corrected paths.
Because the paths specified in `deep-remove-regex` and `deep-preserve-regex` [start from the library name](https://github.com/googleapis/google-cloud-java/blob/14f7146c98fdf03de2f113215e03347a21e83f9a/java-alloydb/.OwlBot.yaml#L17), so if we run `copy-code` from inside a library, these regexes won't match any files.
We don't need to correct the library path because `copy-code` sends the files from `googleapis-gen` (or our built temp folder in our case) to the `owl-bot-staging` folder. These regexes don't deal with the monorepo, they deal with the source repo, which for our case is the temp folder we build after …
=> fix: correct deep-remove and deep-preserve regexes

library_generation/templates/owlbot.py.j2, library_generation/test/resources/goldens/owlbot-golden.py
In this PR:
- Remove the last comma in the `java.common_templates` method in `owlbot.py`
This will align with `java.common_templates` generated by google-cloud-java's `generation/update_owlbot_postprocessor_config.sh`
=> chore: remove ending comma in `owlbot.py`

library_generation/generate_repo.py
In todays's nightly generation job ([log](https://github.com/googleapis/google-cloud-java/actions/runs/8457767424/job/23170489394)), no actual generation is done.
I think this is because `main` method has been removed by #2598.
=> fix: add main to `generate_repo.py`

.github/workflows/create_additional_release_tag.yaml
After b/328660418 is resolved, we don't need the `unmanaged-dependencies-check-latest` tag.
=> chore: remove tag of unmanaged dependency check

library_generation/generate_pr_description.py, library_generation/test/generate_pr_description_unit_tests.py
In this PR:
- Do not generate pr_description.txt if googleapis commit is the same in baseline config and current config.
=> chore: do not generate pr description if two commits are same

gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/TimeoutTest.java
This change removes duplicate calls to setters in `gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/TimeoutTest.java`.
Fixes #2635 ☕️
=> fix: remove duplicated calls to AutoValue builders

gax-java/gax/src/main/resources/META-INF/native-image/com.google.api/gax/native-image.properties
For https://github.com/googleapis/sdk-platform-java/issues/2600
Background for removing these to configs:
(1) Build time initialization of SLF4J's LoggerFactory class
The configuration was added in https://github.com/googleapis/java-core/pull/685 to address the following failure in java-bigquerystorage:
```
Error: Classes that should be initialized at run time got initialized during image building:
org.slf4j.LoggerFactory was unintentionally initialized at build time. To see why org.slf4j.LoggerFactory got initialized use --trace-class-initialization=org.slf4j.LoggerFactory
```
However, since this [change](https://github.com/googleapis/sdk-platform-java/pull/1290) to initialize netty 4 at run-time, this configuration has no longer been needed. Verified locally that running ` mvn clean …
=> fix: remove unnecessary slf4j and AbstractGoogleClientRequest native image configs

gapic-generator-java-pom-parent/pom.xml, gax-java/pom.xml, java-shared-dependencies/third-party-dependencies/pom.xml
Following Tomo's suggestion in https://github.com/googleapis/sdk-platform-java/pull/2602#issuecomment-2062138924
Shared-Dep's third_party parent is gapic-generator-java-pom-parent. threetenbp's + otel version is defined in gapic-generator-java-pom-parent
=> chore: shared-deps third party's parent is generator-pom-parent

renovate.json
Same as #2618, will revert when Beam is released.
current version is v3.25.3 updated in https://github.com/googleapis/sdk-platform-java/pull/2491
=> chore: disable renovate for protobuf dependencies

WORKSPACE, showcase/gapic-showcase/pom.xml, showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/EchoClient.java, showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/package-info.java, showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/GrpcEchoStub.java, showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/HttpJsonEchoStub.java, showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoOuterClass.java, showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoRequest.java, showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoRequestOrBuilder.java, showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoResponse.java, showcase/proto-gapic-showcase-v1beta1/src/main/java/com/google/showcase/v1beta1/EchoResponseOrBuilder.java, showcase/proto-gapic-showcase-v1beta1/src/main/proto/schema/google/showcase/v1beta1/echo.proto
update gapic-showcase so that we can pickup changes in https://github.com/googleapis/gapic-showcase/pull/1484
Steps: 
1) Updated the gapic-showcase version in `gapic-showcase/pom.xml` to 0.33.0
2) Ran `mvn compile -P update`
=> deps: update gapic-showcase to v0.33.0

gax-java/gax/pom.xml
Mark opentelemetry-api as an optional dependency per [internal discussion](https://docs.google.com/document/d/1mhuUD6yZfMJHdOvmHwYM-pYnjMO_t7DwCGKJmSPYE5k/edit?resourcekey=0-fLgYpys-qO89rF_kwOejug&tab=t.0#heading=h.9y4fw0m64snt). Both [java-bigtable](https://github.com/googleapis/java-bigtable/blob/3f37d8da8b51a3fea56d1c462b9500ee2c244973/google-cloud-bigtable/pom.xml#L222) and [java-spanner ](https://github.com/googleapis/java-spanner/blob/6f522dd73123b3de8399902e28d755a5496829c3/google-cloud-spanner/pom.xml#L253)already declare this dependency in their poms, so this is not a breaking change.
=> deps: Make opentelemetry-api an optional dependency.

library_generation/test/integration_tests.py
In this PR:
- Show file diff in integration tests.
I manually edited a line in test branch and this is the test result:
```
Difference in google-cloud-alloydb/src/main/java/com/google/cloud/alloydb/v1/AlloyDBAdminClient.java:
--- 
+++ 
@@ -774,7 +774,7 @@
/**
* Constructs an instance of AlloyDBAdminClient, using the given stub for making calls. This is
-   * for advanced usage - prefer using create(AlloyDBAdminSettings) - manually added.
+   * for advanced usage - prefer using create(AlloyDBAdminSettings).
*/
public static final AlloyDBAdminClient create(AlloyDBAdminStub stub) {
return new AlloyDBAdminClient(stub);
Error: Process completed with exit code 1.
```
=> chore: show difference in integration test

java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/DependencyAnalyzer.java, java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/external/DepsDevClient.java, java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/AnalysisResult.java, java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/License.java, java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/LicenseCategory.java, java-shared-dependencies/dependency-analyzer/src/main/java/com/google/cloud/model/VersionKey.java, java-shared-dependencies/dependency-analyzer/src/test/java/com/google/cloud/external/DepsDevClientTest.java, java-shared-dependencies/dependency-analyzer/src/test/java/com/google/cloud/model/AnalysisResultTest.java, java-shared-dependencies/dependency-analyzer/src/test/java/com/google/cloud/model/LicenseTest.java
In this PR:
- Generate package information report for package that has no non-compliant licenses and security vulnerabilities.
- Encode version using `URLEncoder`. The version may contain special characters that needs to be encoded before sending to deps.dev, e.g., [9+181-r4173-1](https://deps.dev/maven/com.google.errorprone%3Ajavac-shaded/9%2B181-r4173-1).
An example of the report:
```
Licenses: [Apache-2.0]
Vulnerabilities: None.
Checked in [deps.dev query](https://api.deps.dev/v3/query?versionKey.system=MAVEN&versionKey.name=io.opentelemetry:opentelemetry-api&versionKey.version=1.37.0)
Licenses: [Apache-2.0]
Vulnerabilities: None.
Checked in [deps.dev query](https://api.deps.dev/v3/query?versionKey.system=MAVEN&versionKey.name=io.opentelemetry:opentelemetry-context&versionKey.version=1. …
```
=> chore: update package information report

gax-java/gax_java.bzl
`load()` statements are being added to prepare for moving the rules out of Bazel and into `rules_java`
Fixes https://github.com/googleapis/sdk-platform-java/issues/2683
=> chore: Add `load()`s for the Bazel builtin java rules

library_generation/README.md, library_generation/generate_composed_library.py, library_generation/generate_library.sh, library_generation/model/generation_config.py, library_generation/test/generate_library_unit_tests.sh, library_generation/test/generate_pr_description_unit_tests.py, library_generation/test/model/config_change_unit_tests.py, library_generation/test/model/generation_config_unit_test.py, library_generation/test/resources/integration/google-cloud-java/baseline_generation_config.yaml, library_generation/test/resources/integration/google-cloud-java/current_generation_config.yaml, library_generation/test/resources/integration/java-bigtable/generation_config.yaml, library_generation/test/resources/test-config/generation_config.yaml, library_generation/test/utils/generation_config_comparator_unit_tests.py, library_generation/utils/utilities.sh
In this PR:
- Change `protobuf_version` to `protoc_version`.
=> chore: change protobuf_version to protoc_version

.github/workflows/nightly.yaml
This is step does `mvn install` and is not only unit tests.
=> chore: fix confusing step name

gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/common/AbstractServiceStubSettingsClassComposer.java, gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/ServiceStubSettingsClassComposerTest.java, gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/ApiVersionTestingStubSettings.golden, gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/EchoStubSettings.golden, gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpc/goldens/samples/servicesettings/stub/SyncEchoWithVersionMethod.golden, gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/ServiceStubSettingsClassComposerTest.java, gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/grpcrest/goldens/EchoStubSettings.golden, gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/rest/ServiceStubSettingsClassComposerTest.java, gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/rest/goldens/HttpJsonApiVersionTestingStubSettings.golden, gapic-generator-java/src/test/java/com/google/api/generator/gapic/composer/rest/goldens/HttpJsonEchoStubSettings.golden, gapic-generator-java/src/test/java/com/google/api/generator/gapic/protoparser/ParserTest.java, gapic-generator-java/src/test/java/com/google/api/generator/test/protoloader/RestTestProtoLoader.java, gapic-generator-java/src/test/java/com/google/api/generator/test/protoloader/TestProtoLoader.java, gapic-generator-java/src/test/proto/api_version_testing.proto, gapic-generator-java/src/test/proto/echo_grpcrest.proto, gax-java/gax/src/main/java/com/google/api/gax/rpc/ApiClientHeaderProvider.java, gax-java/gax/src/test/java/com/google/api/gax/rpc/ApiClientHeaderProviderTest.java, showcase/gapic-showcase/src/main/java/com/google/showcase/v1beta1/stub/EchoStubSettings.java
This is part 2, following changes in https://github.com/googleapis/sdk-platform-java/pull/2630
Changes in this pr:
- ApiClientHeaderProvider: add key and token setter for api version.
- AbstractServiceStubSettingsClassComposer: add logic to set this header when api-version is present (not null or empty)
- Unit and golden tests to reflect above changes. (This includeds a few new golden files created for tests based on the dedicated proto created in #2630)
This pr does not include gapic-showcased testing for now.
---
manual tested with [gapic-showcase](https://github.com/googleapis/gapic-showcase) v0.33.0
steps: 
- Use gapic-showcase v0.33.0 (which includes update in 1484)
- use `gapic-showcase run -v` which prints the request header
- From showcase folder, run `mvn verify -P …
=> feat: Update Gapic generator and Gax to emit api-versioning via header

library_generation/cli/entry_point.py, library_generation/model/generation_config.py, library_generation/test/cli/entry_point_unit_tests.py, library_generation/test/model/generation_config_unit_test.py, library_generation/test/resources/test-config/config_without_gapics_key.yaml, library_generation/test/resources/test-config/config_without_gapics_value.yaml, library_generation/test/resources/test-config/config_without_library_value.yaml, library_generation/test/resources/test-config/generation_config_with_duplicate_library_name.yaml, library_generation/test/utilities_unit_tests.py, library_generation/utils/utilities.py
In this PR:
- Add a CLI tool to validate generation config.
Downstream libraries, e.g., google-cloud-java, can write a workflow job like:
```
docker run ...
python /src/cli/entry_point.py \
validate-generation-config \
--generation-config-path=path/to/generation_config.yaml
```
=> feat: add a CLI tool to validate generation configuration 

library_generation/cli/entry_point.py
In this PR:
- Add a log when the config validation succeeds.
Context: I tested the checker in [here](https://github.com/googleapis/google-cloud-java/actions/runs/8884272073/job/24392990025?pr=10761). It will be good if the checker emit a log when the check passed.
=> chore: add a log in config checker

gax-java/gax/src/main/java/com/google/api/gax/core/InstantiatingExecutorProvider.java
Fixes https://github.com/googleapis/sdk-platform-java/issues/2680
=> fix: Log HttpJson's async thread pool core size

.github/workflows/verify_library_generation.yaml
In this PR:
- Skip running library generation test after merging a pull request. Related error: 
```
Run set -ex
set -ex
git checkout "${base_ref}"
git checkout "${head_ref}"
changed_directories="$(git diff --name-only ${base_ref} ${head_ref})"
if [[ ${changed_directories} =~ "library_generation/" ]]; then
echo "should_run=true" >> $GITHUB_OUTPUT
else
echo "should_run=false" >> $GITHUB_OUTPUT
fi
shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
env:
base_ref: 
head_ref: 
+ git checkout ''
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
```
Full log: https://github.com/googleapis/sdk-platform-java/actions/runs/8913958564/job/24480528068
=> chore: skip library generation tests after merging a pull request

.github/workflows/verify_library_generation.yaml
In this PR:
- Remove `on.push` trigger so that the workflow doesn't run against a specific branch.
Official doc: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushbranchestagsbranches-ignoretags-ignore
=> chore: do not run workflow on push

.github/workflows/verify_library_generation.yaml, library_generation/test/integration_tests.py
https://github.com/googleapis/sdk-platform-java/pull/2716 didn't quite fix what it should have. Follow up to fix the error:
```
Previous HEAD position was e54601fce Merge 30c7c5b4f9825c14458d6ef31e0b3e3fccbb4207 into 5d4567f883b1e29cd5f299d392c5a809b451aa18
Switched to a new branch 'main'
branch 'main' set up to track 'origin/main'.
+ git fetch --no-tags --prune origin +main:refs/remotes/origin/main
From https://github.com/googleapis/sdk-platform-java
- [deleted]             (none)     -> origin/main
+ git checkout renovate/markupsafe-2.x
error: pathspec 'renovate/markupsafe-2.x' did not match any file(s) known to git
```
=> chore: follow up fix to verify_library_generation

library_generation/README.md, library_generation/owlbot/bin/entrypoint.sh, library_generation/owlbot/src/fix-poms.py, library_generation/owlbot/src/fix_poms.py, library_generation/setup.py, library_generation/test/compare_poms.py, library_generation/test/owlbot/fix_poms_unit_tests.py, library_generation/test/resources/test-owlbot/java-admanager/.repo-metadata.json, library_generation/test/resources/test-owlbot/java-admanager/ad-manager-bom/pom-golden.xml, library_generation/test/resources/test-owlbot/java-admanager/ad-manager/pom-golden.xml, library_generation/test/resources/test-owlbot/java-admanager/pom-golden.xml, library_generation/test/resources/test-owlbot/java-admanager/proto-ad-manager-v1/pom-golden.xml, library_generation/test/resources/test-owlbot/java-admanager/versions.txt
In this PR:
- Only append `.api.grpc` suffix to group id if the corresponding artifact id starts with `proto-` or `grpc-`.
We need to support `ad-manager`, which is the first artifact id doesn't start with `proto-`, `grpc-` and `google-`.
=> fix: only append `.api.grpc` suffix to group id if the artifact id starts with `proto-` or `grpc-`

.cloudbuild/graalvm/cloudbuild-test-a.yaml, .cloudbuild/graalvm/cloudbuild-test-b.yaml, .cloudbuild/graalvm/cloudbuild.yaml, .kokoro/presubmit/downstream-build.sh
Adds timestamps to the mvn build output, plus minor formatting for shorter lines / easier readability.
=> ci: add timestamps to graalvm's mvn setup commands

library_generation/test/utils/generation_config_comparator_unit_tests.py, library_generation/utils/generation_config_comparator.py
In this PR:
- Do not populate repo level change while removing library
Context: the [log](https://github.com/googleapis/google-cloud-java/actions/runs/8970167105/job/24633084853?pr=10782) shows that the script went a full generation when a library is removed from the generation config.
=> fix: do not populate repo level change while removing library

.cloudbuild/graalvm/cloudbuild-test-a-downstream-kms.yaml, .cloudbuild/graalvm/cloudbuild-test-a-downstream-kmsinventory.yaml, .cloudbuild/graalvm/cloudbuild-test-a.yaml, .cloudbuild/graalvm/cloudbuild-test-b-downstream-kms.yaml, .cloudbuild/graalvm/cloudbuild-test-b-downstream-kmsinventory.yaml, .cloudbuild/graalvm/cloudbuild-test-b.yaml
8m33s, 8m44s, 10m43s, 11m28s, 9m41s, 10m47s
These test times are all shorter than the ci / build (11) check, making these checks no longer the bottle neck.
=> ci: increase graalvm ci machine type

gapic-generator-java-bom/pom.xml, java-shared-dependencies/third-party-dependencies/pom.xml
Importing opentelemetry-bom in gapic-generator-java-bom (and thus Google Cloud Libraries BOM) wrongly implies that we (Google) publish the OpenTelemetry artifacts.
https://jlbp.dev/JLBP-15 states:
>  Your project's BOM should not include any of your dependencies on other libraries.
In this change, the opentelemetry-bom is declared in the third-party-dependencies BOM and thus will be excluded in the Google Cloud Libraries BOM, which does not import the third-party-dependencies BOM.
Related to b/338624813
=> fix: opentelemetry-bom to be in third-party-dependencies BOM

gax-java/gax/src/main/java/com/google/api/gax/rpc/ApiClientHeaderProvider.java, showcase/gapic-showcase/pom.xml, showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITApiVersionHeaders.java
This pr updates gapic-showcase version to 0.35.0 and adds showcase tests to verify behavior of api version headers being emitted (changes in #2630 and #2671).
=> test: add showcase test for api-version

library_generation/requirements.txt
In this PR:
- Remove a redundant dependency, `platformdirs`.
=> chore: remove platformdirs

library_generation/generate_library.sh
In this PR:
- Exclude `google/cloud/visionai/v1/prediction.proto` until cl/631529749 is submitted
Test generated client in https://github.com/googleapis/google-cloud-java/pull/10845.
=> chore: exclude `prediction.proto`

renovate.json
In this PR:
- Exclude `google-api-client-bom` from google api dependencies group
=> chore: exclude `google-api-client-bom` from google api dependencies group

.github/workflows/ci.yaml, .github/workflows/sonar.yaml, gapic-generator-java-pom-parent/pom.xml, gax-java/dependencies.properties, gax-java/gax/BUILD.bazel, gax-java/gax/pom.xml, gax-java/gax/src/test/java/com/google/api/gax/rpc/EndpointContextTest.java, gax-java/pom.xml
=> chore: add junit5 extension to setup environment variable

library_generation/generate_pr_description.py, library_generation/test/generate_pr_description_unit_tests.py
In this PR:
- Do not generate `pr_description.txt` if no qualified commit found between two googleapis commit.
=> chore: do not create pr description without qualified commit

api-common-java/src/test/java/com/google/api/pathtemplate/PathTemplateTest.java
Fix #2776 and #2778.
The failing tests are in the same file, thus combine into one pull request.
=> chore: fix failing unit tests in `PathTemplateTest`

gax-java/gax/src/main/java/com/google/api/gax/tracing/OpenTelemetryMetricsRecorder.java
This can mitigate the ask to expose `Meter` as a constructor parameter in `OpenTelemetryMetricsRecorder`. Since `Meter` usually represents the libary that does the instrumentation, we can not expose it. However, we can expose the meter name as a public String, so that users of gax can create Otel views more easily with it.
=> fix: Expose Gax meter name

gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
The static field `systemProductName` should only be used for testing purposes. In production environment, the logic of checking `isOnComputeEngine` should be exactly the same as before https://github.com/googleapis/sdk-platform-java/pull/2614.
Fixes b/346215860
=> fix: Move the logic of getting systemProductName from static block to static method

library_generation/owlbot/templates/java_library/.github/CODEOWNERS, library_generation/owlbot/templates/java_library/.github/ISSUE_TEMPLATE/bug_report.md, library_generation/owlbot/templates/java_library/.github/ISSUE_TEMPLATE/feature_request.md, library_generation/owlbot/templates/java_library/.github/ISSUE_TEMPLATE/support_request.md, library_generation/owlbot/templates/java_library/.github/PULL_REQUEST_TEMPLATE.md, library_generation/owlbot/templates/java_library/.github/auto-label.yaml, library_generation/owlbot/templates/java_library/.github/blunderbuss.yml, library_generation/owlbot/templates/java_library/.github/dependabot.yml, library_generation/owlbot/templates/java_library/.github/generated-files-bot.yml, library_generation/owlbot/templates/java_library/.github/release-please.yml, library_generation/owlbot/templates/java_library/.github/release-trigger.yml, library_generation/owlbot/templates/java_library/.github/sync-repo-settings.yaml, library_generation/owlbot/templates/java_library/.github/workflows/approve-readme.yaml, library_generation/owlbot/templates/java_library/.github/workflows/ci.yaml, library_generation/owlbot/templates/java_library/.github/workflows/renovate_config_check.yaml, library_generation/owlbot/templates/java_library/.github/workflows/samples.yaml, library_generation/owlbot/templates/java_library/.kokoro/build.sh, library_generation/owlbot/templates/java_library/.kokoro/common.cfg, library_generation/owlbot/templates/java_library/.kokoro/continuous.cfg, library_generation/owlbot/templates/java_library/.kokoro/presubmit.cfg, library_generation/owlbot/templates/java_library/.kokoro/trampoline.sh
In this PR we add the `.github` and `.kokoro` folders to
`library_generation/owlbot/templates/java_library` in order to enable
the hermetic build workflows in HW libraries.
The templates come from https://github.com/googleapis/synthtool/commit/dae1282201b64e4da3ad512632cb4dda70a832a1
**The hermetic build templates will come in a separate PR**
=> chore: add HW repo templates

library_generation/generate_composed_library.py, library_generation/model/generation_config.py, library_generation/model/library_config.py, library_generation/test/resources/goldens/.repo-metadata-monorepo-golden.json, library_generation/test/resources/goldens/.repo-metadata-non-monorepo-golden.json, library_generation/test/resources/goldens/.repo-metadata-proto-only-golden.json, library_generation/test/utilities_unit_tests.py, library_generation/utils/utilities.py
This PR introduces a couple of new keys in the repo-metadata.json [model](https://github.com/googleapis/sdk-platform-java/blob/main/library_generation/model/library_config.py).
* `min_java_version`, as seen in [pubsublite](https://github.com/googleapis/java-pubsublite/blob/11c6540e2dec642492f5bd324ee810ca037d5a86/.repo-metadata.json#L11), [spanner](https://github.com/googleapis/java-spanner/blob/9deb34846b57e238642b6aa13f3107b2204cf969/.repo-metadata.json#L10) and others.
* `recommended_package`, as seen in [spanner](https://github.com/googleapis/java-spanner/blob/9deb34846b57e238642b6aa13f3107b2204cf969/.repo-metadata.json#L20), [storage](https://github.com/googleapis/java-storage/blob/87bf7371b6c4300b0f306ca36d1918d52adf721b/.repo-metadata.json#L19) and others
This constitutes an effort …
=> chore: adjust repo-metadata generation to fit existing files in HW repos

.cloudbuild/library_generation/cloudbuild-library-generation-push.yaml, release-please-config.json
So far, the Release Please config did not consider `.cloudbuild/library_generation/cloudbuild-library-generation-push.yaml` to update the tags.
This PR fixes this and also updates the image tag to the current one (2.42.0).
=> fix: restore hermetic build image publication

.cloudbuild/library_generation/cloudbuild-library-generation-push.yaml
This is a follow up of https://github.com/googleapis/sdk-platform-java/pull/2952
=> chore: restore hermetic image tag to current SNAPSHOT

gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
Fixes https://github.com/googleapis/sdk-platform-java/issues/2852
Result of manually invoked nightly run: https://github.com/googleapis/sdk-platform-java/actions/runs/9782209009
=> chore: Fix flaky InstantiatingGrpcChannelProviderTest on Mac

library_generation/model/library_config.py
Fix: https://github.com/googleapis/sdk-platform-java/security/code-scanning/1
=> chore: use sha256 in hashing

renovate.json
Reverts googleapis/sdk-platform-java#2618 now that https://github.com/apache/beam/releases/tag/v2.57.0 is out
=> chore: revert disable renovate for grpc and guava versions

renovate.json
Reverts googleapis/sdk-platform-java#2666 now that https://github.com/apache/beam/releases/tag/v2.57.0 is out
=> chore: Revert disable renovate for protobuf dependencies

gax-java/gax/src/main/java/com/google/api/gax/tracing/ApiTracer.java, gax-java/gax/src/main/java/com/google/api/gax/tracing/BaseApiTracer.java
Follow up of https://github.com/googleapis/sdk-platform-java/pull/3016
On `bigtable` and `spanner`:
Thanks @blakeli0 and @lqiu96 for the directions.
=> chore: move the `attemptFailed` logic from BaseApiTracer to ApiTracer

renovate.json
Context: https://github.com/googleapis/sdk-platform-java/pull/3033/files
This [requirement.txt](https://github.com/googleapis/sdk-platform-java/blob/e8deeaf226149d2ae6f8424d7f738273d799dcde/library_generation/requirements.txt#L1-L6) is auto generated and should not be updated by renovate bot.
=> chore: renovate bot should ignore requirement.txt

library_generation/README.md, library_generation/generate_composed_library.py, library_generation/model/generation_config.py, library_generation/model/library_config.py, library_generation/model/repo_config.py, library_generation/test/resources/goldens/.repo-metadata-custom-transport-golden.json, library_generation/test/utilities_unit_tests.py, library_generation/utils/utilities.py
This PR adds a new optional entry "`transport`" to `generation_config.yaml`.
The `transport` entry will only have effect in the postprocessing output (i.e. generated libraries will still have its transport inferred via BUILD.bazel). The main output file affected by this is `.repo-metadata.json` and its derived files (e.g. README.md).
This addresses the [need to allow a custom transport for java-storage](https://github.com/googleapis/java-storage/pull/2619#discussion_r1662963790).
=> feat: add `transport` option to `generation_config.yaml`

.github/workflows/ci.yaml, gax-java/gax-grpc/pom.xml, gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java, gax-java/gax-grpc/src/test/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProviderTest.java
Fixes #2427
If `GOOGLE_CLOUD_ENABLE_DIRECT_PATH_XDS` is set in the environment aiming to enable Direct Path xDS in another client, we want to just warn the user that _if this is intended_, it can be a misconfiguration and that the gRPCLB Direct Path setting should be enabled as well.
As said in the context, we will _warn_ the user that it _could_ be a misconfiguration _if_ the env var setting was meant for the client in question. Other warn cases remain the same.
Due to the fact that part of the method in question is tested via a special env var test (not detected by SonarCloud), it will show as uncovered. See this screenshot for coverage of all tests combined
=> fix: improve warnings for Direct Path xDS set via env

gax-java/gax/src/main/java/com/google/api/gax/rpc/ErrorDetails.java, gax-java/gax/src/test/java/com/google/api/gax/rpc/ErrorDetailsTest.java
Because the google.rpc.Status.details is a google.protobuf.Any, it can contain any message. ErrorDetails conveniently unpacks the standard status message types from google/rpc/error_details.proto but some services provide their own error details types.
This new method allows unpacking those custom messages without deserializing the entire google.rpc.Status another time.
=> feat: update ErrorDetails to allow unpacking arbitrary messages

.github/scripts/hermetic_library_generation.sh, .github/workflows/hermetic_library_generation.yaml, generation_config.yaml
In this PR:
- remove the image tag in the hermetic code generation workflow.
=> chore: remove image tag in hermetic code generation workflow

gax-java/gax/src/main/java/com/google/api/gax/util/TimeConversionUtils.java, gax-java/gax/src/test/java/com/google/api/gax/util/TimeConversionUtilsTest.java
https://github.com/googleapis/sdk-platform-java/pull/1872#discussion_r1695864350
=> fix(gax): prevent truncation/overflow when converting time values

.github/workflows/downstream.yaml, .kokoro/presubmit/common.sh, .kokoro/presubmit/downstream-compatibility-spring.sh, .kokoro/presubmit/downstream-compatibility.sh
Fixes https://github.com/googleapis/sdk-platform-java/issues/2534
The check takes 2 minutes
=> test: add downstream check for spring-cloud-gcp

api-common-java/src/main/java/com/google/api/core/ApiFutureToListenableFuture.java, api-common-java/src/main/java/com/google/api/core/ListenableFutureToApiFuture.java, api-common-java/src/test/java/com/google/api/core/ApiFutureToListenableFutureTest.java, gax-java/gax/src/main/java/com/google/api/gax/retrying/BasicRetryingFuture.java, library_generation/owlbot/templates/java_library/README.md
Sometimes an operation can get stuck indefinitely. The underlying reasons can vary significantly:
- the underlying attempt rpc can get stuck due to a bug in grpc (ie https://github.com/grpc/grpc-java/pull/11026)
- the operation can get stuck in layers above gax: https://github.com/googleapis/java-bigtable/pull/1939
- or it can get stuck in gax itself (dont have a pointer handy)
Guava futures provide some observability for ListenableFutures, but in creating the custom ApiFutures in gax, we lose that functionality. This PR sprinkles a few to toString to allow callers to inspect the internal state of the operation. For example with these changes, the toString() of the future returned from bigtableDataClient.mutateRows() changes from
> TransformFuture@652ce654[status=PENDING, …
=> feat: add toString to futures returned by operations

.cloudbuild/library_generation/library_generation.Dockerfile
Release please is incorrectly updating [GRPC and NPM versions](https://github.com/googleapis/sdk-platform-java/compare/396fd063e3babc80a5e8c00d72ab1241ad3a1988..ad830a8275ad2fa3d97dfb24bf26eedd950c10ee) in the library generation Dockerfile. Correctly closing it now per [this comment](https://github.com/googleapis/release-please/blob/34abdd3b7e35bd6638cc5d4c34b8b1ab5bdd29c2/src/updaters/java/java-update.ts#L28-L32) in release-please.
=> chore: Correctly closing the release please config for gapic-generator-java in library generation Dockerfile

.github/workflows/ci.yaml, showcase/README.md, showcase/scripts/generate_showcase.sh
The recent changes in the hermetic library generation workflow make it necessary for the environment to have a well-known folder where the generator jar is assumed to be located.
This PR sets up the generator jar in such location when running showcase golden tests or using the `-Pupdate` profile.
More details in the [development guide](https://github.com/googleapis/sdk-platform-java/blob/main/library_generation/DEVELOPMENT.md#the-hermetic-builds-well-known-folder)
=> chore: make the showcase scripts to automatically prepare the generator jar

renovate.json
In this PR:
- Do not use renovate to update protobuf version in `gax-java/dependencies.properties`.
We need to make sure the protobuf version in `gax-java/dependency.properties` (used by the self-service client) is compatible with protoc/protobuf version defined in the generator. 
We'll manually change the version.
Verification:
```
export LOG_LEVEL=debug && npx --yes --package renovate -- renovate --platform=local
...
{
"datasource": "maven",
"depName": "com.google.protobuf:protobuf-bom",
"currentValue": "3.25.4",
"fileReplacePosition": 1523,
"registryUrls": [
"https://maven-central.storage-download.googleapis.com/maven2/",
"https://maven-central.storage-download.googleapis.com/maven2",
"https://repo1.maven.org/maven2",
"https://repo.maven.apache.org/maven2"
],
"depType": "import", …
```
=> chore: do not use renovate to update protobuf

library_generation/owlbot/templates/clirr/clirr-ignored-differences.xml.j2
Clirr is flagging a bunch of 7006 Method Return Type changed errors. The Protoc generated changes are source code compatible and should ignore these errors in our generated code.
See [this doc](https://docs.google.com/spreadsheets/d/1qEzUWLougtiqh0ocRaG4e8w12pr89o0T_tQvB6YDStE/edit?pli=1&gid=0#gid=0) for more information. After adding all the Clirr checks exemptions in this PR to the downstream handwritten libraries, we are no longer seeing an Clirr failures.
=> chore: Add Clirr exemptions for Protobuf 4.27.4 runtime

.github/scripts/hermetic_library_generation.sh
In this PR:
- Do not exit if there's no code change.
Context: we found an issue in bigtable (https://github.com/googleapis/java-bigtable/pull/2336) such that PR description is overwritten by subsequent commit due to config updates. However, the generation associated with that [commit](https://github.com/googleapis/java-bigtable/pull/2336/commits/b6e7e1d566c4f2364e3eb8f766fec31c396ded57) didn't have code change (because the code change is already committed) and exit early so the PR description is not changed back.
=> chore: do not exit early if there's no code change

gax-java/gax/src/main/java/com/google/api/gax/tracing/MetricsTracer.java, gax-java/gax/src/test/java/com/google/api/gax/tracing/MetricsTracerTest.java
This PR adds an overload for adding multiple attributes at once. 
Earlier the client had to call the `addAttributes` method in a loop to add each attributes. Below overload takes a map and add all the attributes at once
```
public void addAttributes(Map<String, String> attributes) {
this.attributes.putAll(attributes);
};
```
=> feat: Metrics tracer addAttribute map overload

library_generation/templates/root-pom.xml.j2, library_generation/test/resources/test_monorepo_postprocessing/pom-golden.xml
Issue discovered in https://github.com/googleapis/google-cloud-java/actions/runs/10908789692/job/30275696533?pr=11081
```
<plugin>
<groupId>org.apache.maven.plugins</groupId>
<artifactId>maven-deploy-plugin</artifactId>
-        <version>3.1.3</version>
+        <version>3.1.2</version>
<configuration>
<skip>true</skip>
</configuration>
```
=> chore: Update root pom.xml template to use maven deploy v3.1.3

.cloudbuild/library_generation/cloudbuild-library-generation-push.yaml
In this PR:
- Specify options.logging` in Cloud Build config.
The cloud build failed when pushing:
```
Error: Insufficient step blocks
on ../../modules/infra_cloud_build/cloud_build.tf line 32, in resource "google_cloudbuild_trigger" "triggers":
32:   build {
At least 1 "step" blocks are required.
Error: Insufficient step blocks
on ../../modules/infra_cloud_build/cloud_build.tf line 32, in resource "google_cloudbuild_trigger" "triggers":
32:   build {
At least 1 "step" blocks are required.
```
Try to resolve this issue following [this](https://yaqs.corp.google.com/eng/q/4648617514492755968#n1) answer in YAQS.
=> chore: specify `options.logging` in cloud build

.github/sync-repo-settings.yaml
In this PR:
- Update required check:
- `graalvm-presubmit-sdk-platform-java-a` changed to `graalvm-presubmit-sdk-platform-java-a (cloud-devrel-kokoro-resources)`
- `graalvm-presubmit-sdk-platform-java-b` changed to `graalvm-presubmit-sdk-platform-java-b (cloud-devrel-kokoro-resources)`
=> chore: update required check

gax-java/gax/src/main/java/com/google/api/gax/rpc/internal/QuotaProjectIdHidingCredentials.java, gax-java/gax/src/test/java/com/google/api/gax/rpc/internal/QuotaProjectIdHidingCredentialsTest.java, showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITEndpointContext.java
=> fix: address incorrect universe domain validation when quota project id is set

gax-java/gax/src/main/java/com/google/api/gax/rpc/EndpointContext.java, gax-java/gax/src/test/java/com/google/api/gax/rpc/EndpointContextTest.java
See internal ticket b/349488459 for more info.
External info:
ComputeEngineCredentials in client libraries should not validate the universe domain. Validating the universe domain requires retrieving it from Metadata Server (MDS) and this will be temporarily disabled. 
For users that using client libraries, there will be no automatic call to MDS. For users that use the Credentials directly and manually call `ComputeEngineCredentials.getUniverseDomain()` and the universe domain is not explicitly set, it will make a call to MDS.
=> fix: Disable automatically retrieving Universe Domain from Metadata Server

gax-java/dependencies.properties
In previous https://github.com/googleapis/sdk-platform-java/pull/3258, missed to update version in gax-java/dependencies.properties
=> deps: update grpc dependencies to v1.67.1 in dependencies.properties

gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientHeaderSampleComposer.java, test/integration/goldens/apigeeconnect/samples/snippets/generated/main/java/com/google/cloud/apigeeconnect/v1/connectionservice/create/SyncCreateUseHttpJsonTransport.java, test/integration/goldens/asset/samples/snippets/generated/main/java/com/google/cloud/asset/v1/assetservice/create/SyncCreateUseHttpJsonTransport.java, test/integration/goldens/credentials/samples/snippets/generated/main/java/com/google/cloud/iam/credentials/v1/iamcredentials/create/SyncCreateUseHttpJsonTransport.java, test/integration/goldens/library/samples/snippets/generated/main/java/com/google/cloud/example/library/v1/libraryservice/create/SyncCreateUseHttpJsonTransport.java, test/integration/goldens/redis/samples/snippets/generated/main/java/com/google/cloud/redis/v1beta1/cloudredis/create/SyncCreateUseHttpJsonTransport.java
Fixes #1272
Tested by following instructions https://github.com/googleapis/sdk-platform-java/blob/main/gapic-generator-java/DEVELOPMENT.md#running-the-plugin-under-googleapis-with-local-gapic-generator-java
Ran 
```
bazelisk build //google/cloud/tpu/v2:google-cloud-tpu-v2-java
```
Generated samples, included new google-cloud-tpu-v2-java/samples/snippets/generated/com/google/cloud/tpu/v2/tpu/create/SyncCreateUseHttpJsonTransport.java
```
/*
* Copyright 2024 Google LLC
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*      https://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the …
```
=> fix: generator setting incorrect name/class for sample due to region tag (2nd attempt)

library_generation/cli/entry_point.py, library_generation/generate_repo.py, library_generation/test/cli/entry_point_unit_tests.py, library_generation/test/generate_repo_unit_tests.py, library_generation/test/resources/test-config/monorepo_baseline.yaml, library_generation/test/resources/test-config/monorepo_current.yaml
In this PR:
- Allow selectively generate libraries by adding `--library-names` to CLI.
We have a request of partially releasing google-cloud-java (b/331628538), which requires only generating a selective list of libraries.
This change allows a user-defined list of libraries to be generated even if the corresponding library configs are the same.
=> feat: selectively generate libraries

hermetic_build/library_generation/owlbot/bin/format_source.sh
In firestore, [RecordMapperTest.java](https://github.com/googleapis/java-firestore/blob/main/google-cloud-firestore/src/test-jdk17/java/com/google/cloud/firestore/RecordMapperTest.java) has Java Records which is incompatible with java formatter 1.7. 
This PR is to skip these files.
=> chore: skip formatting test-jdk17 files in firestore

.cloudbuild/library_generation/library_generation.Dockerfile, hermetic_build/library_generation/generate_library.sh, hermetic_build/library_generation/owlbot/bin/entrypoint.sh, hermetic_build/library_generation/tests/generate_library_unit_tests.py, hermetic_build/library_generation/tests/generate_library_unit_tests.sh
This PR switches the base images of all the Hermetic Build Docker image stages to publicly hosted docker images. 
The chosen images are mirrored by Airlock or are at least in process of incorporation. 
The choice of OS family is `alpine` for its security-oriented setup. 0 vulnerabilities were found in the public image scan reports ([example](https://hub.docker.com/layers/library/python/3.12.7-alpine3.20/images/sha256-f498302457ec11162f872199b92239c34e1fbcdbc391ff37a4959e820224aa98?context=explore)).
Although several optimizations are possible (see https://github.com/googleapis/sdk-platform-java/pull/3196 and its intermediate commits), this PR is restricted to the minimal changes to have a secure base image.
_Notes:_
* Since the UNIX tools are from FreeBSD, the `-d` flag in the `rm` …
=> chore(hermetic-build): use secure base image hosted in docker.com

.github/scripts/hermetic_library_generation.sh
https://github.com/googleapis/sdk-platform-java/pull/3271 renders this volume mapping unnecessary
=> chore: remove .m2 folder mapping in library generation workflow

.cloudbuild/graalvm/cloudbuild-test-a-downstream-kms.yaml, .cloudbuild/graalvm/cloudbuild-test-a-downstream-kmsinventory.yaml, .cloudbuild/graalvm/cloudbuild-test-a.yaml, .cloudbuild/graalvm/cloudbuild-test-b-downstream-kms.yaml, .cloudbuild/graalvm/cloudbuild-test-b-downstream-kmsinventory.yaml, .cloudbuild/graalvm/cloudbuild-test-b.yaml, .cloudbuild/graalvm/cloudbuild.yaml
Emulating solution in https://github.com/googleapis/java-shared-config/pull/921 to address the following error:
```
generic::invalid_argument: if 'build.service_account' is specified, the build must either (a) specify 'build.logs_bucket', (b) use the REGIONAL_USER_OWNED_BUCKET build.options.default_logs_bucket_behavior option, or (c) use either CLOUD_LOGGING_ONLY / NONE logging options
```
=> chore: add options.logging in cloud build trigger configs

.cloudbuild/library_generation/library_generation.Dockerfile, hermetic_build/library_generation/generate_library.sh
In this PR:
- Use `$RANDOM` (a shell variable that generates a random integer between 0 and 32767) to randomize temp output directory to support parallel generation.
=> chore: randomize temp output directory

.cloudbuild/library_generation/cloudbuild-library-generation-push-prod.yaml, .cloudbuild/library_generation/cloudbuild-library-generation-push.yaml, hermetic_build/DEVELOPMENT.md, hermetic_build/library_generation/tests/integration_tests.py
Fixes the following error:
[Docker Buildkit](https://docs.docker.com/build/buildkit/) is a more advanced version and more actively maintained. We confirmed locally that the error occurs with an old version of the docker builder and that it is fixed when using `DOCKER_BUILDKIT=1`
=> fix: use BuildKit instead of legacy builder to build the Hermetic Build images

hermetic_build/DEVELOPMENT.md
In this PR:
- Fix list num in `DEVELOPMENT.md`.
=> docs: fix list num

gax-java/gax/src/main/resources/META-INF/native-image/com.google.api/gax/native-image.properties
This should not vary from the runtime version for graalvm builds.
Tested: ran ITVersion tests in graalvm and printed out the header to see full value exists
=> fix: instantiate GaxProperties at build time to ensure we get the protobuf version

renovate.json
From https://github.com/googleapis/sdk-platform-java/pull/3372, the files `.cloudbuild/`directories aren't getting updated to use the latest java-shared-config version. From the [renovate logs](https://developer.mend.io/github/googleapis/sdk-platform-java/-/job/019327f8-a53b-767d-986c-4ddee5aacab7), there appears to be a difference in the registry urls used when looking up versions from maven central. 
Registry used when an update to the latest version is successfully made to `1.12.0`: 
```
{
"datasource": "maven",
"deps": [
{
"currentValue": "1.11.3",
"currentVersion": "1.11.3",
"datasource": "maven",
"depName": "com.google.cloud:google-cloud-shared-config",
"depType": "parent-root",
"fileReplacePosition": 702,
"fixedVersion": "1.11.3",
"isSingleVersion": true,
"packageName": …
```
=> chore: explicitly specify maven central location for renovate-bot version lookups

.github/sync-repo-settings.yaml
The GraalVM `cloud-devrel-kokoro-resources` checks are deprecated and will be removed soon in favor of java-graalvm-ci-prod checks.
=> chore: replace graalvm cloud-devrel-kokoro-resources with java-graalvm-ci-prod checks as required

hermetic_build/common/cli/get_changed_libraries.py, hermetic_build/common/model/config_change.py, hermetic_build/common/tests/model/config_change_unit_tests.py, hermetic_build/library_generation/cli/entry_point.py
In this PR:
- Return all library names as a comma-separated string if repo-level parameter changes.
Fix: #3381
=> fix: return all library names if repo-level parameter changes

hermetic_build/library_generation/tests/integration_tests.py
A verification step in go/offline-gen-design
=> chore: restrict internet access when running docker container in integration test

hermetic_build/README.md
Providing the same `/workspace` mount point for two volumes produces an error. Expected second mount point is `/workspace/apis`
=> docs: hermetic build README syntax fix

gax-java/dependencies.properties
Fixes https://github.com/googleapis/sdk-platform-java/issues/2428
The libraries released from api-common-java, java-common-protos, and java-iam are annotated in gax-java/dependencies.properties. These annotations allows the version values updated at the time of the release pull request, ensuring the generated Gradle files to have a proper dependency set.
=> chore: Release Please anontations for dependencies.properties

gax-java/dependencies.properties
Reverts googleapis/sdk-platform-java#3396
https://github.com/googleapis/sdk-platform-java/pull/3382#issuecomment-2499518297
> I think my pull request about Release Please annotation broke the CI checks for Release Please pull request.
The Bazel integration tests are not ready to use the locally installed artifacts in local Maven repository. GAX artifacts are fine because they are from Bazel package. I'll need to explore how to build them in https://github.com/googleapis/sdk-platform-java/commit/c8cb5ae1e4444d3f08dcc78e817e63d16f5e46d8#diff-8a0414289f48984fdac9f835e30a3c10f79ebef40088b9045c98665d2bddb6e3.
=> chore: reverting Release Please anontations for dependencies.properties

.cloudbuild/library_generation/library_generation.Dockerfile
In this PR:
- Include tag in base image.
Renovate Bot can update the image sha with a fixed tag ([doc](https://docs.renovatebot.com/docker/#digest-updating)). Without the tag, the updated image maybe not what we want.
=> chore: update base image to include tag

renovate.json
In this PR:
- Update owlbot-cli sha using renovate Bot ([doc](https://docs.renovatebot.com/modules/datasource/git-refs/)).
- Group image dependency updates to a single PR.
Debug output of renovate:
```
{
"deps": [
{
"depName": "repo-automation-bots",
"packageName": "https://github.com/googleapis/repo-automation-bots",
"currentValue": "main",
"currentDigest": "ab222d9a20bb27586433caedc70f049b7853db7e",
"datasource": "git-refs",
"replaceString": "OWLBOT_CLI_COMMITTISH=ab222d9a20bb27586433caedc70f049b7853db7e\n",
"updates": [
{
"updateType": "digest",
"newValue": "main",
"newDigest": "f66cf627d08d80cba67521e4db491c8e4e4ad315",
"branchName": "renovate/library-generation-image-updates"
}
],
"versioning": "semver-coerced",
"warnings": []
}
],
"matchStrings": …
```
=> chore: update owlbot cli sha using renovate

hermetic_build/release_note_generation/generate_pr_description.py
This adds a small hint on why it's likely that the release note generation workflow has failed due to the current branch having an older commit than the base branch. Rationale: requires understanding on why "hermetic code library generation" needs an "newer commit".
=> chore(hermetic-build): add hint for old commit hash error message

.github/scripts/hermetic_library_generation.sh, .github/scripts/update_googleapis_commit.sh, .github/workflows/update_googleapis_commit.yaml, hermetic_build/library_generation/owlbot/templates/java_library/.github/scripts/update_generation_config.sh, hermetic_build/library_generation/owlbot/templates/java_library/.github/workflows/update_generation_config.yaml
In this PR:
- Merge base branch to current branch before updating generation config.
Example run: https://github.com/googleapis/sdk-platform-java/actions/runs/12148752357/job/33877902009
=> chore: merge target branch before commit changes

gapic-generator-java-pom-parent/pom.xml, gax-java/gax/src/main/resources/META-INF/native-image/com.google.api/gax/native-image.properties
In case of protobuf 4+ need to include protobuf.Runtime in classes initialized at build time as that is used to determine protobuf version for graalvm.
Tested, temporarily bumped protobuf dependency to 4.28.1 without including Runtime in build time class list.  Received error:
```
Error: Classes that should be initialized at run time got initialized during image building:
com.google.protobuf.RuntimeVersion was unintentionally initialized at build time. To see why com.google.protobuf.RuntimeVersion got initialized use --trace-class-initialization=com.google.protobuf.RuntimeVersion
```
Updated to include Runtime and received passing [native showcase tests](https://github.com/googleapis/sdk-platform-java/actions/runs/12205342463/job/34052473211?pr=3438)
=> fix: graalvm missing build time class when using protobuf 4.x

java-shared-dependencies/third-party-dependencies/pom.xml
`dev.cel` 0.6.0+ brings in `protobuf-java` 4.28.x, which violates the no-downgrade rule since we still have [3.25.5](https://github.com/googleapis/sdk-platform-java/blob/f0236cfc102cf7ce06e1f733a4f40a50133d6b24/gapic-generator-java-pom-parent/pom.xml#L34) in this repo. This is not a major issue now as this dependency is not used yet in any downstream libraries, but we should downgrade it in case someone start using it. 
Separately, we should prevent this from happening in the future. See b/382754689 for potential future enhancements.
=> chore(deps): Downgrade dev.cel to 0.6.0

.github/workflows/downstream_protobuf_compatibility_check_nightly.yaml, .kokoro/nightly/downstream-protobuf-source-compatibility.sh, .kokoro/presubmit/downstream-protobuf-source-compatibility.sh
Set up a nightly CI job that tests Protobuf compatibility with downstream libraries. This step of the CI job is to test source compatibility.
The nightly job will check the compatibility of these libraries with the latest in Protobuf-Java 3.x and and 4.x. This job can be manually invoked with the Protobuf-Java versions as a list.
Future steps may introduce testing for binary compatibility.
=> ci: Add Downstream Protobuf-Java Source Compatibility Test

.github/scripts/update_googleapis_commit.sh, hermetic_build/library_generation/owlbot/templates/java_library/.github/scripts/update_generation_config.sh
Fix error when updating googleapis commit in a new branch.
```
fatal: unknown commit origin/generate-libraries-main
```
Example run: https://github.com/googleapis/sdk-platform-java/actions/runs/12286920597/job/34287983045
=> chore: push current branch to remote

hermetic_build/common/model/config_change.py
In this PR:
- Close repo after retrieving qualified commits.
This is an attempt to fix the following error ([log](https://github.com/googleapis/sdk-platform-java/actions/runs/12297693455/job/34319408952)):
```
Traceback (most recent call last):
File "/home/runner/work/sdk-platform-java/sdk-platform-java/hermetic_build/common/cli/get_changed_libraries.py", line 79, in <module>
main()
File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
return self.main(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/opt/hostedtoolcache/Python/3.12.7/x64/lib/python3.12/site-packages/click/core.py", …
```
=> chore: close repo after use

.github/workflows/downstream_protobuf_compatibility_check_nightly.yaml
Manually invoking with Protobuf-Java v4.26.0: https://github.com/googleapis/sdk-platform-java/actions/runs/12303211967
=> ci: Allow manual invocations for the Protobuf Source CI Job

.cloudbuild/library_generation/cloudbuild-library-generation-push-prod.yaml, .cloudbuild/library_generation/library_generation_airlock.Dockerfile
In this PR:
- Create a Dockerfile to use recommended OS image from Airlock.
b/384540059
=> chore: create a new Dockerfile

.github/sync-repo-settings.yaml
In this PR:
- Make the library generation integration test non-required.
This integration test will be removed in #3476 because we will use cloud build to run integration tests.
=> chore: make library generation IT non-required

hermetic_build/DEVELOPMENT.md
In this PR:
- Update development guide on the integration test.
=> docs: update development guide

java-common-protos/pom.xml, java-iam/pom.xml
The distributionManagement declared in the pom.xml files interferes the upload to GCP ArtifactRegistry because it tries to
upload artifacts to google.oss.sonatype.org even when you try to upload artifacts to GCP Artifact Registry (b/377328233#comment9).
The distributionManagement is already configured in the parent POM at
https://github.com/googleapis/java-shared-config/blob/6d526a3129f585338b14dab8f041e56dbaae4cd5/native-image-shared-config/pom.xml#L42. No need redeclare in these pom.xml files.
=> ci: remove unnecessary distributionManagement section

.github/workflows/ci.yaml
We also remove showcase-native because it's already being [tested in Cloud Build](https://www.google.com/url?q=https://github.com/googleapis/sdk-platform-java/blob/09d9708dec7ef82f7d269c6285a9588dec48ac5d/.cloudbuild/graalvm/cloudbuild-test-a.yaml%23L45&sa=D&source=docs&ust=1737144190134588&usg=AOvVaw0VT7f-vqeGpoSEAKvWhwg9)
=> chore: add jdk 23 job for showcase tests

.github/workflows/create_additional_release_tag.yaml
Scoping the permission to "contents: write" as per
- https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token#defining-access-for-the-github_token-permissions
- https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps?apiVersion=2022-11-28#repository-permissions-for-contents
=> ci: scoping the permission in create_additional_release_tag.yaml

gax-java/gax/src/main/resources/META-INF/native-image/com.google.api/gax/native-image.properties
Context: upgrading to GraalVM for JDK 23
Updating the image support in spring (https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3536) caused errors at analysis time solved by https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/3536/commits/d3f6185f6f1cbca811ca22d8abe3b4149ea7877a
Gax seems to be a better place for this kind of configs.
=> chore: adjust native-image config for spring-cloud-gcp

gax-java/gax/src/main/java/com/google/api/gax/rpc/StateCheckingResponseObserver.java
- Creating the string message prematurely puts a lot of strain on the JVM and GC, switch to the format version of `Preconditions.checkState` which only constructs the string if we throw the exception
- Issue: https://github.com/googleapis/sdk-platform-java/issues/3621
Thank you for opening a Pull Request! Before submitting your PR, please read our [contributing guidelines](https://github.com/googleapis/gapic-generator-java/blob/main/CONTRIBUTING.md). 
There are a few things you can do to make sure it goes smoothly:
Fixes #3621 ☕️
=> fix: Avoid creating message string prematurely for streaming calls

java-shared-dependencies/third-party-dependencies/pom.xml
Discovered as part of CI error in https://github.com/googleapis/google-cloud-java/pull/11426
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:3.5.0:enforce (enforce) on project google-cloud-notification: 
Error:  Rule 2: org.apache.maven.enforcer.rules.dependency.RequireUpperBoundDeps failed with message:
Error:  Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Error:  Require upper bound dependencies error for io.opentelemetry.semconv:opentelemetry-semconv:1.26.0-alpha paths to dependency are:
Error:  +-com.google.cloud:google-cloud-notification:0.176.0-beta-SNAPSHOT
Error:    +-com.google.cloud:google-cloud-storage:2.48.1
Error:      +-io.opentelemetry.semconv:opentelemetry-semconv:1.26.0-alpha (managed) <-- …
```
=> deps: Update opentelemetry-semconv to v1.29.0-alpha

gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/InstantiatingGrpcChannelProvider.java
@rockspore pointed out that the credential should be created from scratch because when using [toBuilder](https://github.com/googleapis/google-auth-library-java/blob/main/oauth2_http/java/com/google/auth/oauth2/ComputeEngineCredentials.java#L648) the underlying [access token is copied](https://github.com/googleapis/google-auth-library-java/blob/37d228410e99799e4a7be8650fe472ea712c9b4d/oauth2_http/java/com/google/auth/oauth2/OAuth2Credentials.java#L657). 
This was confirmed to be a bug with local testing which:
- deployed a GAE app, the app performs the below two actions sequentially
- create Google API client ( `allowedHardBoundAccessTokens` empty in GrpcProvider) and then ping the API, logs show the bearer token is used, obtained from making call to MDS
- create a Google API client  ( …
=> fix: S2A gRPC flow creates ComputeEngineCredentials via newBuilder.

.github/release-please.yml, .github/sync-repo-settings.yaml
=> feat: next release from main branch is 2.55.0

java-shared-dependencies/third-party-dependencies/pom.xml
This PR manually update arrow.version to v18.2.0
=> deps: update arrow.version to v18.2.0

.github/workflows/ci.yaml
observed in https://github.com/googleapis/sdk-platform-java/actions/runs/13730578942/job/38406676526?pr=3684
#3568 is merged.
=> chore: fix showcase clirr test after java-showcase renaming

.github/workflows/ci.yaml, java-showcase/README.md
https://github.com/googleapis/sdk-platform-java/pull/3568 updated the name `showcase` module to `java-showcase`. This PR updates a few places that still reference the old name to the new name.
=> chore: Update README and CI with the new name of showcase module.

java-showcase/gapic-showcase/pom.xml
This should be consistent with logback-core version. 1.3.x used because we test java 11+ in showcase
(typo in commit message, logback-classic is the one fixed)
=> chore: fix logback-classic version for testing

hermetic_build/library_generation/cli/entry_point.py
Adding alias to repository-path and api-definitions-path to be compatible with Librarian [options](https://github.com/googleapis/librarian/blob/d3f78d51103c523da60251e790c05a681331192a/internal/command/flags.go#L40) 
[click options](https://click.palletsprojects.com/en/stable/options/) allows alias directly, so this change is trivial and does not affect any existing usage cases.
=> chore: add aliases to generate command options.

.cloudbuild/graalvm/cloudbuild-test-a-downstream-kms.yaml, .cloudbuild/graalvm/cloudbuild-test-a-downstream-kmsinventory.yaml, .cloudbuild/graalvm/cloudbuild-test-a.yaml, .cloudbuild/graalvm/cloudbuild-test-b-downstream-kms.yaml, .cloudbuild/graalvm/cloudbuild-test-b-downstream-kmsinventory.yaml, .cloudbuild/graalvm/cloudbuild-test-b.yaml, .cloudbuild/graalvm/cloudbuild.yaml, gapic-generator-java-pom-parent/pom.xml, gax-java/gax-bom/pom.xml, java-shared-dependencies/first-party-dependencies/pom.xml, java-shared-dependencies/upper-bound-check/pom.xml, java-showcase/pom.xml, sdk-platform-java-config/pom.xml
RenovateBot is not creating a pull request for the version. I created this manually based on the previous pull request
https://github.com/googleapis/sdk-platform-java/pull/3655/files.
=> build(deps): update dependency com.google.cloud:google-cloud-shared-config to v1.15.0

java-shared-dependencies/third-party-dependencies/pom.xml
Reverts googleapis/sdk-platform-java#3675
Due to JDK11+ requirement in arrow 18.
https://arrow.apache.org/docs/18.0/java/install.html#java-compatibility
=> deps: revert "deps: update arrow.version to v18.2.0"

.github/workflows/java_sdk_logging.yaml, java-sdk-logging/license-checks.xml, java-sdk-logging/log4j2-extension/pom.xml, java-sdk-logging/logback-extension/pom.xml, java-sdk-logging/pom.xml
A follow up of #3706:
- Change the group id to `com.google.cloud` as it is a customer-facing library.
- Add clirr and enforcer check in CI.
=> chore: update logging mod

.cloudbuild/library_generation/library_generation.Dockerfile
This ties the google-java-format.jar version to the one [declared in java-shared-config](https://github.com/googleapis/java-shared-config/blob/a315cf154ffb2dfd77ff7ce9892f8bb8a40ec7cc/java-shared-config/pom.xml#L31)
The purpose is to later upgrade this version to avoid the old Guava dependency.
I moved the download step to ggj-build so the final image only copies artifacts from "build related" stages.
=> chore(hermetic-build): infer formatter version from java-shared-config property

gax-java/gax/pom.xml, gax-java/gax/src/main/resources/META-INF/native-image/com.google.api/gax/native-image.properties, gax-java/gax/src/test/resources/META-INF/native-image/com.google.api/gax/native-image.properties
Follow up from https://github.com/googleapis/sdk-platform-java/pull/3674
Context: Some local changes were not pushed to that PR before it was merged.
Main changes: 
- include `src/test/.../native-image.properties` in testlib jar
- include java-storage-nio related classes for initialization at build time
=> chore: include java-storage-nio changes in GraalVM config

.github/workflows/downstream_protobuf_compatibility_check_nightly.yaml, .kokoro/nightly/downstream-protobuf-binary-compatibility.sh, .kokoro/nightly/downstream-protobuf-source-compatibility.sh
Manual invocation: https://github.com/googleapis/sdk-platform-java/actions/runs/14038997003
=> ci: Use Java 8 for Linkage Checker

java-shared-dependencies/third-party-dependencies/pom.xml, java-shared-dependencies/upper-bound-check/pom.xml
=> chore: add httpcore5 and httpclient5 to third-party-dependencies

java-showcase/gapic-showcase/src/test/java/com/google/showcase/v1beta1/it/ITHttpAnnotation.java
Full context in [GraalVM 17 migration doc](https://docs.google.com/document/d/1bOeGtVFLsq5ts71If5pFXCvHIeNpbtBRvF6XQfavLZs/edit?tab=t.loipy7ydvwga)
Confirmation that this works: https://github.com/googleapis/java-shared-config/pull/1010/commits/95304940a769c3649875b8fa8a99f36e363580fb
JDK 17 `InputStreamReader` produces different bytes from JDK 18+. This affects `ITHttpAnnotation#testComplianceGroup` because of the way `compliance_suite.json` is parsed.
JDK 18 was released including commit [7fc854](https://github.com/openjdk/jdk/commit/7fc8540907e8e7483ad5729ea416167810aa8747) which enables usage of UTF-8 by default. Before this commit, each JVM will produce their own default Charset (_likely the reason we don't see this error in other CI setups using java 17_). As a confirmation, if we …
=> chore: prepare showcase for GraalVM for JDK 17

.github/workflows/verify_library_generation.yaml, hermetic_build/library_generation/owlbot/templates/java_library/.github/sync-repo-settings.yaml, hermetic_build/library_generation/owlbot/templates/java_library/.github/workflows/renovate_config_check.yaml, hermetic_build/library_generation/owlbot/templates/java_library/.github/workflows/update_generation_config.yaml, hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/build.sh, hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-a.cfg, hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-b.cfg, hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-c.cfg, hermetic_build/library_generation/setup.py
Context: [we will introduce a new GraalVM job](https://docs.google.com/document/d/1bOeGtVFLsq5ts71If5pFXCvHIeNpbtBRvF6XQfavLZs/edit?tab=t.dcjxhf429j6t#bookmark=id.3s7d4dj247hr) and will leverage the hermetic build templates to propagate this change to some of the repositories. Each PR will be followed with ad-hoc changes such as sync-repo-settings (the cannot be templated).
Demo PRs
* https://github.com/googleapis/java-bigtable/pull/2558
* https://github.com/googleapis/java-bigquerystorage/pull/2937
* https://github.com/googleapis/java-storage/pull/3029
* https://github.com/googleapis/java-datastore/pull/1816
* There are manual changes in `build.sh`. We will add this file to the [ignored files in owlbot.py](https://github.com/googleapis/java-datastore/blob/8ceb62b5182e30b4f771d6c1b586a22fb …
=> chore: introduce .kokoro templates for GraalVM jobs

.cloudbuild/graalvm/cloudbuild-test-a-downstream-kms.yaml, .cloudbuild/graalvm/cloudbuild-test-a-downstream-kmsinventory.yaml, .cloudbuild/graalvm/cloudbuild-test-a.yaml, .cloudbuild/graalvm/cloudbuild-test-b-downstream-kms.yaml, .cloudbuild/graalvm/cloudbuild-test-b-downstream-kmsinventory.yaml, .cloudbuild/graalvm/cloudbuild-test-b.yaml, .cloudbuild/graalvm/cloudbuild-test-c-downstream-kms.yaml, .cloudbuild/graalvm/cloudbuild-test-c-downstream-kmsinventory.yaml, .cloudbuild/graalvm/cloudbuild-test-c.yaml, .cloudbuild/graalvm/cloudbuild.yaml, .cloudbuild/graalvm/graalvm_c.Dockerfile, .github/release-please.yml, .github/sync-repo-settings.yaml, release-please-config.json
To be merged after cl/747626774
[context doc](https://docs.google.com/document/d/1bOeGtVFLsq5ts71If5pFXCvHIeNpbtBRvF6XQfavLZs/edit?tab=t.dcjxhf429j6t)
TL;DR: we are introducing testing infra for GraalVM for JDK 17
=> build: introduce testing infra for GraalVM "C"

hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-a.cfg, hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-c.cfg
Fixes a typo in two image references on templates.
=> fix(hermetic-build): use correct image name in templated graalvm jobs

.github/workflows/nightly.yaml
Additionally: we use cloud-java-bot to create the flakiness issues.
=> build: fix nightly failures in Java 11 jobs

hermetic_build/library_generation/owlbot/templates/java_library/.github/workflows/ci.yaml, hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/build.sh
Prepares downstream repos for the linter upgrade from java-shared-config (https://github.com/googleapis/java-shared-config/pull/1003)
=> fix: use spotify formatter in hermetic build templates

hermetic_build/library_generation/owlbot/templates/java_library/.github/workflows/samples.yaml
This follows from the linter upgrade done in https://github.com/googleapis/java-shared-config/pull/1003
=> fix: use java 17 in samples.yaml

.github/release-please.yml, hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-native-a.cfg, hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-native-b.cfg, hermetic_build/library_generation/owlbot/templates/java_library/.kokoro/presubmit/graalvm-native-c.cfg
This ensures the templates are up to date with the latest released version of sdk-platform-java-config
=> fix: keep native image templates up to date

renovate.json
Temporary solution while https://github.com/googleapis/sdk-platform-java/issues/3766 is not fixed
=> fix: subscribe Airlock Docker image definition to GRPC updates

java-shared-dependencies/dependency-convergence-check/pom.xml, java-shared-dependencies/unmanaged-dependency-check/pom.xml
=> deps: Update maven-shared-utils to v3.2.1

gax-java/gax/src/main/java/com/google/api/gax/rpc/ClientContext.java, gax-java/gax/src/test/java/com/google/api/gax/rpc/ClientContextTest.java
Temporary fix to only plumb the mtlsEndpoint to the gRPCChannelProviders if this has been set with a non-null value. Validation will still go through if it is set with bogus values.
Issue reported in https://github.com/googleapis/java-bigtable/pull/2565
This seems to due to how Bigtable wrappers the generated stubs. BigTable manually calls setEndpoint to for the StubSettings, but does not do the equivalent for setMtlsEndpoint. The EndpointContext is only aware of the TLS endpoint and passes a null value to the ChannelProviders. 
Potential longer term fix: BigTable's wrappers would need to set the mTLS Endpoint. This would be needed for BigTable to support S2A. This does not impact any of BigTable's existing functionality as the endpoint resolution for all non-S2A flows is done via …
=> fix: Only send mtlsEndpoint if it is non-null

.cloudbuild/library_generation/cloudbuild-library-generation-push-exitgate.yaml
The new file .cloudbuild/library_generation/cloudbuild-library-generation-push-exitgate.yaml is based on .cloudbuild/library_generation/cloudbuild-library-generation-push.yaml. The main difference is that the image is output to us-central1-docker.pkg.dev/cloud-sdk-production-pipeline/images-dev, which is the entry point of the AR Exit Gate.
=> feat: add cloudbuild config to publish image via AR Exit Gate

hermetic_build/library_generation/owlbot/templates/java_library/renovate.json
So far these versions are managed both by renovate-bot and Hermetic Build. Since each release of Hermetic Build keeps these template versions up to date, it's better suited to manage these versions via Hermetic Build.
The updates should be reflected by updating `.github/workflows/hermetic_library_generation.yaml` referenced version to the current released one.
=> fix: manage graalvm image versions via Hermetic Build templates _only_

.kokoro/presubmit/downstream-build.sh, settings.xml
https://github.com/googleapis/sdk-platform-java/pull/3814#issuecomment-2919666879
=> chore: temporarily stop using maven mirror

.cloudbuild/library_generation/library_generation.Dockerfile, .cloudbuild/library_generation/library_generation_airlock.Dockerfile
This PR switches the base image of `java-library-generation` to `python-3.13.2-slim`, based on `debian-slim`.
https://hub.docker.com/layers/library/python/3.13.2-slim/images/sha256-8feb1b384bf6755cd1a180d65ec065c742aa1602f026993c33475be6ade2fb2e
Our image is an infrastructure image not meant to be used by our final users.
This solves the ongoing "compatibility layer" problems previously caused by our [GLIBC compatibility layer](https://github.com/googleapis/sdk-platform-java/blob/b87fd5e1af37af01cff1a51e3e50efcf048a3c27/.cloudbuild/library_generation/library_generation.Dockerfile#L37-L55).
For context on this change: [doc](https://docs.google.com/document/d/1wI5VZG5gMCkt4ZyvL6wbf2IeyJrY9pFthFVuAY1kfWw/edit?resourcekey=0-aIfwb5NHqpBlQnbYsD19qw&tab=t.0#heading=h.7xlry2sxrwzj)
=> feat: use debian base image for `java-library-generation`

gapic-generator-java-pom-parent/pom.xml
Manually create the update since renovate bot dashboard is being slow and not creating the PR even after trying to force it multiple times.
=> deps: update google auth library dependencies to v1.37.1

hermetic_build/library_generation/owlbot/templates/java_library/.github/scripts/update_generation_config.sh, hermetic_build/library_generation/owlbot/templates/java_library/.github/workflows/update_generation_config.yaml
Currently, the `get_latest_released_version()` function returns `2.59.0` for gapic-generator-java. This is not correct and is due to an ongoing issue with Maven.
This PR uses the alternative `maven-metadata.xml` files instead, which contains a `metadata/versioning/latest` entry always pointing to the latest version.
```bash
[hi on] diegomarquezp:~$ function get_latest_released_version() {
local group_id=$1
local artifact_id=$2
group_id_url_path="$(sed 's|\.|/|g' <<< "${group_id}")"
url="https://repo1.maven.org/maven2/${group_id_url_path}/${artifact_id}/maven-metadata.xml"
xml_content=$(curl -s --fail "${url}")
latest=$(xmllint --xpath 'metadata/versioning/latest/text()' - <<< "${xml_content}")
if [[ -z "${latest}" ]]; then
echo "The latest version of ${group_id}:${artifact_id} is empty." …
```
=> fix(hermetic-build): use public maven metadata for latest version inference

gax-java/gax/src/main/java/com/google/api/gax/longrunning/OperationTimedPollAlgorithm.java
Context: 433564823
Previously, we improved the error message by adding a link to our LRO documentation, but we need to include additional clarification into why the task was canceled (whether due to a timeout, reaching maximum attempts, or another reason). This PR lists these possible causes in the log statement.
=> fix: improve error messaging for LRO CancellationException

dependencies.txt
Updates to the following upper bound dependency versions:
```
j2objc-annotations=3.1
threetenbp=1.7.2
google.api-client=2.8.1
opentelemetry-semconv=1.34.0
```
=> chore: Update the upper bound dependencies file
